### ISSUE TITLE
Sample app code gone

### ISSUE THREAD

**Issue by jmartine2** [martijn00/XamarinMediaManager#11]
It looks like as of the August 10 update, all of the sample app code is gone. Could it be restored? The app is there, but it is a default app that doesn't play music.

**Comment by martijn00** [comment]
Can you point me to a commit where that happened?

**Comment by jmartine2** [comment]
Sorry for the delay in responding. Yes, it happened in the 8/10/16 commit. It was fine in the 7/28/16 commit, and is still not correct as of the latest commit.
