### ISSUE TITLE
seeking problem in Android

### ISSUE THREAD

**Issue by tonyyyrocks39** [martijn00/XamarinMediaManager#121]
HI,

I am using a slider to show progress of player.When I am sliding it return to back to its original position.
Here is my code.I am calling this entire code in initialization method,So that during page load it starts playing.Here progressbar is a slider.
CrossMediaManager.Current.Play(@url,MediaFileType.AudioUrl);
			CrossMediaManager.Current.PlayingChanged += (sender, e) =>
			{
				ProgressBar.Maximum =Convert.ToDouble( e.Duration.TotalSeconds);
				ProgressBar.Value = e.Position.TotalSeconds;
				int seconds =Convert.ToInt32( e.Duration.TotalSeconds % 60);
				int minutes =Convert.ToInt32( e.Duration.TotalSeconds  / 60);
				Duration.Text = minutes.ToString()+":"+seconds.ToString();

			};
How can I use a slider to seek to a speicific position.

**Comment by jmartine2** [comment]
@tonyyyrocks39  Here's how I do it:

        private void _seekBar_ProgressChanged(object sender, SeekBar.ProgressChangedEventArgs e)
        {
            if (e.FromUser)
            {
                SetSongPosition(e.Progress);
            }
        }

        void SetSongPositionEvent(long barPosition)
        {
            CrossMediaManager.Current.Seek(TimeSpan.FromMilliseconds(barPosition));
        }

I use a granularity of milliseconds. From you code, it looks like you use whole seconds, so you may have to adjust.

**Comment by tonyyyrocks39** [comment]
correct..I got it..But how can I do with a slider.

**Comment by jmartine2** [comment]
Isn't a slider what is called a SeekBar in Android?

**Comment by tonyyyrocks39** [comment]
Okay,Could you please tell me which event i need to fire,if a user slides the slider to specific position(with my codes)

**Comment by jmartine2** [comment]
You need to add an event handler to your SeekBar's ProgressChanged event, which points to the handler function.  Something like:

            _seekBar.ProgressChanged += _seekBar_ProgressChanged;

(in your case _seekbar would be ProgressBar, assuming that it is indeed defined as a SeekBar.

**Comment by tonyyyrocks39** [comment]
I am sorry,still did not get the solution.May be I am not able to explain the issue properly-
1.I have added your nuget package in both android and forms project.
2.Then I have used a slider in forms project whose name is ProgressBar(as seek bar is not available in forms).
3.After that Written codes for playing-

CrossMediaManager.Current.Play(@url,MediaFileType.AudioUrl);
CrossMediaManager.Current.PlayingChanged += (sender, e) =>
{
ProgressBar.Maximum =Convert.ToDouble( e.Duration.TotalSeconds);
ProgressBar.Value = e.Position.TotalSeconds;
int seconds =Convert.ToInt32( e.Duration.TotalSeconds % 60);
int minutes =Convert.ToInt32( e.Duration.TotalSeconds / 60);
Duration.Text = minutes.ToString()+":"+seconds.ToString();

		};

Please note-Here progress bar is a Slider control.
Now my problem is when I drag this slider to a specific position how can i achieve seek function.

As this event _seekBar.ProgressChanged += _seekBar_ProgressChanged; is not available in Xamarin forms,Neither I can use a Progress bar in forms as it too doesnot have a event handler for value changed or progress changed.

**Comment by jmartine2** [comment]
Sorry, I missed the fact that you are using Xamarin Forms. Did you look at the documentation for the Slider class?

https://developer.xamarin.com/api/type/Xamarin.Forms.Slider/

It looks like the event you want is ValueChanged.

**Comment by tonyyyrocks39** [comment]
Nope, Valuechanged will not work here.Anyways I solved it by using a custom renderer for slider where I did a touchdown and touchup event.Now Its working perfectly fine.Thanks for help.
