### ISSUE TITLE
Youtube videos

### ISSUE THREAD

**Issue by zazka1** [martijn00/XamarinMediaManager#124]
Hello,
I'm trying the example from the sample project and it is working with the .mp4 video provided there. However when I try to use youtube video the screen stays black and nothing happens.

**Comment by modplug** [comment]
The url you pasted doesn't seem to work in my browser either

**Comment by zazka1** [comment]
Yes, my bad. I think this link is generated per IP or has expiry date. However try and generate a youtube video download link and try to play it in the player. It won't work.

**Comment by candidodmv** [comment]
@modplug Could you explain to me if this plugin works with Youtube embed URL? Or more specifically, is it possible to play Youtube video with this plugin? In case of positive answer, could you share documentation or usage example?
Thank you.

**Comment by SimonSimCity** [comment]
@candidodmv By following this helpful answer (http://stackoverflow.com/questions/8402457/how-to-get-direct-url-for-youtube-videos#answer-37779863) you should be able to get the direct links to the MP4, WebM and 3gpp files. At least the MP4 - maybe also the WebM - should be playable by this media-player.
