### ISSUE TITLE
V0.3.0-unstable0041 Play and Pause issue

### ISSUE THREAD

**Issue by Vencode** [martijn00/XamarinMediaManager#125]
Hello, 

On the latest unstable version, on Android if you pause the music:

 await CrossMediaManager.Current.Pause(); and then try to resume it using await CrossMediaManager.Current.Play(); 

The music plays from the start.

I've tried to use the CrossMediaManager.Current.PlaybackController.PlayPause() method but had the same behaiviour.

Is there any workaround to make this work ?

Also Android related is there a way to remove the playback controller from the top bar ?

Thanks in Advance

**Comment by Vencode** [comment]
I've just tested todays release, on iOS everything works fine, on android we still have issues with the play when resuming the song. it still restarts it

**Comment by fela98** [comment]
I would strongly recommend using the ExoPlayer plugin. IMHO it's much better and faster and should become the main implementation for Android.

**Comment by fela98** [comment]
This pull request should fix it.

**Comment by Vencode** [comment]
Thank you, so much i confirm its working fine now :)
