### ISSUE TITLE
IOS  TimeSpan does not accept floating point Not-a-Number values.

### ISSUE THREAD

**Issue by jucaripo** [martijn00/XamarinMediaManager#139]
When I ask to play an audio it generates this error in IOS 10.2:

TimeSpan does not accept floating point Not-a-Number values.

this is the command 
CrossMediaManager.Current.Play("http://www.montemagno.com/sample.mp3",MediaFileType.AudioUrl);

**Comment by martijn00** [comment]
Can you check with the new 0.3.0 release?

**Comment by jucaripo** [comment]
Thank Martijn00  the 0.3.0 release work  good for my project.
Great work. :)
