### ISSUE TITLE
Android Audio qeue - music end  play next music issue

### ISSUE THREAD

**Issue by Vencode** [martijn00/XamarinMediaManager#141]
I'm facing an issue when i have a playlist, when the music ends and the navigation occurs automaticaly to the next music, that music is forever loading, it doen't fail, cause it never enters the  failed events:

CrossMediaManager.Current.MediaFailed and CrossMediaManager.Current.MediaFileFailed

But it never starts playing. If I do the navigation to the next music using the following code:

  var index = CrossMediaManager.Current.MediaQueue.Index + 1;
                    if (index >= 0)
                    {
                        CrossMediaManager.Current.MediaQueue.SetIndexAsCurrent(index);
                        await CrossMediaManager.Current.Play();
                    }

It works fine, if then i navigate back to the first music and let it finish the navigation to the next music works fine aswell. It seems that I only have this issue on the first navigation.

On iOS it always works fine.

Any thoughts ?

**Comment by keertanadapari** [comment]
Hi,any solution ?am also facing same problem.
