### ISSUE TITLE
Play() methods plays from the beginning and doesn't work after play and SeekTo issue

### ISSUE THREAD

**Issue by riandesign** [martijn00/XamarinMediaManager#144]
I have this code:

```
private async void Play(fileUri) {
     // e.g., fileUri = "http://somesite.com/someaudio.mp3";
     await CrossMediaManager.Current.Play(fileUri);
}
```

And always I play the audio, it loads the audio through HTTP all again and plays from beginning.
What's the right way to handle the player?

Also, I have this:
```
private async void Pause(object obj) {
     await CrossMediaManager.Current.Pause();
}
```
If I play a sound, pause it and play it again, it plays like a second and stops, I don't know the reason.

**Comment by riandesign** [comment]
@jmartine2 , any thought? Could you help me on this?

**Comment by jmartine2** [comment]
I'm not sure. I don't currently have that issue. I also play only from local files, not URL's, so I don't have any experience with that.

**Comment by jmartine2** [comment]
Here's what I do:

When starting a song for the first time:

```
IMediaFile mediaFile = new MediaFile { Type = MediaFileType.Audio, Url = mediaSource };
await CrossMediaManager.Current.Play(mediaFile);
```

Pause:

`CrossMediaManager.Current.Pause();`

Resume:

`                await CrossMediaManager.Current.PlaybackController.Play();
`

**Comment by riandesign** [comment]
@jmartine2 thank you! Just one more question:
Can you give me a clue how to play an audio from a certain point (time) of it?
I tried "Seek", but it doesn't work and plays from beginning.

**Comment by jmartine2** [comment]
I don't know if you can Seek before playing the media. I only do it while the media is already playing. That may be your problem. Here is what I do:

For instance, if I want to seek to 5 seconds into the song, I would do this:

`CrossMediaManager.Current.Seek(TimeSpan.FromMilliseconds(5000));
`

**Comment by riandesign** [comment]
@jmartine2, so it doesn't work like MediaPlayer on Android?
For instance, if I do the code below, on Android it plays exatcly from 3 seconds of the audio:
`player.SeekTo(3000);`

Isn't there any option for that on Plugin.MediaManager?

**Comment by riandesign** [comment]
@jmartine2 I found the SeekTo method, but it only works after the player is already set.
For example, in the **if block** below, app crashes, but the **else block** works well.

```
if (_mediaFile == null) {
    // It doesn't work
    _mediaFile = new PluginMediaManager.MediaFile { Type = MediaFileType.Audio, Url = fileUri };
    await CrossMediaManager.Current.PlaybackController.SeekTo(10);
    await CrossMediaManager.Current.Play(_mediaFile);
} else {
    // It works!
    await CrossMediaManager.Current.PlaybackController.SeekTo(10);
    await CrossMediaManager.Current.PlaybackController.Play();
}
```

How should I set `SeekTo` when I don't have the player set yet? Any idea?

**Comment by jmartine2** [comment]
I'm honestly not sure. As I said, my only experience is with seeking while the media is already playing. Maybe someone else knows.

**Comment by jmartine2** [comment]
I have actually run into this problem myself now. I am trying to start playing a song from a specific position. If I call CrossMediaManager.Current.Play(), and then call CrossMediaManager.Current.Seek() right afterward, the song starts playing for a second or two from the beginning before jumping to the sought position. Is there a way to pre-load the media (perhaps in a paused state) so that I can seek to the desired position before the user hears anything?

**Comment by olehdeyneka** [comment]
@jmartine2 I am running into the same issue, were you able to resolve this? I am trying to start player from the specific position, but it plays from the beginning first.

**Comment by axeira** [comment]
Same problem here, after seekTo it stops working and I can see the error 
E/MediaPlayer(14143): Attempt to perform seekTo in wrong state: mPlayer=0x90d8b2c0, mCurrentState=2

**Comment by axeira** [comment]
I'm trying to jump in a streamed mp3 when moving a slider

private async void ProgressBarSlider_ValueChanged(object sender, ValueChangedEventArgs e)
        {
            //if user moved the slider
            if (!sliderProgramChanged)
            {
                //jump to new position
                recPosition = recDuration * e.NewValue / 100;
                await CrossMediaManager.Current.PlaybackController.SeekTo(recPosition);
                await CrossMediaManager.Current.Play();
                Position.Text = XCAPIClass.SecondsToString(recPosition, false);
                Duration.Text = XCAPIClass.SecondsToString(recDuration, false);
            }

        }

**Comment by deepakyogi1995** [comment]
Hello @riandesign ,

   I want to play pause audio.
await CrossMediaManager.Current.Pause(); pause is working with this code but 
pause audio not pay again i used this code for play pause video.

 await CrossMediaManager.Current.PlaybackController.Play();
