### ISSUE TITLE
ExoPlayer - Can't play media files with a # (hash sign) in filename or path

### ISSUE THREAD

**Issue by jmartine2** [martijn00/XamarinMediaManager#156]
Using the ExoPlayer implementation, I am unable to play any songs where either the filename or any part of the file path contains a hash/pound sign (#). If I switch back to the regular Android implementation, the same files play fine.

I do not get any exceptions or other errors. The music simply does not play.

**Comment by martijn00** [comment]
I've added a new branch to update ExoPlayer to 2.2.0: https://github.com/martijn00/XamarinMediaManager/tree/exoplayer2.2.0

The code compiles but for some reason it won't play.
