### ISSUE TITLE
How do i do playback local music file ?

### ISSUE THREAD

**Issue by fumiya-kume** [martijn00/XamarinMediaManager#159]
How do i do playback local music file ?

**Comment by mgsmith20** [comment]
I am wondering how to play back a local video file also.

**Comment by modplug** [comment]
If you store your files in shared / PCL project I advice you to read this guide: https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/files/

**Comment by mgsmith20** [comment]
I thought the source property is a string?  Do I set a different property?

Thanks,
Michael Smith

**Comment by priehle** [comment]
I'm curious how to do this as well. I am using PCLStorage (recommended in the article above), setting the source to FileSystem.Current.LocalStorage + "/" + <Folder Path> + "/" + <File Name>. This resolves to something like this in iOS:

/var/mobile/Containers/Data/Application/AE6136ED-28C4-482F-XXXX-XXXXXXXXXXXX/Documents/../Library/books/1103/video/635660817460381870.mp4

and this in Android:

/data/user/0/XXXX.Droid/files/books/1103/video/635660817460381870.mp4

Setting the source this way works with Xamarin Forms (ie. Image) and other plugins I've used (ie. FFImageLoading), but it doesn't seem to work in this one.

**Comment by RussellTaylor83** [comment]
Has anyone figured this out yet please? Using a MediaPlayer I was able to just pass it a local resource e.g. 

`_player = MediaPlayer.Create(this, Resource.Raw.myMp3);`

I'm not sure this is entirely possible as the library uses Java.IO.File(), and this seems to suggest it's not appropriate to use a resource

http://stackoverflow.com/questions/37083900/android-load-java-io-file-from-resource-file

Thank you

**Comment by RussellTaylor83** [comment]
I have figured it out - 

CrossMediaManager.Current.Play(Uri.Parse("android.resource://[PackageName]/" + Resource.[YourResourceName]).ToString());

**Comment by priehle** [comment]
That's great but it doesn't cover cases when the file is not a resource. My files are extracted from a zip file that I download online.

**Comment by kwacks** [comment]
I'm also trying to figure this out for iOS. I  tried NSBundle.MainBundle.PathForResource(AppConstants.ResourceFiles.NotificationSound, null) but the file failed. 
Also worth noting it's a .caf file. 
Any tips on how to get and play local files?

**Comment by MichaelMcKinney** [comment]
This seems to be the only way to play media that requires custom http headers to access the files.

Has anyone had any breakthroughs on this? I'm also trying to play a locally downloaded file using [PCLStorage](http://www.c-sharpcorner.com/article/local-file-storage-using-xamarin-form/) in the exact same way as @priehle.

The files I'm using are _not_ resources, and instead are saved locally after downloading. The paths look something like this:

iOS:
"/var/mobile/Containers/Data/Application/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/Documents/../Library/myVideoFile.avi"

Android:
"/data/user/0/com.bundleId.appId/files/myVideoFile.avi"

Thanks everyone, any ideas are greatly appreciated!

**Comment by jmartine2** [comment]
Instead of using that version of CrossMediaManager.Current.Play() that takes a string, you should try creating a MediaFile object yourself and calling the version of that method that takes an IMediaFile.

**Comment by morejump** [comment]
anyone has a solution??

**Comment by upCodeS** [comment]
@MichaelMcKinney Hey I was playing around with your code, it seems to be what I'm looking for in my project. The variable 'myFile.Path', what exactly is going on there?

**Comment by mattiabaldinger** [comment]
I found the solution for IOS in the sample project, but still no solution for android, also with the things mentioned in the other comments. Anyone?

**Comment by MichaelMcKinney** [comment]
I looked back on my solution from before and it has long since been changed. However, I found the place where we get the file path. Once we have the file path we can use the `CrossMediaManager.Current.Play(filePath)` piece from before.

Here is a helper function we use to save the downloaded file as a byte array to local storage. The we return the path for that file. 

        public static async Task<string> WriteFileAsync(byte[] content, string fileExtension, int documentId
        {
            var rootFolder = FileSystem.Current.LocalStorage;            
            var specificFileType = "myFile";            

            var fileName = string.Concat(specificFileType, "_", documentId, fileExtension);

            IFolder subFolder = null;
            var subFolderExists = await rootFolder.CheckExistsAsync("MyAppResources");

            if (subFolderExists == ExistenceCheckResult.NotFound)
            {
                subFolder = await rootFolder.CreateFolderAsync("MyAppResources", CreationCollisionOption.ReplaceExisting);                
            }
            else
            {
                subFolder = await rootFolder.GetFolderAsync("MyAppResources");
            }

            var fileExists = await subFolder.CheckExistsAsync(fileName);

            if (fileExists == ExistenceCheckResult.NotFound)
            {
                var file = await subFolder.CreateFileAsync(fileName, CreationCollisionOption.ReplaceExisting);
                var stream = await file.OpenAsync(FileAccess.ReadAndWrite);

                stream.Write(content, 0, content.Length);

                return file.Path;
            }

            var filePath = subFolder.Path + "/" + fileName;            

            return filePath; 
        }


Once you have the file path you should be able to use

    var pathToFileURL = new System.Uri(filePath).AbsolutePath;
    CrossMediaManager.Current.Play("file://"+ pathToFileURL);

Good luck everyone! this is just a part of the infrastructure I have set up, but these should be the important parts.

**Comment by mattiabaldinger** [comment]
@MichaelMcKinney thanks for the hint to copy the files to local storage. with that workaround i could solve my problem..
