### ISSUE TITLE
Xamarin.Forms enable full screen

### ISSUE THREAD

**Issue by candidodmv** [martijn00/XamarinMediaManager#162]
Hi, how could i show video player as full screen, both Android and iOS? Is it possible?

Thanks!

**Comment by modplug** [comment]
Hi. You need to set the VideoView AspectMode to AspectFill. This should work on iOS. I know we have some issues with this on Android at the moment

**Comment by candidodmv** [comment]
Right, but let me check if you are understand what I'm referring. see images bellow, there is a red circle on the feature:
![andorid_player](https://cloud.githubusercontent.com/assets/1034797/24266677/6ee7721c-0fe6-11e7-946d-7f4286d2a6c6.PNG)
![ios_player](https://cloud.githubusercontent.com/assets/1034797/24266676/6ee70a3e-0fe6-11e7-8562-afd0524abe49.PNG)

**Comment by modplug** [comment]
You will have to code that yourself. The VideoView is merely a view

**Comment by candidodmv** [comment]
I'm doing exactly, my intuition was correct. Thanks!

**Comment by JohnGalt1717** [comment]
@candidodmv Can you share some code on how you setup full screen?

**Comment by candidodmv** [comment]
Hi @JohnGalt1717 , I can't share the code here because is a part of private product. But let me explan to you, and you will see that there's no magic. I assume that you are you using Xamarin.Forms

1) You must create a new ContentView(C# or XAML) and put your video frame that. I suggest to you use the official sample:
https://github.com/martijn00/XamarinMediaManager/blob/develop/Samples/Forms/MediaForms/MediaFormsPage.xaml

2) with the above code you be able to see the player working alone on the page, probably you will see further the controls of the player and on the top of the screen the navigation bar, if you are using the [Xamarin.Forms.NavigationPage.PushAsync ](https://developer.xamarin.com/api/member/Xamarin.Forms.NavigationPage.PushAsync/p/Xamarin.Forms.Page/) Method, the trick is perform the navigation to the new viewmodel with no navigation pushing new page as modal, see more on [official documentation](https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/navigation/hierarchical/#Performing_Navigation)

3 at the end you need create a button on the page where the player frame is, and bind an event  to close itself on tap. and for design purpose to control the visibility of the controls, showing and hiding with basic logic. to hide controls I've used an timeout function for wait some miliseconds and to show when the user touch on the screen.

and done, simple as ride a bicycle.

questions, respond this issue.

**Comment by programadorpazo** [comment]
Ayuda.Quiero Mostrar un video de youtube en una página que utilize toda la pantalla.

It would be very useful.

**Comment by Shayether** [comment]
@candidodmv @JohnGalt1717   Did any one managed to get this done, please help me with a jump start

**Comment by EchoSKSh** [comment]
@programadorpazo did u managed to get this done. Can u help on this
