### ISSUE TITLE
Xamarin.Android.Support.v4 dependencies too high for Xamarin.Forms

### ISSUE THREAD

**Issue by JKennedy24** [martijn00/XamarinMediaManager#163]
I am using Xamarin.Forms and Xamarin.Forms maps.

I added this nuget package and it upgraded my:

```
Xamarin.Android.Support.v4 (>= 25.1.1)
Xamarin.Android.Support.v7.AppCompat (>= 25.1.1)
```

I have always been informed by Xamarin, Never upgrade these packages, let Xamarin.Forms determin the version otherwise it will cause problems.

Xamarin.Forms is on:

`Xamarin.Android.Support.v4 (>= 23.3.0)`

So low and behold it caused problems.

Do these dependencies need downgrading a version?

**Comment by martijn00** [comment]
On Xamarin.Forms 2.3.3.193 the dependency on the old Support is removed and it is now possible to use v25.1.1 and higher. Install the latest version from Nuget https://www.nuget.org/packages/Xamarin.Forms/2.3.3.193 to use this.

**Comment by trandinhnam** [comment]
So, do you mean we need to downgrade xamarin to install this plugin?
