### ISSUE TITLE
Xamarin.Forms droid seek bar not working

### ISSUE THREAD

**Issue by dhruvcom** [martijn00/XamarinMediaManager#164]
On tapping play button video starts however seekbar gets filled and reaches to end and then nothing happens

**Comment by candidodmv** [comment]
There is a percentage cal problem, just do something like this:
```
var androidProgress = (e.Progress / 100);
var iosProgress = e.Progress;
Progress = Device.OnPlatform<double>(e.Progress, (e.Progress / 100));
```

**Comment by modplug** [comment]
Guys, I'd prefer it if you fixed the actual problem by committing a PR for it :) That workaround will stop working once the bug is fixed in the Android VideoPlayerImplementation

**Comment by Happypig375** [comment]
Why is this issue not closed?
