### ISSUE TITLE
Cant install  in Xamarin.Android 

### ISSUE THREAD

**Issue by fumiya-kume** [martijn00/XamarinMediaManager#165]
Ver 0.4.0 is cant install Xamarin.Android
https://lh3.googleusercontent.com/-j_FUA4o2LEo/WNj0NMX20RI/AAAAAAAAIZI/djdJ6b8CAqM/s0/devenv_2017-03-27_20-15-00.png

**Comment by martijn00** [comment]
You need to use Android support v25.1.1 or higher. Update your Nuget packages and it will work.
