### ISSUE TITLE
Normalize Progress

### ISSUE THREAD

**Issue by candidodmv** [martijn00/XamarinMediaManager#166]
Hi,

There's a different calculation for Android and iOS. Not would be convenient to keep this with the same value?

Loook at 
https://github.com/martijn00/XamarinMediaManager/blob/develop/MediaManager.Android/Video/VideoPlayerImplementation.cs#L66

and 
https://github.com/martijn00/XamarinMediaManager/blob/develop/MediaManager.iOS/VideoPlayerImplementation.cs#L197

There's a division by 100 on Android, what not happens on iOS.

Thanks!

**Comment by modplug** [comment]
See my comment in #164

**Comment by candidodmv** [comment]
I've do a PR, and was committed.
