### ISSUE TITLE
Video Player Position issue

### ISSUE THREAD

**Issue by candidodmv** [martijn00/XamarinMediaManager#167]
Hi,

On iOS duration works as should be, but on Android there some problem, the value keeps jump large space, not increase one-by-one seconds like a timer works.

Thanks!

**Comment by modplug** [comment]
Are you talking about duration or progress?

**Comment by candidodmv** [comment]
Sorry by confusing, I wanted to say "Position", look at the screenshot attached for a better understand.
![ezgif-3-88f2897654](https://cloud.githubusercontent.com/assets/1034797/24403647/30fb86da-1394-11e7-922a-fbc49f908b78.gif)

Notice that timer on the bottom does jumps not increase one by one, like a counter.

ps. on iOs works fine.
ps2. this is a youtube video.
