### ISSUE TITLE
Android ExtractMediaInfo throwing Java.Lang.RuntimeException

### ISSUE THREAD

**Issue by jmartine2** [martijn00/XamarinMediaManager#168]
Occasionally in my app, I am getting an unhandled Java.Lang.RuntimeException when calling ExtractMediaInfo(). My stack trace shows that it's occurring in the following line of MediaExtractorImplementation.GetMetadataRetriever():

`await metaRetriever.SetDataSourceAsync(inputStream.FD);
`

The message of the exception is:

> setDataSource failed: status = 0x80000000

I don't think that a Java.Lang.RuntimeException should be coming all the way back to the app. A few ideas:

1) If this occurs, is there anything that we can do about it? Is it important that the above method call succeed? Should the app need to know that it failed? If not, does it make sense to just silently eat the exception in MediaExtractorImplementation?

2) If it can't be overcome, and it's important that the app knows that it failed, I think we need to catch it and throw a more specific exception. 
  2a) Define a new custom exception type in IMediaExtractor?
  2b) Use a built-in C# / .NET exception type with a descriptive Message?

Thoughts?

**Comment by jmartine2** [comment]
@candidodmv I am not using MVVM. I am just calling MediaExtractorImplementation.GetMetadataRetriever() directly.

**Comment by candidodmv** [comment]
all right! Thanks
