### ISSUE TITLE
UWP sample app crashes

### ISSUE THREAD

**Issue by jmartine2** [martijn00/XamarinMediaManager#17]
I tried the UWP sample app, but can't get it to work. I'm running on a Windows 10 laptop.  When I start the app, it immediately crashes with the following exception:

> An exception of type 'System.Runtime.InteropServices.COMException' occurred in Plugin.MediaManager.dll but was not handled in user code
> 
> Additional information: ClassFactory cannot supply requested class (Exception from HRESULT: 0x80040111 (CLASS_E_CLASSNOTAVAILABLE))

It is happening in the following line of code in MediaManagerImplementation.cs:

> _player = new MediaPlayer();

Here is the call stack:

> Plugin.MediaManager.dll!Plugin.MediaManager.MediaManagerImplementation.MediaManagerImplementation() Line 25   C#
>   Plugin.MediaManager.dll!Plugin.MediaManager.CrossMediaManager.CreateMediaManager() Line 34  C#
>   [External Code] 
>   Plugin.MediaManager.dll!Plugin.MediaManager.CrossMediaManager.Current.get() Line 20 C#
>   MediaSample.UWP.exe!MediaSample.UWP.MainPage.MainPage() Line 21 C#
>   [External Code] 
>   MediaSample.UWP.exe!MediaSample.UWP.App.OnLaunched(Windows.ApplicationModel.Activation.LaunchActivatedEventArgs e) Line 78  C#

**Comment by modplug** [comment]
Hi @jmartine2. 
I've seen that bug when I don't have the anniversary update installed on my computer.
I just haven't had time to look into it yet.

**Comment by jmartine2** [comment]
I can confirm that it works for me now that I have the anniversary update installed on my laptop. This probably should remain open until the crash is fixed for non-anniversary systems.

**Comment by martijn00** [comment]
Fixed
