### ISSUE TITLE
Videoview not appearing in iOS (Only sound of video coming, not visual)

### ISSUE THREAD

**Issue by Denaindra** [martijn00/XamarinMediaManager#172]
Hi 
 
The video view is not appearing in the given layout ... But when we call the play meathod , we can hear the video being played (Only the sound comes , not the visual). Please note error only occurs in iOS , in android the video plays as expected. 
Nuget Packag Version : 0.4.0

Thanks in advance

**Comment by modplug** [comment]
Hi there. Make sure you call VideoViewRenderer.Init(); in FinishedLaunching() in your AppDelegate.cs
