### ISSUE TITLE
Multiple VideoViews

### ISSUE THREAD

**Issue by ghost** [martijn00/XamarinMediaManager#173]
Related to #171 and #100, except I have no intention of playing multiple videos at the same time. What I would like to do is have multiple views on one or more pages of a carousel where touching each will stop the currently playing video and start whichever one was clicked on. The views can and should be invisible when they are not playing a video and would have a placeholder image.

What would be the proper way to implement this, seeing as how there's only a singleton instance to handle the media? It seems to me that if you try to create multiple VideoViews, the singleton instance loses it's reference to the media. Can I just set the source for the VideoView each time the user presses the image, so that the singleton instance regains it's reference? Unable to test right now since I'm blocked by #159.

**Comment by martijn00** [comment]
Should be possible now
