### ISSUE TITLE
android version requirement 

### ISSUE THREAD

**Issue by cansado2930** [martijn00/XamarinMediaManager#175]
Hello,
I have discover your plugin by Xamarin blog and it is very interesting. I have tried and work very well. I have a question About Android. Is it possible to use with Android 4.2, 4.4 or 5?
Thanks

**Comment by martijn00** [comment]
As you can see in the readme the plugin supports from Android api level 9 and up: https://github.com/martijn00/XamarinMediaManager#build-status

Make sure you compile against Android v24 or higher to make the Android support libraries work.
