### ISSUE TITLE
How do you use the queue?

### ISSUE THREAD

**Issue by RussellTaylor83** [martijn00/XamarinMediaManager#176]
#I've tried this various ways, and with little success.

```
MediaFile file = new MediaFile(uri.ToString());

for (var i = 0; i < 5; i++)
{
       CrossMediaManager.Current.MediaQueue.Add(file);
}
CrossMediaManager.Current.MediaQueue.Repeat = RepeatType.RepeatAll;
CrossMediaManager.Current.Play();
```

So this *should* play the same file fives times in a row, and then repeat indefinitely. It only plays the file once, and on the next time I call Play() or PlayNext() nothing happens.

What am I doing wrong please?

Thank you

**Comment by martijn00** [comment]
The Queue is not really designed to add files like that. Rather use:
`List<MediaFile>() files;
 CrossMediaManager.Current.Play(files);`

But looking at that you want to play the same file over and over you could just do:
` CrossMediaManager.Current.Play(uri.ToString());`
And set repeat to All

**Comment by RussellTaylor83** [comment]
Thank you for your help. This only plays once:

```
CrossMediaManager.Current.Play(uri.ToString());
CrossMediaManager.Current.MediaQueue.Repeat = RepeatType.RepeatAll;
```

I must be using repeat all incorrectly as well?

**Comment by keertanadapari** [comment]
Hi,i am having problem to play songs in sequentially which is in queue.please help me.i fallowed the below steps to add files to queue and play songs one by one.but its not working for me.
 await CrossMediaManager.Current.Play(media_file);
 CrossMediaManager.Current.MediaQueue.Repeat = RepeatType.RepeatAll;

**Comment by gtgatsby** [comment]
I also can't get the Queue to work properly in the MediaForms.Android plugin. It doesn't work in the sample provided, either. It skips the first entry, and starts playing the second, then doesn't play the others. I tried taking a look, but the code is pretty complex, and I couldn't get my breakpoints to be hit...
