### ISSUE TITLE
cannot find Plugin.MediaManager.Forms

### ISSUE THREAD

**Issue by hs79hs** [martijn00/XamarinMediaManager#179]
After I run the following command in Package Manager Console,
Install-Package Plugin.MediaManager
The package is successfully installed.

But then in my project, it can find Plugin.MediaManager, but cannot find Plugin.MediaManager.Forms, and thus cannot recognize VideoViewRenderer.

Do I need to install Plugin.MediaManager.Forms separately? How? Thanks.

**Comment by SimonSimCity** [comment]
@hs79hs `Plugin.MediaManager.Forms` is a separate package, which depends on `Plugin.MediaManager`. You now just need to call `Install-Package Plugin.MediaManager.Forms` and you should be good to go.

**Comment by hs79hs** [comment]
Thank you very much.
