### ISSUE TITLE
Local files not working on some Android devices

### ISSUE THREAD

**Issue by jmartine2** [martijn00/XamarinMediaManager#18]
I can not get Xamarin Media Manager to work on some devices with local files.  On two of my devices (Samsung Galaxy S4 and Samsung Galaxy Tab 2), everything works fine for both HTTP sources and local files. However, on two other devices (Kindle Fire and HTC One M8), HTTP sources work fine, but local files refuse to play.

I hooked the Kindle Fire up to my development machine so that I could debug it.  In the sample app, I changed the url from:
"http://www.montemagno.com/sample.mp3"
to
"/storage/sdcard1/Music/Fresh Prince of Bel Air Theme Song.mp3"
(which is an existing file on the tablet)

I found that the failure is occurring in the following line in MediaPlayerService.cs:

`await mediaPlayer.SetDataSourceAsync(ApplicationContext, Android.Net.Uri.Parse(audioUrl));
`
That line is throwing the following exception:

> Java.Lang.RuntimeException: setDataSource failed: status = 0x80000000
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
> 

Again, the exact same code works fine on all local files on my two Samsung devices, but on the other two devices, I can't get it to work with ANY local MP3 files (including files that work fine on my phone). The same MP3 files also play fine on the Kindle Fire with the stock Amazon Music app.

Has anyone else run into this issue?

**Comment by martijn00** [comment]
Is there any information about this available on Google? Maybe a reason, or a workaround?

**Comment by modplug** [comment]
http://stackoverflow.com/questions/18917160/mediametadataretriever-setdatasourcenative-method-causes-runtimeexception-sta

**Comment by jmartine2** [comment]
@modplug , That SO question is about MediaMetadataRetriever, not MediaPlayer. 

@martijn00 , I did look at serveral StackOverflow questions, but none of the solutions have worked so far.   
[This one](http://stackoverflow.com/questions/16395559/mediaplayer-setdatasource-failed-with-status-0x80000000-for-ringtone-set-by-file) looked most promising, so I tried implementing the accepted solution. Unfortunately, all 3 methods that it tries (using string path, using URI, and using FileDescriptor) give the same exception on the Kindle Fire. :(

**Comment by jmartine2** [comment]
Ok, I fixed it!  

It turns out that there were issues with both MediaPlayer.SetDataSource() and MediaMetadataRetriever.SetDataSource().  Both of those method throw exceptions on the Kindle Fire (and the HTC One) when used with a path to a local file.  However, if you open a FileInputStream and use the versions of those methods that take a File Descriptor, it works fine.

I will send a pull request for these changes soon.

**Comment by jmartine2** [comment]
Thanks to @modplug for the link that helped me solve the MediaMetadataRetriever part.

**Comment by modplug** [comment]
Great work!
fre. 16. sep. 2016 kl. 19.04 skrev Joe Martinez <notifications@github.com>:

**Comment by martijn00** [comment]
Update is up on Nuget: https://www.nuget.org/packages/Plugin.MediaManager/0.0.5
