### ISSUE TITLE
Only works on the first run

### ISSUE THREAD

**Issue by luigicatanoso** [martijn00/XamarinMediaManager#180]
Hello everyone. I'm new on Xamarin.Forms and I’m having issues using this plugin. Every time I start the video the first time it plays, but if I go back to the selection and click again it doesn’t play at all (the video is blank). I have no choice: restart my application, so everything works just at the first attempt, always. All this occurs following the code samples, as well doing copy and paste, but why?
![2017-04-06](https://cloud.githubusercontent.com/assets/26625155/24773746/a316f34c-1b16-11e7-985c-5a80e05933a1.png)

**Comment by sharatchandra99** [comment]
Hi, 

Am also getting the same issue. The video is playing only once and when i go to previous page and come back the video page again, its not playing any video file.

**Comment by AndyAnand** [comment]
Hello, i'm also having the same issue. Playing the video for the first time works fine but when backbutton is pressed (window closed) and a new window is created, you get nothing but a black screen.

**Comment by OPcody** [comment]
Hello everyone,

I have been able to recreate this as well. 
So far from investigation, it appears that the CrossMediaManager.Current.VideoPlayer does not reset. 
You can see this by checking the status during OnAppearing

Does anyone know how to reset it?

Thanks!

**Comment by corgalore** [comment]
Okay, I have the same problem. I can get the video to start playing again if I hit Stop first, then Play again, but the progress events don't fire on any video after the first one.

**Comment by codercampos** [comment]
Confirmed this. I'll try to check it later this week and help the repo (because this is an awesome plugin for Forms)

**Comment by martijn00** [comment]
@codercampos I would be really happy to see some fixes and PR's coming!

**Comment by tankitty** [comment]
@codercampos  at first time can play url normally after that when you set player.Source = "http://..." or same source you will get error 

 java.io.FileNotFoundException: No content provider
