### ISSUE TITLE
I'm not able to control or mute the volume on any platform

### ISSUE THREAD

**Issue by RobTillie** [martijn00/XamarinMediaManager#181]
It seems the volume control only works one-way, from OS -> MediaManager. It does not do anything if I set VolumeManager.Mute or CurrentVolume.

It seems like I could get this to work easily by Invoking VolumeChanged in the setters of the VolumeManager properties. For example, the UWP implementation would then handle this event in VolumeManagerOnVolumeChanged and set the mute and volume properties of the actual player.

Is my assumption correct? If so, I could make a PR to enable two-way volume control.

**Comment by martijn00** [comment]
On most platforms this is not implemented yet.

https://github.com/martijn00/XamarinMediaManager/blob/develop/MediaManager.Android/VolumeManagerImplementation.cs#L10

https://github.com/martijn00/XamarinMediaManager/blob/develop/MediaManager.UWP/VolumeManagerImplementation.cs

https://github.com/martijn00/XamarinMediaManager/blob/develop/MediaManager.iOS/VolumeManagerImplementation.cs

I would accept a PR to fix this!

**Comment by Levvy055** [comment]
For it's also not working.
Calling `_volumeManager.CurrentVolume = someValue;` do nothing in UWP
Also I figured that MaxVolume is equal to 0. Why is that even is song is playing pretty loud?

**Comment by mike-rowley** [comment]
I don't believe Volume has been implemented on UWP as I was the one that did the implementation on IOS and Android.  If you have a PR for this we would be very interested in it.

**Comment by SantaRita** [comment]
Any solution to control volume ?
