### ISSUE TITLE
Problem showing video

### ISSUE THREAD

**Issue by tanure** [martijn00/XamarinMediaManager#182]
Hello. I'm write an app on Xamarin.Forms. I used the Xamarin Media Manager, like sample code. But, the video doesn't play. I tired to create a new app and use the same page like samples, but I don't have sucess!

This plugin plays the youtube videos? And...What is the problem um my page:

mypage.xaml :
`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
              xmlns:forms="clr-namespace:Plugin.MediaManager.Forms;assembly=Plugin.MediaManager.Forms"
             x:Class="ANAC.Cidadao.Pages.PrincipalDetailPage">

    <ContentPage.Content>
        
        <StackLayout x:Name="stk">
            
         
            <Grid>
                <Grid.RowDefinitions>
                    <RowDefinition Height="4*"/>
                    <RowDefinition Height="1*"/>
                </Grid.RowDefinitions>
                <forms:VideoView Grid.Row="0" Grid.RowSpan="1" HorizontalOptions="FillAndExpand" HeightRequest="250"
                     Source="http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4" AspectMode="AspectFill"/>
                <Grid HorizontalOptions="FillAndExpand" Grid.Row="1" Grid.RowSpan="1" Margin="20">
                    <Grid.RowDefinitions>
                        <RowDefinition Height="1*"/>
                        <RowDefinition Height="6*"/>
                    </Grid.RowDefinitions>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition/>
                        <ColumnDefinition/>
                        <ColumnDefinition/>
                    </Grid.ColumnDefinitions>
                    <StackLayout Grid.Row="0" Grid.ColumnSpan="3" Orientation="Vertical">
                        <StackLayout Orientation="Horizontal">
                            <Label Text="Duration: "></Label>
                            <Label x:Name="Duration"/>
                        </StackLayout>
                        <ProgressBar x:Name="ProgressBar" Grid.ColumnSpan="3" HorizontalOptions="FillAndExpand"></ProgressBar>
                    </StackLayout>

                    <Button Grid.Row="1" Grid.Column="0" TextColor="White" BackgroundColor="Gray" HeightRequest="50" VerticalOptions="Center" Text="Play" WidthRequest="100" Clicked="PlayClicked"></Button>
                    <Button Grid.Row="1" Grid.Column="1" TextColor="White" Text="Pause" BackgroundColor="Gray" HeightRequest="50" VerticalOptions="Center" WidthRequest="100" Clicked="PauseClicked"></Button>
                    <Button Grid.Row="1" Grid.Column="2" TextColor="White" Text="Stop" BackgroundColor="Gray" HeightRequest="50" VerticalOptions="Center" WidthRequest="100" Clicked="StopClicked"></Button>
                </Grid>
            </Grid>

            <Button Image="feedback.png" Text="Registro de reclamação" Style="{StaticResource buttonsStyle}" HeightRequest="80" x:Name="btnFeedback" Clicked="Button_Clicked" />

            <Button Image="estatistica.png" Text="Estatísticas" Style="{StaticResource buttonsStyle}"  HeightRequest="80" x:Name="btnEstatisticas" Clicked="btnEstatisticas_Clicked"/>

            <Button Image="direitos.png" Text="Seus direitos" Style="{StaticResource buttonsStyle}" HeightRequest="80" x:Name="btnDireitos" Clicked="btnDireitos_Clicked" />

        </StackLayout>
    </ContentPage.Content>
</ContentPage>`

Mypage.cs :
`
using Plugin.MediaManager;
using Plugin.MediaManager.Abstractions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Xamarin.Forms;

namespace ANAC.Cidadao.Pages
{
    public partial class PrincipalDetailPage : ContentPage
    {
        private IPlaybackController PlaybackController => CrossMediaManager.Current.PlaybackController;

        public PrincipalDetailPage()
        {
            InitializeComponent();
            CrossMediaManager.Current.PlayingChanged += (sender, e) =>
            {
                ProgressBar.Progress = e.Progress;
                Duration.Text = "" + e.Duration.TotalSeconds.ToString() + " seconds";
            };

        }

        private async void Button_Clicked(object sender, EventArgs e)
        {
            await Navigation.PushAsync(new ReclamacaoPage());
        }

        private async void btnEstatisticas_Clicked(object sender, EventArgs e)
        {
            await Navigation.PushAsync(new EstatisticasPage());
        }

        private async void btnDireitos_Clicked(object sender, EventArgs e)
        {
            await Navigation.PushAsync(new SeusDireitosPage());
        }

        void PlayClicked(object sender, System.EventArgs e)
        {
            PlaybackController.Play();
        }

        void PauseClicked(object sender, System.EventArgs e)
        {
            PlaybackController.Pause();
        }

        void StopClicked(object sender, System.EventArgs e)
        {
            PlaybackController.Stop();
        }
    }
}
`

**Comment by martijn00** [comment]
As you can see in some other issue's, for Youtube you need the direct link to the video file to be able to play it. See also: https://github.com/martijn00/XamarinMediaManager/issues/124
