### ISSUE TITLE
Android notification crashing

### ISSUE THREAD

**Issue by jmartine2** [martijn00/XamarinMediaManager#183]
Two of my beta testers got new phones, running Nougat (It' the LG V20 if that matters). They are my first users to run Nougat, I believe. Since then they are producing the following unhandled exception:

> android.app.RemoteServiceException: Bad notification posted from package com.elephanigma.starmygrooves: Couldn't cache contentViews: package=com.elephanigma.starmygrooves
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1675)
> 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 	at android.os.Looper.loop(Looper.java:154)
> 	at android.app.ActivityThread.main(ActivityThread.java:6247)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

Unfortunately, the stack trace does not show any of my code or MediaManager code. However, I do know that my app does not create any Android notifications on its own. The only notification is the one created by XamarinMediaManager.

Only these two beta testers are generating the crash. So, I'm thinking that it is specific to either Nougat or their phone model in particular.

Has anyone else run into this bug?

Can anyone make sense of the crash report?

FYI, I posted this on StackOverflow in February, and got no responses. It has some more details:
http://stackoverflow.com/questions/42335277/

**Comment by jmartine2** [comment]
An update on this issue: I've been playing with the NotificationManager. If I comment out all of the code in UpdateNotifications(), the crash does not happen at all. With the current code, the crash happens an average of once every 5-10 songs. If I go back and uncomment everything except the following line:

`nm.Notify(MediaServiceBase.NotificationId, _builder.Build());`

I still get the crash occasionally, but MUCH less frequently (maybe once every 100 songs). If I then go back and comment out all the code in the method, I can't get it to happen at all.

As a workaround, I have created my own custom implementation of IMediaNotificationManager, with UpdateNotificaitons() commented out, which seems to work fine, except that the Pause button doesn't change to a Play button when paused. I worked around that by adding separate Pause and Play buttons.

This should get fixed at some point so that UpdateNotifications can work without crashing.

**Comment by LyndiLeighWK** [comment]
I have a similar issue.  If I play then pause an audio file in my app, then switch to another app (like podcasts) and play an audio file from that app, my app crashes with this exception:

` --- End of managed Android.Util.AndroidRuntimeException stack trace ---
android.app.RemoteServiceException: Bad notification posted from package org.rbc.odb: Couldn't update remote views for: StatusBarNotification(pkg=org.rbc.odb user=UserHandle{0} id=1 tag=null key=0|org.rbc.odb|1|null|10225: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x0 color=0x00000000 category=transport actions=1 vis=PUBLIC semFlags=0x0 semPriority=0))
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1813)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6776)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
`

**Comment by hig-dev** [comment]
I'm also experiencing this problem:

```
android.app.RemoteServiceException: Bad notification posted from package REAL_Shuffle_Player_Forms.Android: Couldn't update remote views for: StatusBarNotification(pkg=REAL_Shuffle_Player_Forms.Android user=UserHandle{0} id=1 tag=null key=0|REAL_Shuffle_Player_Forms.Android|1|null|10210: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x0 color=0x00000000 category=transport actions=1 vis=PUBLIC))
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1662)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:153)
	at android.app.ActivityThread.main(ActivityThread.java:6171)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
Xamarin caused by: Android.Util.AndroidRuntimeException: Bad notification posted from package REAL_Shuffle_Player_Forms.Android: Couldn't update remote views for: StatusBarNotification(pkg=REAL_Shuffle_Player_Forms.Android user=UserHandle{0} id=1 tag=null key=0|REAL_Shuffle_Player_Forms.Android|1|null|10210: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x0 color=0x00000000 category=transport actions=1 vis=PUBLIC))
  --- End of managed Android.Util.AndroidRuntimeException stack trace ---
android.app.RemoteServiceException: Bad notification posted from package REAL_Shuffle_Player_Forms.Android: Couldn't update remote views for: StatusBarNotification(pkg=REAL_Shuffle_Player_Forms.Android user=UserHandle{0} id=1 tag=null key=0|REAL_Shuffle_Player_Forms.Android|1|null|10210: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x0 color=0x00000000 category=transport actions=1 vis=PUBLIC))
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1662)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:153)
	at android.app.ActivityThread.main(ActivityThread.java:6171)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
```

**Comment by KalpeshVedak** [comment]
We are seeing this issue too

**Comment by KalpeshVedak** [comment]
Got a fix for my application , calling the notification update of large icon too fast leads to the problem
if you have a task that is updating notification icon and it is getting called too fast then it results in this issue
ideally large icon should only be set when the song changes and not on every action like play pause

**Comment by hig-dev** [comment]
I'm working on a fix in my fork https://github.com/hig-dev/XamarinMediaManager
Don't know yet if it's working fully. I will make further tests but it looks promising.
Once I tested everything, I will make a pull request.
