### ISSUE TITLE
Questions about XamarinMediaManager

### ISSUE THREAD

**Issue by charlesroddie** [martijn00/XamarinMediaManager#185]
Media playback has been a problem in Xamarin.Forms so I wish you good luck trying to fill the void.

Questions:
- Does XamarinMediaManager support both full screen playback and non-full-screen playback within a Xamarin.Forms View?
- Does it have a time property that can be read and set? I believe no other video player has got this working yet.
- No chance of Windows 8.1 support? Happens to be a requirement for us at the moment :( .

Thanks!

**Comment by martijn00** [comment]
* There is no support for switching to full screen, but i guess you could do that by changing the size of the view.
* Yes this is supported.
* No this is not on our roadmap.
