### ISSUE TITLE
Xamarin.Forms: VideoView does not appear

### ISSUE THREAD

**Issue by adrianhall** [martijn00/XamarinMediaManager#186]
Environment is Visual Studio 2017 with Xamarin.Forms 2.3.4.231 (which is the latest release), with a shared project (not a PCL) and iOS, Android and UWP projects.  Plug.MediaManager & Plugin.MediaManager.Forms 0.4.0 is installed. in each project.

I have the following XAML:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
    x:Class="VideoApp.Pages.VideoDetail"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:forms="clr-namespace:Plugin.MediaManager.Forms;assembly=Plugin.MediaManager.Forms">
    <StackLayout>
        <forms:VideoView
            x:Name="VideoPlayer"
            AspectMode="AspectFill"
            HorizontalOptions="FillAndExpand"
            Source="http://zumobook.streaming.mediaservices.windows.net/007f9e4a-92c2-4d3b-aa12-a428126e0eef/Sample 1.ism/manifest" />
        <StackLayout Orientation="Horizontal">
            <Label Text="Duration: " />
            <Label x:Name="Duration" />
        </StackLayout>
        <ProgressBar x:Name="ProgressBar" HorizontalOptions="FillAndExpand" />
        <StackLayout Orientation="Horizontal">
<!-- Some buttons removed for sake of brevity -->
        </StackLayout>
    </StackLayout>
</ContentPage>
```

In addition, I've added the `var window=typeof(VideoView);` in the App.cs in the shared project.

Compiling for UWP: 

If I remove the <forms.VideoView> then the page loads normally, albiet without the video.  If I add the VideoView back in, then the title remains as on the previous page and there is a blank page otherwise.   No video is played.

It doesn't matter if the source is empty, valid, bound to a property, etc. Looking at the output, there is no strange log messages.  If I set a breakpoint at the end of the VideoDetail constructor (after the `InitializeComponent()`), then the VideoPlayer variable is a `Plugin.MediaManager.Forms.VideoView` type.

Any idea on how to debug further?

**Comment by corgalore** [comment]
Did you include VideoViewRenderer.Init(); in the OnCreate() method in each native project?

You also need a using reference for Plugin.MediaManager.Forms.Android/iOS.

**Comment by adrianhall** [comment]
Yes - I included both of those.  I moved on to a different library.

**Comment by corgalore** [comment]
Adrian,

If you don't mind,  what library did you use?

**Comment by alexanderdp** [comment]
Regarding the error:
The type or namespace name 'Forms' does not exist in the namespace Plugin.MediaManager are you missing an assembly reference?

You must also install the Nuget Package:
Plugin.MediaManager.Forms

**Comment by antonioreyna** [comment]
I am having the same problem on my xaml

**Comment by vipinraturi** [comment]
I am having the same issue. Has anyone find the solution yet or not?

**Comment by ergodaveh** [comment]
Just to Note a Successful build
I had to install the Nuget Package and add a using reference of same
Plugin.MediaManager.Forms
