### ISSUE TITLE
Unable to install nuget for XF Android project

### ISSUE THREAD

**Issue by muqeet-khan** [martijn00/XamarinMediaManager#187]
I am able to install the MediaManager nugets for iOS and my portable project but the install fails for Android. XF is at the latest stable version 2.3.4.231 using VS 2017.  I get this error.

![image](https://cloud.githubusercontent.com/assets/6345044/25148996/8549c1c0-2442-11e7-9c0d-4193f4b1764b.png)

I did not update any android libraries. I am not sure why this would pop up. Any help will be appreciated. Thanks!

**Comment by hig-dev** [comment]
This is because Xamarin Forms currently only supports the Android Support libraries in version 23.3.0 and the new MediaManager plugin wants 25.1.1 or higher. I think you have to use the MediaManager plugin in version 0.3

**Comment by martijn00** [comment]
See https://github.com/martijn00/XamarinMediaManager/issues/163#issuecomment-289018449

**Comment by muqeet-khan** [comment]
I am new to XF, please bare with me, but, I am using 2.3.4.224 and the requirement is as follows:

![image](https://cloud.githubusercontent.com/assets/6345044/25240502/9c2fbf08-25b8-11e7-98a3-50938cbe50cd.png)


for 2.3.3.192 as follows:
![image](https://cloud.githubusercontent.com/assets/6345044/25240470/86cb2bde-25b8-11e7-8a8d-0bc278107c96.png)


The 2 dependencies look exactly the same to me. So, I am not sure what I am missing.

**Comment by martijn00** [comment]
So the difference is with MonoAndroid 1.0 it is `= 23.3.0` and with 7.0 it is `>= 23.3.0` which means you need to set your Android project to target v7.0 or higher, after that you can update to v25.1.1 or higher support packages.

**Comment by trandinhnam** [comment]
So do you mean that we need to downgrade xamarin.form to install this plugin?
