### ISSUE TITLE
Audio is shown on background as a song is playing

### ISSUE THREAD

**Issue by riandesign** [martijn00/XamarinMediaManager#189]
I've been developing an chat which has voice recorder.
So, users can send audio files and play them.

When I play any audio, it works well, however everytime it is shown on background player and it is there forever. I don't want it. I just want to play the audio inside the app.

Just to illustrate the issue:

![youtube-in-background-ios-7-step-4](https://cloud.githubusercontent.com/assets/5668552/25663469/29df6bac-2fee-11e7-864d-30f962a0907d.jpg)

**Comment by martijn00** [comment]
You can override the notificationManager to disable this.
