### ISSUE TITLE
Custom IMediaNotificationManager won't "stick" (Android)

### ISSUE THREAD

**Issue by jmartine2** [martijn00/XamarinMediaManager#192]
I am writing my own custom IMediaNotificationManager, but I can't figure out how to inject it. I try setting MediaManager.Current.MediaNotificationManager to a new instance of my own implementation. If I set a breakpoint immediately after setting it, it shows that the reference is pointing to my object. However, soon afterwards (like when I play the next song), it somehow gets reinitialized to the default implementation.

What do I need to do to successfully (permanently) inject my own MediaNotificationManager?

**Comment by martijn00** [comment]
I'll look into putting the new version online on Nuget. I would be happy to review PR's with your fixes!
