### ISSUE TITLE
Xamarin Forms Android unstable

### ISSUE THREAD

**Issue by K232** [martijn00/XamarinMediaManager#193]
Hi all,
it seems that Xamarin Forms Android Version has some problems?

I've also tested with Hanselman Minutes App. First video plays fine, then I go back and try to start the second video and it only shows "Buffering" .... Problem is repeatable on emulator and on Android 6 Hardware.

Any ideas?

**Comment by martijn00** [comment]
Thanks for filling an issue! Can you open a pull request with a fix for this? I would be more then happy to review it!

**Comment by K232** [comment]
I don't have any fix....?

**Comment by RamonEastsoftware** [comment]
Yes, I verify this problem. any ideas Martin?

pushing page with different MediaFile is not working on android. only the first instance is playing.

**Comment by RamonEastsoftware** [comment]
The error is 
07-27 23:15:55.644: E/MediaMetadataRetrieverJNI(28066): getEmbeddedPicture: Call to getEmbeddedPicture failed.

Can you help me fix this? thank you.
