### ISSUE TITLE
ExoPlayer - TimeSpan OverflowException

### ISSUE THREAD

**Issue by jmartine2** [martijn00/XamarinMediaManager#196]
I received the following unhandled exception in ExoPlayerAudioService:

android.runtime.JavaProxyThrowable: System.OverflowException: TimeSpan overflowed because the duration is too long.

Stack Trace:
System.TimeSpan.Interval(double value, int scale)<ba45d3baa00f457cb8afa0a7e4e904e1>:0
System.TimeSpan.FromMilliseconds(double value)<ba45d3baa00f457cb8afa0a7e4e904e1>:0
Plugin.MediaManager.ExoPlayer.ExoPlayerAudioService.OnBuffering()<0392627dd98a40a6ab8fe621ef7a87d4>:0
Java.Lang.Thread.RunnableImplementor.Run()<1874d040d9994479aca527460bc3ab5f>:0
Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this)<1874d040d9994479aca527460bc3ab5f>:0
at (wrapper dynamic-method) System.Object:ffb5ed07-c94a-4741-8894-67324027a193 (intptr,intptr)
mono.java.lang.RunnableImplementor.n_run(Native Method)
mono.java.lang.RunnableImplementor.run()RunnableImplementor.java:30
android.os.Handler.handleCallback()Handler.java:733
android.os.Handler.dispatchMessage()Handler.java:95
android.os.Looper.loop()Looper.java:157
android.app.ActivityThread.main()ActivityThread.java:5356
java.lang.reflect.Method.invokeNative(Native Method)
java.lang.reflect.Method.invoke()Method.java:515
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run()ZygoteInit.java:1265
com.android.internal.os.ZygoteInit.main()ZygoteInit.java:1081
dalvik.system.NativeStart.main(Native Method)

**Comment by martijn00** [comment]
Maybe ExoPlayer needs to be updated to the latest version. I have to look into providing updated bindings for ExoPlayer.
