### ISSUE TITLE
Loop off by default

### ISSUE THREAD

**Issue by tgraupmann** [martijn00/XamarinMediaManager#198]
```
private async void Button_Clicked(object sender, EventArgs e)
        {
            await CrossMediaManager.Current.Play("ms-appx:///Assets/Test.wav");
        }
```

Playing a local wave asset on UWP (Raspberry PI Windows IoT Core) loops the wav file.

It would be great if the Play had an optional loop parameter with loop off by default.

As a workaround I use the media finished callback.
```
CrossMediaManager.Current.MediaFinished += Current_MediaFinished;
```

Click a button to start playing the wav file.
```
private async void Button_Clicked(object sender, EventArgs e)
        {
            await CrossMediaManager.Current.Play("ms-appx:///Assets/Test.wav");
        }
```

And use the MediaFinished event to stop playing the audio.
```
        private async void Current_MediaFinished(object sender, Plugin.MediaManager.Abstractions.EventArguments.MediaFinishedEventArgs e)
        {
            await CrossMediaManager.Current.Stop();
        }
```

Optional loop will be better when I have multiple sounds going.

**Comment by martijn00** [comment]
Thanks for filling an issue! Can you open a pull request with a fix for this? I would be more then happy to review it!
