### ISSUE TITLE
VideoView forms with autoplay?

### ISSUE THREAD

**Issue by fmeneuhe** [martijn00/XamarinMediaManager#199]
Hi,
I would like to know if the VideoView for Xamarin Forms has any autoplay function?
Thanks

**Comment by K232** [comment]
Isn't it autoplay by default? For me, the video automatically starts as soon as it's buffered....

**Comment by rraallvv** [comment]
@K232 what platform are you running your app on? For mine, Android doesn't autoplay while iOS does.

@fmeneuhe I'm interested too, did you solve the issue?

**Comment by K232** [comment]
@rraallvv , I'm sure it was both iOS and Android.
