### ISSUE TITLE
Nuget

### ISSUE THREAD

**Issue by jraesly** [martijn00/XamarinMediaManager#2]
I can't find this on nuget.com?

Can you provide a link?

**Comment by martijn00** [comment]
Hi, i didn't get it into nuget yet. I'll plan to do this in the future.

**Comment by jraesly** [comment]
Time table?

**Comment by martijn00** [comment]
I could do a beta release on nuget this week, the official version will have to wait a bit longer.

**Comment by jraesly** [comment]
That would be great if you could. 
Thanks!

**Comment by jmartine2** [comment]
Did this ever get put on nuget? The Github page says that it's there, but I can't find it. I tried searching for "XamarinMediaManager", and nothing came up.

**Comment by martijn00** [comment]
It's up now: https://www.nuget.org/packages/Plugin.MediaManager/
