### ISSUE TITLE
Audio Playback Speed

### ISSUE THREAD

**Issue by lazarnikolov94** [martijn00/XamarinMediaManager#201]
Hi! Is it possible to alter the playback speed to be faster / slower? I see that there is a public float Rate variable in AudioPlayerImplementations.cs, but I can't seem to access it.

**Comment by martijn00** [comment]
Rate is not implemented yet. Can you open a pull request with a fix for this? I would be more then happy to review it!

**Comment by AndreiMisiukevich** [comment]
@martijn00 
Some updates?) It would be useful feature..

**Comment by ThaineNorris** [comment]
Playback speed would be greatly appreciated!
