### ISSUE TITLE
Notifications are not stopping on calling MediaNotificationManager.StopNotifications()

### ISSUE THREAD

**Issue by lionheadQWERTY** [martijn00/XamarinMediaManager#204]
Hi guys, 

i cant find a way to edit the notifications or stop them, i am using the package from the NuGet package manager.

Im playing a internet radio stream

**Comment by krigertvb** [comment]
I also have this problem. Is there a way to turn off notifications on Android?

**Comment by leokidbox** [comment]
Its driving me nuts -_-

Overriding the media notifications should work.

**Comment by martijn00** [comment]
There is a fix for this commited, but not online on Nuget yet.

**Comment by leokidbox** [comment]
@martijn00  do you know when its going to be on nuget?

**Comment by richardpike** [comment]
This clears the notification for me:
```
if (CrossMediaManager.Current.MediaNotificationManager != null)
{
	CrossMediaManager.Current.MediaNotificationManager.StopNotifications();
}
```
But the icon flashes for about a second. Is there a way to stop it from appearing at all?
