### ISSUE TITLE
Samples don't compile

### ISSUE THREAD

**Issue by ChristophPie** [martijn00/XamarinMediaManager#208]
I have downloaded the Repo as ZIP, added thr Nuget package [MediaManager](https://www.nuget.org/packages/Plugin.MediaManager/) from [here](https://github.com/martijn00/XamarinMediaManager/archive/develop.zip). 
Then I compiled the whole solution, but I get these errors, attached.
[errors.txt](https://github.com/martijn00/XamarinMediaManager/files/1117739/errors.txt)

I think e.g.
```
        public IMediaNotificationManager NotificationManager
        {
            get => _overrideNotificationManager ?? _notificationManager;
            set
            {
                _overrideNotificationManager = value;
                _notificationManager = value;
            }
        }
```
in "MediaSessionManager.cs" is  (one) of the problems.

**Comment by martijn00** [comment]
Thanks for filling an issue! Can you open a pull request with a fix for this? I would be more then happy to review it!
