### ISSUE TITLE
UWP playback resume issue

### ISSUE THREAD

**Issue by BtrJay** [martijn00/XamarinMediaManager#209]
Hi @martijn00 ,

It looks like the player doesn't resume where you started ppreviously on UWP.

The steps to reproduce for this issue are 

1. Play any mp3 file

2. Pause in the middle of the stream

3. play mp3 again and it restarts from the beginning

Have you had any updates on this?

Kind regards,

Jay

**Comment by martijn00** [comment]
Thanks for filling an issue! Can you open a pull request with a fix for this? I would be more then happy to review it!

**Comment by BtrJay** [comment]
Hi @martijn00 ,

We will create a pull request for that.

Regards,

Jay

**Comment by BtrJay** [comment]
Hi @martijn00 ,

It looks like I can't create a pull request from my local branch. (keep getting 403 error)

Could you create one for me that extends develop branch?

Kind Regards,

Jay

**Comment by martijn00** [comment]
@BtrJay You need to create a Fork of my repo. After that create a branch and commit your code on it. Then go to my repo on Github and select Create new pull request.
