### ISSUE TITLE
Cannot play any remote files using the ExoPlayer

### ISSUE THREAD

**Issue by fela98** [martijn00/XamarinMediaManager#212]
On Android, it is currently impossible to play any http or https URL using the ExoPlayer. The reason being the following line:

https://github.com/martijn00/XamarinMediaManager/commit/dcad94ae6981641b2ac443dc1f0b55c0fd492df9#diff-4502773ba4cb767b19ec69fc5a3ac7a0R282

It's the [Uri.EscapeDataString(string)](https://msdn.microsoft.com/en-us/library/system.uri.escapedatastring(v=vs.110).aspx) method that causes this problem. It's only compatible with local uris but not with a http/https url.

@jmartine2 it looks like the commit comes from you. Did you test this with any other files other than local ones after doing these changes?

@martijn00 This bug is now in 0.4.0 which is supposed to be a "stable" build, do you not have any testing in place that should have catched this bug earlier?

IMO this bug, which in my opinion is a critical bug that breaks a big part of the component, should have been found way earlier. We even have multiple samples in place that use remote urls that clearly demonstrate that the package is broken.

I will create a pull request that reverts the changes.

**Comment by martijn00** [comment]
Please make a proper fix in the PR before i can merge this.
