### ISSUE TITLE
Android bug

### ISSUE THREAD

**Issue by shabirjan** [martijn00/XamarinMediaManager#214]
I am facing a bug/crash/Exception when i use MediaManager video playing on Android using Xamarin forms.

Cannot access a disposed object. Object name: 'Plugin.MediaManager.VideoSurface

This happens when i go back from VideoPlaying page to another page like when i click on back button. And this occurs when i call `CrossMediaManager.Current.Stop()` and `CrossMediaManager.Current.StatusChanged -= methodName` . I am using MVVM and Prism and i am calling these from `OnNavigatedFrom` method of `INavigatedAware` from Prsim

**Comment by shabirjan** [comment]
@SimonSimCity @modplug @candidodmv @aiviet @fela98 any solution for this issue?

**Comment by aiviet** [comment]
@shabirjan Based on your descriptions, I think it is the same ObjectDisposedException as in #238. The fix for this has been merged. You need to wait for the next nuget release. Or you can try the walk-around that I suggested in #238.

**Comment by candidodmv** [comment]
as this problem was happened a lot of time ago, I don't remember exact details that I did, but the only thing that I'm sure is that was need to use workaround with another way to do what was needed

**Comment by SimonSimCity** [comment]
Sorry, but I haven't used this project in quite a while now - and never used Xamarin Forms...
