### ISSUE TITLE
Specific Eventargs for the Eventhandler

### ISSUE THREAD

**Issue by escamoteur** [martijn00/XamarinMediaManager#22]
We have a lot of great events in the interface, but unfortunately they only provide the information that something has happend, but no data with it. So that you always have to access properties to get the actual interesting data. So it could be better like this:

    public delegate void StatusChangedEventHandler(object sender, EventArgs e);

->      public delegate void StatusChangedEventHandler(object sender, PlayerStatus status);

    public delegate void CoverReloadedEventHandler(object sender, EventArgs e)
--> not sure if it makes sense here to pass the new image;

    public delegate void PlayingEventHandler(object sender, EventArgs e);
--> Would make sense to have a PlayinState class which contains: Position, Duration and Buffer

    public delegate void BufferingEventHandler(object sender, EventArgs e);

-->    public delegate void BufferingEventHandler(object sender, int); 

    public delegate void TrackFinishedEventHandler(object sender, EventArgs e);
--> Possibly passing the Track in the Queue

**Comment by martijn00** [comment]
Great idea! I will look into this when i have some time. Feel free to make a pull request if you want.

**Comment by escamoteur** [comment]
No time at the moment unfortunately

**Comment by modplug** [comment]
@escamoteur: This is included in my latest PR
