### ISSUE TITLE
How to build the lastest version?.

### ISSUE THREAD

**Issue by lionheadQWERTY** [martijn00/XamarinMediaManager#220]
Hello, i am having trouble building the lastest version, which has a fix on the media notification implementation.

When i clone the repo and try to build it with power shell i get this message:

`File C:\WORK\XamarinMediaManager\build.ps1 cannot be loaded because running scripts is disabled on this system. For 
more information, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : SecurityError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnauthorizedAccess`

**Comment by martijn00** [comment]
I've published new nuget packages. You should not build with the script but with Visual Studio.
