### ISSUE TITLE
Video does not show in Android phone or emulator

### ISSUE THREAD

**Issue by einc** [martijn00/XamarinMediaManager#221]
I am using Xamarin Forms for Visual Studio 2017 and am using an Android 4.0.3 API 15 to test and the KitKat 4.4 API 19 Emulator.

 I am following the demo (https://github.com/martijn00/XamarinMediaManager/blob/develop/Samples/Forms/MediaForms/MediaFormsPage.xaml). 

My code compiles and there are no errors, but the video does not show. I've tried changing the background of the video, but the background of where the video should be doesn't change either. I've tried placing labels in the video's grid row and so I don't think it is a grid problem. Furthermore, PlaybackController is not null. 

I turned on Write External Storage, Read External Storage, and Internet (it works), AccessWifiState, Internet, MediaContentControl and WakeLock permissions in Android Manifest.

void PlayClicked(object sender, System.EventArgs e)
        {
            PlayButton.Text = "Pressed";
                          PlaybackController.Play();
        }

I think the problem may be with PlaybackController.Play()?

what I currently see on my phone:
![emulator](https://user-images.githubusercontent.com/14082828/28482644-2673a7ee-6e1e-11e7-8d34-220a1eb58c61.jpg)

**Comment by ThaineNorris** [comment]
Same here. Anyone?

**Comment by michael-watson** [comment]
@einc @ThaineNorris, have you guys checked the Application Output to see what it is saying? I'm seeing some issues with "No Content Provider" in the output. I'm trying to figure out what is going on.

**Comment by StefanKert** [comment]
@michael-watson any news on this? Facing the same issue and curious if you came up with a solution.
