### ISSUE TITLE
Android Notifications Reappears After Being Dismissed

### ISSUE THREAD

**Issue by LyndiLeighWK** [martijn00/XamarinMediaManager#224]
Steps to replicate issue:
1. Play then pause an audio file in my app
2. Dismiss audio player from notifications
3. Switch to another app (BeyondPod)
4. Play audio from podcast app
5. Audio player from my app reappears in notifications after being dismissed already

**Comment by Inrego** [comment]
I have this same problem. You don't need to switch to another app. Simply just dismiss the notification, and it will reappear after a short while.

**Comment by Inrego** [comment]
It seems like this has been fixed in newer versions of the package. I've posted instructions on how to update to newest version in this issue: https://github.com/martijn00/XamarinMediaManager/issues/234

**Comment by LyndiLeighWK** [comment]
@Inrego Thanks!  I will give that a try.

**Comment by Inrego** [comment]
Update! No, it doesn't seem to be fixed in newer versions.
