### ISSUE TITLE
MediaForms.Android only audio

### ISSUE THREAD

**Issue by einc** [martijn00/XamarinMediaManager#225]
I cloned the project and am trying to test MediaForms.Android. I have already downloaded the needed packages and enabled the needed properties in Android AppManifest.
When I run the code, I can hear the audio but only see a black screen where the video is supposed to be. I tried HeightRequest = "200" and WidthRequest = "200" but I still only see a black screen.
When I set the background color of the video to pink, nothing changes

**Comment by vincilbishop** [comment]
Getting this issue on iOS as well :(

**Comment by antonioreyna** [comment]
i have this issue too, any idea? in my case just android
