### ISSUE TITLE
UWP: SeekTo doesn't seem to start from where it's supposed to be

### ISSUE THREAD

**Issue by BtrJay** [martijn00/XamarinMediaManager#228]
Hi @martijn00 ,

It looks like I've found another issue when I tried to use SeekTo method in UWP.

The steps to replicate 

1. Add number to SeekTo method in PlaybackController

MediaManager.PlaybackController.SeekTo(streamingPosition);
MediaManager.PlaybackController.Play();

 2. This isn't working consistently, sometimes start from beginning

Please let me know if you want us to open pull request for that.

Regards,

Jay

**Comment by martijn00** [comment]
Hi, a PR would be perfect!

**Comment by BtrJay** [comment]
Please see #232
