### ISSUE TITLE
Design for custom playback logic

### ISSUE THREAD

**Issue by myrobotzone** [martijn00/XamarinMediaManager#229]
Hi all,

In my application I would like to inject custom logic before commencing audio playback, but as far as a can tell this is not supported yet (right?). What do you think about the following design to achieve this?

Application implements custom IPlaybackController class and then assigns it to the PlaybackController property provided by MediaManagerBase. After that any internal calls to the playback controller, such as in response to media button clicks, are transparently forwarded on to the application's custom playback controller.

I've spiked the changes and and it works with minimal impact to MediaManager code. Is this an acceptable change or does any one have an alternative?

P.S is there a better way to discuss stuff like this than creating an issue? Maybe a wiki would be better.

Cheers,
Jonas

**Comment by martijn00** [comment]
What about this: https://github.com/martijn00/XamarinMediaManager/blob/develop/MediaManager.Abstractions/IMediaManager.cs#L104

If you want to discuss some stuff directly with me, i'm available at the XamarinChat slack: https://xamarinchat.herokuapp.com/

**Comment by myrobotzone** [comment]
Is the idea that applications implement IMediaManager?

**Comment by martijn00** [comment]
No for most use cases you should not implement that yourself, but instead set a custom implementation of a platform on the MediaManager.

**Comment by myrobotzone** [comment]
The PlaybackController is a settable property, so from a framework consumer's point of view it looks like setting this is an option for injecting custom playback control logic. However with the current implementation it doesn't work as expected. Similar to issue #192.

**Comment by martijn00** [comment]
Right, there might be a bug there. If you make a PR to fix that i could take a look. Also it would be good to talk on Slack about design choices like this.

**Comment by myrobotzone** [comment]
Great - I'll create a PR with this issue number. And next time I'll use Slack.

**Comment by martijn00** [comment]
What's your username over there?

**Comment by myrobotzone** [comment]
myrobotzone (just joined)
