### ISSUE TITLE
Video rotation is not working properly on some Android devices

### ISSUE THREAD

**Issue by javierescobare** [martijn00/XamarinMediaManager#233]
When trying the Forms sample app on LG G4, the video doesn't rotate properly. I tried with another LG device but then it worked perfectly.

First
![image](https://user-images.githubusercontent.com/15280278/28897407-2cd2eb40-77a6-11e7-9425-f6a86a23bb0c.png)

Go landscape...
![image](https://user-images.githubusercontent.com/15280278/28897338-e2f5026a-77a5-11e7-89ec-60a64addceb2.png)

Then portrait again...
![image](https://user-images.githubusercontent.com/15280278/28897365-061ab96a-77a6-11e7-8cb0-5a3277be5d29.png)

**Comment by aiviet** [comment]
Use this layout

<?xml version="1.0" encoding="utf-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:MediaForms"
             xmlns:forms="clr-namespace:Plugin.MediaManager.Forms;assembly=Plugin.MediaManager.Forms"
             x:Class="MediaForms.MediaFormsPage">
	<Grid>
		<Grid.RowDefinitions>
			<RowDefinition Height="*"/>
			<RowDefinition Height="Auto"/>
		</Grid.RowDefinitions>
		
        

        <forms:VideoView x:Name="videoView"
            Grid.Row="0"
            HorizontalOptions="FillAndExpand"
            VerticalOptions="FillAndExpand"
            AspectMode="AspectFill"/>

        <Grid HorizontalOptions="FillAndExpand" Grid.Row="1" >
			<Grid.RowDefinitions>
				<RowDefinition Height="Auto"/>
                <RowDefinition Height="Auto"/>
			</Grid.RowDefinitions>
			<Grid.ColumnDefinitions>
				<ColumnDefinition/> 
				<ColumnDefinition/> 
				<ColumnDefinition/> 
			</Grid.ColumnDefinitions>
			<StackLayout Grid.Row="0" Grid.ColumnSpan="3" Orientation="Vertical">
			<StackLayout Orientation="Horizontal">
					<Label Text="Duration: "></Label>
					<Label x:Name="Duration"/>
				</StackLayout>
				<ProgressBar x:Name="ProgressBar" Grid.ColumnSpan="3" HorizontalOptions="FillAndExpand"></ProgressBar>
			</StackLayout>
			
			<Button Grid.Row="1" Grid.Column="0" TextColor="White" BackgroundColor="Gray" HeightRequest="50" VerticalOptions="Center" Text="Play" WidthRequest="100" Clicked="PlayClicked"></Button>
			<Button Grid.Row="1" Grid.Column="1" TextColor="White" Text="Pause" BackgroundColor="Gray" HeightRequest="50" VerticalOptions="Center" WidthRequest="100" Clicked="PauseClicked"></Button>
			<Button Grid.Row="1" Grid.Column="2" TextColor="White" Text="Stop" BackgroundColor="Gray" HeightRequest="50" VerticalOptions="Center" WidthRequest="100" Clicked="StopClicked"></Button>
		</Grid>
	
	</Grid>
    
</ContentPage>
```

**Comment by javieresc97** [comment]
Same problem :/

**Comment by cartmax** [comment]
I have the same problem @javieresc97, do you find any solutions ?
