### ISSUE TITLE
UWP Local Playback?

### ISSUE THREAD

**Issue by ghost** [martijn00/XamarinMediaManager#242]
Hello everyone,

Has anyone managed to figure out local playback on UWP? From my experience this seems to be a platform-specific implementation, and neither Android nor iOS solutions assist in UWP implementation.

**Comment by Inrego** [comment]
Works fine for me in UWP.

**Comment by upCodeS** [comment]
@Inrego Would you be able to provide a sample code of what you are doing? For Android, I'm performing the following:

return Android.Net.Uri.Parse("android.resource://[project].Android/" + Resource.Raw.[resource_name]).ToString();

And for iOS, I'm performing the following:

"return NSBundle.MainBundle.PathForResource(file_ID, "mp3");", where file_ID is a string name of a Media File

These calls return the proper url to a media file, which can then be used as the arguments in a play() call. But neither of these implementations will apply for UWP. Any thoughts?

**Comment by Inrego** [comment]
Ah, I have not tried with embedded resources. But with my limited experience with Xamarin forms, you usually just provide the filename when you need to access resources (works for images, anyway).
So have you tried something along these lines (for all 3 platforms)?

    await CrossMediaManager.Current.Play("filename.mp3");

I guess it's a bit easier for me, since I download the files on demand, and therefore have a full filepath for each file.

**Comment by upCodeS** [comment]
@Inrego Alas, that does not work. It seems like you have to retrieve the resource file path, which I don't know how to execute on UWP.

**Comment by Inrego** [comment]
Check out this source file from another project (that loads pictures async). It may be of some help.
https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Windows/DataResolvers/ResourceDataResolver.cs

**Comment by upCodeS** [comment]
I appreciate you pointing me in the right direction, however couldn't get that to control UWP local playback :/

**Comment by patrickabadi** [comment]
This worked for me:

```
var vidUri = new Uri("ms-appx:///" + "Assets/wireframe.mp4");
videoPlayer.Source = vidUri.ToString();
videoPlayer.BackgroundColor = Color.Transparent;
videoPlayer.AspectMode = Plugin.MediaManager.Abstractions.Enums.VideoAspectMode.AspectFit;
CrossMediaManager.Current.VolumeManager.Mute = true;
CrossMediaManager.Current.PlaybackController.Play();
```

**Comment by tekkies** [comment]
With the change above, I am able to play a file in the My Music folder using a regular dos path (e.g. "C:\Users\me\Music\achy-breaky-heart.mp3").

**Comment by martijn00** [comment]
Try again in 0.7.5 and let me know if it works

**Comment by tekkies-docker** [comment]
I tested:
* v0.7.5
* both UWP and Android.
* Playing local
* Playing 3 files in a playlist

All seemed to work fine.  Thanks.

**Comment by tekkies** [comment]
I tested:
* v0.7.5
* both UWP and Android.
* Playing local
* Playing 3 files in a playlist

All seemed to work fine.  Thanks.
