### ISSUE TITLE
MediaManager 0.44 dependency issue

### ISSUE THREAD

**Issue by mike-rowley** [martijn00/XamarinMediaManager#246]
I am getting a dependency error on the MediaManager 0.44 Nuget.

Unable to resolve dependencies. 'Plugin.MediaManager 0.4.4' is not compatible with 'Plugin.MediaManager.ExoPlayer 0.4.3 constraint: Plugin.MediaManager (= 0.4.3)', 'Plugin.MediaManager.Forms 0.4.3 constraint: Plugin.MediaManager (= 0.4.3)'.

It appears the ExoPlayer Nuget requires a matching version number, is there a Plugin.MediaManger.ExoPlayer Nuget in the works?

Thanks for the amazing work on this package!
M

**Comment by martijn00** [comment]
Unfortunately the ExoPlayer part depends on ExoPlayer 1.x which is quite old. It needs an update to 2.5.1. I would appreciate any help and PR's that fix that.

**Comment by mike-rowley** [comment]
Ok, thanks, I'll definitely see what I can do
