### ISSUE TITLE
[Android] Wrong conversion from Duration and Position

### ISSUE THREAD

**Issue by aiviet** [martijn00/XamarinMediaManager#247]
In Android's VideoPlayerImplementation.cs:
```
public TimeSpan Duration => IsReadyRendering == false ? TimeSpan.Zero : TimeSpan.FromSeconds(VideoViewCanvas.Duration);       
public TimeSpan Position => IsReadyRendering == false ? TimeSpan.Zero : TimeSpan.FromSeconds(VideoViewCanvas.CurrentPosition);
```

According to documentations, unit is in millisecond, not second
https://developer.android.com/reference/android/media/MediaPlayer.html#getDuration()
https://developer.android.com/reference/android/media/MediaPlayer.html#getCurrentPosition()

**Comment by Ruddy2007** [comment]
This needs to be fixed. A huge issue with a simple fix.
