### ISSUE TITLE
Unable to resolve interface types after updating

### ISSUE THREAD

**Issue by lcbpdev** [martijn00/XamarinMediaManager#248]
I'm developing a Xamarin Forms application for Android and iOS and after updating from Plugin.MediaManager 0.3.0 with ExoPlayer 2.0.4.1 to Plugin.MediaManager 0.4.3 with ExoPlayer 2.5.1.1 I get the following errors:

** Error Description:**
Unable to resolve interface type 'Com.Google.Android.Exoplayer2.Upstream.IDataSourceFactory'. Are you missing an assembly reference?
**Project:**
App.Android
**File:**
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets
**Line:**
<GenerateJavaStubs (1668)

** Error Description:**
Unable to resolve interface type 'Com.Google.Android.Exoplayer2.IExoPlayerEventListener'. Are you missing an assembly reference?	
**Project:**
App.Android
**File:**
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets

Line is the same as above

**Comment by martijn00** [comment]
This is the same as https://github.com/martijn00/XamarinMediaManager/issues/246. Currently there is no support for ExoPlayer 2.x. I would accept contributions to get this updated.
