### ISSUE TITLE
Local video source in Xamarin Forms

### ISSUE THREAD

**Issue by uzairali001** [martijn00/XamarinMediaManager#251]
How can I set the url of local Video?
currently I am able to play videos online by using `videoPlayer.Source = "https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4"`.
I have placed `test.mp4` in Android>Assets and Build action is set to `AndroidAssets`

**Comment by eliasribeiro** [comment]
I have same question, video e audio locally. Audio in iOS put in Resource folder and work, but Android not work in Resource/raw or Assets folder. Someone have know to do play in Android locally?

**Comment by aiviet** [comment]
Android project has "Assets" folder which is equivalent to iOs' Resource folder. However you cannot use file bundled in "Android Assets" directly. You have to copy files from Asset to personal folder and assign video source to the full path of the copied files.

**Comment by antonioreyna** [comment]
hello, I added a video to my pcl i was able to get the path for ios with nsbundle, but on andoid i am not able to get that path, what can i do? thanks
