### ISSUE TITLE
BUG: Cannot repeat songs in queue

### ISSUE THREAD

**Issue by ghost** [martijn00/XamarinMediaManager#252]
Despite marking Queue.Repeat = RepeatOne or even adding the same song twice in a row to the queue, I cannot get the player to play any song a second time in a row. I believe this issue was confirmed in an earlier issue (see #177), just wanted to bring it to attention again with the hopes of finding a solution in the future :)

**Comment by keertanadapari** [comment]
Hi,i am also having same problem.i cant able to play songs sequentially which is in queue.if you got solution,please share me.

**Comment by Falco20019** [comment]
The fix was merged into develop branch and this issue could be closed
