### ISSUE TITLE
iOS Control center artwork not shown after set in OnMediaFileChangedEventHandler.

### ISSUE THREAD

**Issue by jwkent** [martijn00/XamarinMediaManager#254]
I am setting the Metadata in the mediaFile using different values.  The title, artist and album are all working fine except for setting AlbumArt, or Art, or DisplayIcon image doesn't display in the iOS control center.  I know I have loaded the image into _albumArtImage variable correctly because I can display the image in my XAML code.

I am using Xamarin.Forms.  What am I doing wrong here?  

```
Plugin.MediaManager.Abstractions.IMediaManager _player;
Image _albumArtImage;

/// <summary>
/// Initializes a new instance of the <see cref="T:AudioPlayer"/> class.
/// </summary>
/// <param name="message">Message.</param>
/// <param name="series">Series.</param>
public AudioPlayer(Message message, Series series)
{
	_series = series;
	_message = message;

	InitializeComponent();

      _albumArtImage = new Image { Source = "artist512.png" };

      //myPic.Source = _albumArtImage.Source;
	CrossMediaManager.Current.MediaFileChanged += OnMediaFileChangedEventHandler;
	InitializePlayer(message, series);
	BindingContext = this;
}

/// <summary>
/// Handles the media file changed event.
/// </summary>
/// <param name="sender">Sender.</param>
/// <param name="e">MediaFileChangedEventArgs</param>
private void OnMediaFileChangedEventHandler(object sender, MediaFileChangedEventArgs e)
{
	e.File.Metadata.Artist = _teacher;
	e.File.Metadata.Album = _series.Name;
	e.File.Metadata.Title = _message.Name;

    e.File.Metadata.AlbumArt = _albumArtImage;
    e.File.Metadata.Art = _albumArtImage;
    e.File.Metadata.DisplayIcon = _albumArtImage;
}
```

**Comment by ThaineNorris** [comment]
Hello John, did you ever find a solution to this?

**Comment by jwkent** [comment]
No I didn't find any solution. 

Sincerely,
John

**Comment by ThaineNorris** [comment]
That's a bummer. I am working on an app that plays Christian ministry podcasts. I tried modifying one of the MP3 files to see if the album art would get extracted from the file, which seems to be suggested by perusing the source code. But I couldn't get that to work either. It wouldn't be a problem except that the iOS remote player on the lock screen always displays album art.

I'll let you know if I find a solution.

**Comment by jwkent** [comment]
Sounds like we are working on similar apps.  I am creating an update to my app which can found on the App Store: 
https://itunes.apple.com/us/app/narrowpath/id991591148?mt=8

**Comment by mike-rowley** [comment]
I'm searching for an answer to this issue as well.

**Comment by Doxoh** [comment]
Have anyone find a solution?

**Comment by jwkent** [comment]
Negative.  iOS 11 has made missing art work less annoying.

**Comment by Doxoh** [comment]
Oh okay thanks @jwkent

**Comment by mike-rowley** [comment]
https://github.com/martijn00/XamarinMediaManager/pull/322 allows AlbumArtUri to populate the IOS lock screen.

**Comment by Doxoh** [comment]
@mike-rowley when the version is on https://www.nuget.org/packages/Plugin.MediaManager/ ?

**Comment by mike-rowley** [comment]
That will be up to @martijn00

**Comment by Doxoh** [comment]
Oh okay thanks @mike-rowley , the I hoped @martijn00 do it in the next time 😅

**Comment by Doxoh** [comment]
@mike-rowley 

You do this "if (!metadata.AlbumArtUri.Equals(string.Empty))". I think "if (!String.IsNullOrEmpty(metadata.AlbumArtUri))" is better

**Comment by Doxoh** [comment]
@mike-rowley Did you know when the pull request is applyed?
