### ISSUE TITLE
Aspect ratio for video not working in android

### ISSUE THREAD

**Issue by PaulVrugt** [martijn00/XamarinMediaManager#255]
Hello,

I'm trying to see if i can use this component in my app. However, in android, setting the aspectmode for the forms component doesn't seem to do anything. Looking at the source, there is a TODO about it. Am I right that the aspectmode is not implemented in android? And if so, how can I prevent the video from being stretched. I mean, if that's not possible, how can anyone use the component?

**Comment by logikonline** [comment]
@PaulVrugt I have a solution if you are using Xamarin Forms - if you IM me, I'll paste you the code to get you moving forward.

**Comment by codercampos** [comment]
I have a custom render that handle this. Leaving a comment as a bookmark to share with you later

**Comment by JohnGalt1717** [comment]
Here here! This needs to be fixed!

**Comment by codercampos** [comment]
To giving (finally a clue) how We can solve this:

I wrote my own ViewRenderer that uses a custom layout, inflates it and add it to the native control. The code I used is this on the OnElementChanged method:

```
var videoPlayer = Element as VideoPlayer; ///
var url = string.IsNullOrEmpty(videoPlayer.VideoResource) ? string.Empty : Core.AppConfig.VideosUrl + videoPlayer.VideoResource;
var layout = (LinearLayout)LayoutInflater.From(Forms.Context).Inflate(Resource.Layout.player_activity, null, false);
var player = (VideoView)layout.FindViewById(Resource.Id.videoLinear);
var uri = Android.Net.Uri.Parse(url);
player.SetVideoURI(uri);
var mediaController = new MediaController(Forms.Context); 
mediaController.SetAnchorView(player);
player.SetMediaController(mediaController);
player.Start();
SetNativeControl(layout); 
```

And this is the layout I used:
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:orientation="vertical"
    android:gravity="center_vertical"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:id="@+id/player_view">
    <VideoView
        android:id="@+id/videoLinear"
        android:gravity="center_vertical"
        android:layout_alignParentTop="true"
        android:layout_alignParentBottom="true"
        android:layout_alignParentLeft="true"
        android:layout_alignParentRight="true"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent" />
</LinearLayout>
```

This fixes the aspect ratio on the video (So far I tested it). I grabbed this I don't remember where (maybe stackoverflow or something) but this is a common issue even using ExoPlayer. Maybe We can use some workaround like this into the code. I promise I'll check it out this week

**Comment by varyamereon** [comment]
Did this get resolved? I am still seeing the issue on Android and the reference to #297 seems to be incorrect.
