### ISSUE TITLE
Xamarin.Forms 2.3.2.127 compatibility

### ISSUE THREAD

**Issue by tlhintoq** [martijn00/XamarinMediaManager#26]
This NuGet won't install in .Droid project because of wanting Xamaring.Android.Support.v4 23.4.0.1 - but that version is not compatable with current Xamarin.Forms 2.3.2.127 constraint of 23.3.0

**Comment by JanWidm** [comment]
Same issue for me. Cannot install the latest version. Not compatible with Xamarin.Forms (Xamarin.Android.Support.v4 23.3.0) if I would update my Android.Support.v4 Xamarin would not work (Xamarin is using 23.4.0.1)

**Comment by martijn00** [comment]
For Forms i've released version 0.0.0.1. The code base is the same as 0.0.7, but with dependency on v4 23.3.0

See Nuget for download: https://www.nuget.org/packages/Plugin.MediaManager/0.0.0.1
