### ISSUE TITLE
I need to add some extra functionality

### ISSUE THREAD

**Issue by interCreaciones** [martijn00/XamarinMediaManager#267]
Hi guys, it's amazing the work you are doing with this plugin, it has made me a lot of work, although now I have a small problem and I do not know how to approach it, I need to add some extra functionality and the nugget packages can not be modified, I tried add plugin folders(abstraction, mediamanager, etc..) to my project without success, I have also tried to compile the source code that you have in the web and it does not work either,
How could we solve this? Regards and thanks for everything

**Comment by martijn00** [comment]
The develop branch builds for me. You could modify that and make a pull request so i can update the nuget. You can also override the interface for something you want to change. You can also open issue's with feature requests here, but i don't know when i can work on them.

**Comment by interCreaciones** [comment]
Thank you for answering so quickly, My goal is change the appearance of the bar notification and the lockscreen. I'm trying to implement my own IMediaNotificationManager but do not really know how to do it. 
I think I need create in PCL my own Interface that inherit from IMediaNotificationManager just like DependencyService, but I'm a mess. Thanks for all.

**Comment by mike-rowley** [comment]
Once PR#277 is released, there will be a process in place to replace the Android Media Notification Manager by creating a class in your Android app inherited from IAndroidMediaNotificationManager.

Then by assigning that class to the MediaNotificationManager like this: CrossMediaManager.Current.MediaNotificationManager = new zoMediaNotificationManagerImplementation(Android.App.Application.Context, typeof(MediaPlayerService));

Here is an example of a replacement class, the only real change is removing the forward and previous buttons:

`    internal class zoMediaNotificationManagerImplementation : IAndroidMediaNotificationManager
    {
        public IMediaQueue MediaQueue { get; set; }
        public MediaSessionCompat.Token SessionToken { get; set; }

        internal const int _notificationId = 1;

        private Intent _intent;

        private PendingIntent _pendingCancelIntent;
        private PendingIntent _pendingIntent;
        private NotificationCompat.MediaStyle _notificationStyle = new NotificationCompat.MediaStyle();
        private Context _applicationContext;
        private NotificationCompat.Builder _builder;

        public zoMediaNotificationManagerImplementation(Context applicationContext, Type serviceType)
        {
            _applicationContext = Application.Context;
            _intent = new Intent(_applicationContext, serviceType);
            var mainActivity =
                _applicationContext.PackageManager.GetLaunchIntentForPackage(_applicationContext.PackageName);
            _pendingIntent = PendingIntent.GetActivity(_applicationContext, 0, mainActivity,
                PendingIntentFlags.UpdateCurrent);
        }

        /// <summary>
        /// Starts the notification.
        /// </summary>
        /// <param name="mediaFile">The media file.</param>
        public void StartNotification(IMediaFile mediaFile)
        {
            StartNotification(mediaFile, true, false);
        }

        /// <summary>
        /// When we start on the foreground we will present a notification to the user
        /// When they press the notification it will take them to the main page so they can control the music
        /// </summary>
        public void StartNotification(IMediaFile mediaFile, bool mediaIsPlaying, bool canBeRemoved)
        {
            var icon = (_applicationContext.Resources?.GetIdentifier("xam_mediamanager_notify_ic", "drawable", _applicationContext?.PackageName)).GetValueOrDefault(0);

            _notificationStyle.SetMediaSession(SessionToken);
            _notificationStyle.SetCancelButtonIntent(_pendingCancelIntent);

            _builder = new NotificationCompat.Builder(_applicationContext)
            {
                MStyle = _notificationStyle
            };
            _builder.SetSmallIcon(icon != 0 ? icon : _applicationContext.ApplicationInfo.Icon);
            _builder.SetContentIntent(_pendingIntent);
            _builder.SetOngoing(mediaIsPlaying);
            _builder.SetVisibility(1);

            SetMetadata(mediaFile);
            AddActionButtons(mediaIsPlaying);
            if (_builder.MActions.Count >= 3)
                ((NotificationCompat.MediaStyle)(_builder.MStyle)).SetShowActionsInCompactView(0, 1, 2);
            if (_builder.MActions.Count == 2)
                ((NotificationCompat.MediaStyle)(_builder.MStyle)).SetShowActionsInCompactView(0, 1);
            if (_builder.MActions.Count == 1)
                ((NotificationCompat.MediaStyle)(_builder.MStyle)).SetShowActionsInCompactView(0);

            NotificationManagerCompat.From(_applicationContext)
                .Notify(_notificationId, _builder.Build());
        }

        public void StopNotifications()
        {
            NotificationManagerCompat nm = NotificationManagerCompat.From(_applicationContext);
            nm.Cancel(_notificationId);
        }

        public void UpdateNotifications(IMediaFile mediaFile, MediaPlayerStatus status)
        {
            try
            {
                var isPlaying = status == MediaPlayerStatus.Playing || status == MediaPlayerStatus.Buffering;
                var isPersistent = status == MediaPlayerStatus.Playing || status == MediaPlayerStatus.Buffering || status == MediaPlayerStatus.Paused;
                var nm = NotificationManagerCompat.From(_applicationContext);
                if (nm != null && _builder != null)
                {
                    SetMetadata(mediaFile);
                    AddActionButtons(isPlaying);
                    _builder.SetOngoing(isPersistent);
                    nm.Notify(_notificationId, _builder.Build());
                }
                else
                {
                    StartNotification(mediaFile, isPlaying, false);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                StopNotifications();
            }
        }

        private void SetMetadata(IMediaFile mediaFile)
        {
            _builder.SetContentTitle(mediaFile?.Metadata?.Title ?? string.Empty);
            _builder.SetContentText(mediaFile?.Metadata?.Artist ?? string.Empty);
            _builder.SetContentInfo(mediaFile?.Metadata?.Album ?? string.Empty);
            _builder.SetLargeIcon(mediaFile?.Metadata?.Art as Bitmap);
        }

        private Android.Support.V4.App.NotificationCompat.Action GenerateActionCompat(int icon, string title, string intentAction)
        {
            _intent.SetAction(intentAction);

            PendingIntentFlags flags = PendingIntentFlags.UpdateCurrent;
            if (intentAction.Equals(MediaServiceBase.ActionStop))
                flags = PendingIntentFlags.CancelCurrent;

            PendingIntent pendingIntent = PendingIntent.GetService(_applicationContext, 1, _intent, flags);

            return new Android.Support.V4.App.NotificationCompat.Action.Builder(icon, title, pendingIntent).Build();
        }

        private void AddActionButtons(bool mediaIsPlaying)
        {

            _builder.MActions.Clear();
            _builder.AddAction(mediaIsPlaying
                ? GenerateActionCompat(Resource.Drawable.pause_black, "Pause", MediaServiceBase.ActionPause)
                : GenerateActionCompat(Resource.Drawable.play_black, "Play", MediaServiceBase.ActionPlay));
        }
    }
`
