### ISSUE TITLE
v1.0 Specifications

### ISSUE THREAD

**Issue by brminnick** [martijn00/XamarinMediaManager#272]
# v1.0 Specifications
Here is the list of features to finish before releasing v1.0

## Priority
- [x] Add NetStandard support
- [x] Use `MediaBrowserServiceCompat` for Android so Audio doesn't die on Oreo
- [x] Implement support for Aspect Ratio on Android [#255](https://github.com/martijn00/XamarinMediaManager/issues/255) 
- [x] Implement Android ExoPlayer & make it the default

## Optional
- [ ] Add ability to control playback speed for both Audio [#201](https://github.com/martijn00/XamarinMediaManager/issues/201) and Video
- [ ] Add ability to control video/audio quality

## Others
- [x] Create detailed readme
- [x] Add documentation
- [x] Fix CI

# v1.x Specifications
- [ ] Support for Android Wear, Car, Chromecast
- [ ] Support for Carplay

**Comment by arnvanhoutte** [comment]
How is the progress so far? When I look at the issues I can see that there are a lot of people eagerly waiting for a release with .net standard support.

**Comment by Inrego** [comment]
If I'm not mistaken, it looks like we're getting close to a 1.0 release?

**Comment by martijn00** [comment]
Let's track the rest of this in separate issues.
