### ISSUE TITLE
Linking fails on Android with Media Manager (latest)

### ISSUE THREAD

**Issue by JohnGalt1717** [martijn00/XamarinMediaManager#278]
using Oreo sdk, and the latest nuget packages and Xamarin Forms etc. if you enable Linking (either sdk only or sdk and user assemblies it will fail with the following error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'System.Void Plugin.MediaManager.MediaNotificationManagerImplementation::StartNotification(Plugin.MediaManager.Abstractions.IMediaFile,System.Boolean,System.Boolean)' in assembly: 'Plugin.MediaManager.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve Android.Support.V7.App.NotificationCompat/MediaStyle Android.Support.V7.App.NotificationCompat/MediaStyle::SetMediaSession(Android.Support.V4.Media.Session.MediaSessionCompat/Token)
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	CADLearning.Mobile.Droid	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	1628	

Appears to be styling or something that is broken?

**Comment by mattperzel** [comment]
Also seeing this.  Currently trying to debug it.

**Comment by martijn00** [comment]
Are you using newer Android Support Packages than the dependencies? Like v25.4 or v26?

**Comment by JohnGalt1717** [comment]
Yes. Forms now allows for latest. Hence a fully Oreo ready forms project uses v26.

**Comment by mattperzel** [comment]
We also upgraded to 26. I'm trying to see if it builds when targeting O now.

**Comment by martijn00** [comment]
I guess the problem lays in that. The current code base has no guarantee to work with anything higher then 25.3.1. There is some work done to update to v26 but that is not finished yet.

**Comment by JohnGalt1717** [comment]
It works. It just won't link or aot.

**Comment by mattperzel** [comment]
I was able to confirm that upgrading the Android to use the official Xamarin 26.0.2 Support versions did work on a non-forms project.  Other then some build script issues, the changes to the Android project were only the references.

**Comment by nodoid** [comment]
I'm getting this with 25.3.1 targeting android 7.1 in my forms project. Is there something I need to be doing to get a build out for testing?

**Comment by nodoid** [comment]
Any progress on this bug? I have an app awaiting an update and this is stopping it.

**Comment by mike-rowley** [comment]
V26 support is a while away, for perspective the 4 day old Xamarin Forms prerelease only now supports V25 and MonoDroid 7.1.

**Comment by nodoid** [comment]
Ah - which version of the appcompat libraries should I link against? The ones I've tried still give the link error

**Comment by mike-rowley** [comment]
Sample projects link with no issues, I would use that as your roadmap.

**Comment by jacobcat** [comment]
Trying to downgrade the Compile SDK or the NuGet packages give me more complicated errors :( So I'll just wait for the fix of this bug.

**Comment by JohnGalt1717** [comment]
FYI, the latest Xamarin Forms update positively freaks out if you don't use the 26.x releases of these now so there is no way of uxing MediManager and actually deploying a reasonable sized version of your app. In addition to .NET standard still not supported I'm wondering if this is ever going to be up to snuff as a project or not and be usable on a regular basis in a production quality project.  Given it's been 2 months since V1 was last noted as the target, what's the deal?

**Comment by nodoid** [comment]
I've left mine on 2.5.09x and manually changed both the android csproj and packages to only grab 25.3.2 of the android compat packages. It works OK, but you have to be careful when updating packages.

**Comment by mike-rowley** [comment]
@JohnGalt1717 the deal is that this is an open source project written and maintained by volunteers.  If you have a PR to contribute we would be happy to look at it.

**Comment by JohnGalt1717** [comment]
So yet another dead duck repo for Xamarin Video playback that should have been part of the native Xamarin Forms package 3+ years ago and can't be trusted in production unless i take it upon myself to basically own the project and keep it up-to-date or am OK with using old versions of Xamarin endlessly because stuff is constantly broken because nothing is maintained.

Got it.  Yet another reason we're seriously considering ditching Xamarin (aside from the 3 bugs in the latest release version of VS.net that prevent you from actually USING Xamarin.)

**Comment by ckristhoff** [comment]
Hi
same here, I get the same error while compile to release.
any solution?

**Comment by mike-rowley** [comment]
@ckristhoff did you read the thread? What version of Support libraries are you using.  As per Martijn's comment above "The current code base has no guarantee to work with anything higher then 25.3.1. There is some work done to update to v26 but that is not finished yet."

**Comment by devinZhou102** [comment]
Hi
I get the same error while compile to release , is there anyway to solve it?

**Comment by nodoid** [comment]
I did create a build against the v26 branch. It needed a few tweaks, but nothing hideous. Not done anything with v27

**Comment by fr5178** [comment]
I can not set linker, using V27

**Comment by martijn00** [comment]
I don't have time to fix up the missing pieces, or the other feature requests right now. I'm available for hire to fix this up and integrate changes into your project if you or anyone else wants. Drop me an email or message and we can talk about it.

**Comment by stefan89** [comment]
I am facing the exact same issue and it is pretty annoying since I need V26 of the support libraries to be able to show push notifications on a Android 8.0+ device.

**Comment by thomcuddihy** [comment]
If you need a v27 compliment version immediately @stefan89, maybe check [this](https://github.com/thomcuddihy/XamarinMediaManager) out. I recommend waiting for the official release though, if you can wait.

**Comment by grantmk** [comment]
Hi @thomcuddihy, do you mind outlining how you built your fork / have a link to a build? I'm new to that particular area!

Thanks in advance!

**Comment by thomcuddihy** [comment]
Heya @grantmk. I've outlined what I did to get my fork to compile in its [README.md](https://github.com/thomcuddihy/XamarinMediaManager/blob/develop/README.md). If you have any specific questions about it, hit me up.

You can download my fork and try compiling it, or try adding the four non-Demo projects to your own project, then add the appropriate `MediaManager.X` projects as Project References to each of your platform projects*.

If you would prefer a pre-compiled version though, please find my bin [here](https://cloud.hometree.xyz/d/804feca1843f4c0fb17e/). You can add these DLLs as .Net Assembly references to your solution, and then enable the appropriate `MediaManager.X` projects for each of your platform projects.

*i.e. add `MediaManager` and `MediaManager.Forms` to every platform project (`YourProject.Droid` and `YourProject.iOS`), then add either `MediaManager.Droid` or `MediaManager.iOS` respectively. If you need more platforms than just Android and iOS, let me know and I'll try to update my fork. It's great that MediaManager supports so many, but I just don't use them in my work.

**Comment by grantmk** [comment]
@thomcuddihy, thanks for fast and specific reply - much appreciated! I owe you a beer for helping get this project out the door!

**Comment by Vaibhav-Khanna** [comment]
@thomcuddihy I would like to sincerely thank you for your effort. Its a very great help from you. Rest all was good and worked. Except the local files playing on android if i enable exoplayer. 

Do you have any idea how to make it work ?

**Comment by zwithus** [comment]
@thomcuddihy I have followed your instruction to use the bin files. But need to add NuGet package ExoPlayer.Core as MediaManager.Android needs it. When I add ExoPlayer,Core, I get lost of other issue, if not I get again the linking issue. Could you please help me in this regard? Thanks.

**Comment by oguzhanorhaan** [comment]
I have the same issue

**Comment by wpanduka** [comment]
I have the same issue , struggling to find solution past few weeks , useless , does some one have solid solution for this ??, Thank you in advance for your support

**Comment by OmidID** [comment]
I have the same issue . does some one have solution for this ???
I cannot downgrade android support library because other libraries i use they are base on version 27 and I used this library in entire project.

**Comment by zwithus** [comment]
@OmidID I could not manage to fix this issue. Since playing a MP3 file was only needed in my project, I created a custom renderer in which iOS project uses XamarinMediaManager and Android project uses the Android.Media native library. Following code indicates how the Android library was implemented.

```
using Xamarin.Forms;
using MyApp.PlatformSpecific;
using Android.Media;
using MyApp.Droid.PlatformSpecific;

[assembly: Dependency(typeof(AudioPlayer))]
namespace MyApp.Droid.PlatformSpecific
{
    public class AudioPlayer : IAudioPlayer
    {
        private MediaPlayer _mediaPlayer;
        private AudioAttributes _audioAttributes = new AudioAttributes.Builder().SetFlags(AudioFlags.None).SetLegacyStreamType(Stream.Music).Build();

        public void Play(string url)
        {
            _mediaPlayer = new MediaPlayer();
            _mediaPlayer.SetDataSource(url);
            _mediaPlayer.SetAudioAttributes(_audioAttributes);
            _mediaPlayer.PrepareAsync();
            _mediaPlayer.Prepared += (sender, e) => _mediaPlayer.Start();
        }
    }
}
```

**Comment by OmidID** [comment]
@zwithus I downloaded the source code and I had compiled that by myself. And no more error !

**Comment by Gerben321** [comment]
So, the year is 2019 and still no fix? Sad, have to look for another package then.

**Comment by martijn00** [comment]
@Gerben321 you have done 13 open source commits in the last 3 years, i bet not financially contributed either. Sad, i will not help you.

**Comment by Gerben321** [comment]
@martijn00 aww no need to cry. I get paid for my work. Good thing there are working alternatives so this outdated code, with people that are eager to to fix their stuff. And your bet is wrong. Since I am planning to use the media features for a big company a financial contribution would be possible. But not to you obviously, too bad.

**Comment by martijn00** [comment]
@Gerben321 that is an even more offensive comment. I'm happy you won't use my work because you don't deserve it. Try to read up on open source, especially on abusive open source comments and how that leads to open source maintainer burnout. There is a whole world waiting to be discovered for you.

**Comment by Gerben321** [comment]
Haha I know all about it. I have a project with over a million users that's open source. But it seems my users value the communication and work that's being done. I don't think you have to worry about a burnout, lol.
