### ISSUE TITLE
How does one set the info in the Android notification?

### ISSUE THREAD

**Issue by jamesmontemagno** [martijn00/XamarinMediaManager#279]
![image](https://user-images.githubusercontent.com/1676321/31642666-e97ec946-b2a0-11e7-911c-fc10b64674ef.png)

I am doing this:
```
 await CrossMediaManager.Current.Play(new MediaFile(url, Plugin.MediaManager.Abstractions.Enums.MediaFileType.Audio, Plugin.MediaManager.Abstractions.Enums.ResourceAvailability.Remote)
                            {
                                Metadata = new MediaFileMetadata
                                {
                                    Title = Item.Name,
                                    Artist = "Volunteer Park Trust",
                                    Album = "Walking Tour"
                                }
                            });
```

I am not sure if the mp3 has any meta data in it, so was trying to set it manually?

**Comment by mike-rowley** [comment]
The Android notification extracts whatever data may or may not be in the ID3 tags and displays that, overwriting anything you have manually entered.  I am not sure if it was initially designed that a user can enter their own meta data, however I have added a bool ExtractMetadata property to the media file, allowing a user to prevent the overwrite.
PR#285 addresses this issue on Android

**Comment by jamesmontemagno** [comment]
I will fix up the ID3 tags on these MP3s, that makes sense :)
