### ISSUE TITLE
iOS background audio not working

### ISSUE THREAD

**Issue by potterdev** [martijn00/XamarinMediaManager#281]
In version 0.4.4 and iOS 11 the audio stops when app is in background even with everything added in Info.plist. This also happens in the sample application. 
Even though you can't hear the audio, when resuming the app, it continues as if it were still playing (without being paused while in the background).

**Comment by potterdev** [comment]
Never mind. It seems the background play works on an actual device. Only in the simulator it seems to fade out.

**Comment by ThaineNorris** [comment]
I can confirm this also. Background audio used to work before iOS 11.

Also, I have code that stops then replaces the currently playing audio when the user selects a different podcast. This works on Android and UWP and used to work on iOS. Now it crashes on iOS 11.

I noticed via some debugging output that audio buffering continues even after Stop() has been called. I don't know if this was the behavior before iOS 11, but it seems like buffering should only continue if the audio is paused.

**Comment by mike-rowley** [comment]
Apparently this is a known issue, Jeremy Huddleston Sequoia is an Apple Engineer according to his bio.
https://stackoverflow.com/questions/46601068/backgound-audio-not-working-in-ios10-ios11-on-simulator

**Comment by ThaineNorris** [comment]
I thought I had my info.plist settings correct, but I didn't. Background audio **is working** on my physical device.
