### ISSUE TITLE
Error while playing audio file

### ISSUE THREAD

**Issue by ericleroy01** [martijn00/XamarinMediaManager#282]
Hi,

app crashes when attempt to play an audio file

getting following error : 
I/mono-stdout( 1566): Method 'Android.Support.V7.App.NotificationCompat/MediaStyle.SetMediaSession' not found.
Method 'Android.Support.V7.App.NotificationCompat/MediaStyle.SetMediaSession' not found.

**Comment by mike-rowley** [comment]
We'll need some details, are you running a branch?  Or the Nuget 0.45?

Anything else you can provide to help us reproduce the issue would be good.

**Comment by bond-os** [comment]
Hi,

I have the same error on 0.4.5 from nuget, after upgrading monoandroid from 7.1 to 8.0

**Comment by ThaineNorris** [comment]
Hello, I have encountered the same error running 0.4.5 from nuget under monoandroid 8.0.

Method 'Android.Support.V7.App.NotificationCompat/MediaStyle.SetMediaSession' not found.
I/mono-stdout( 1780): Method 'Android.Support.V7.App.NotificationCompat/MediaStyle.SetMediaSession' not found.
An unhandled exception occured.

**Comment by mike-rowley** [comment]
I have no issues running the Android sample apps with Xamarin.Android.* libraries at 25.3.1.  XamarinMediaManager 0.45 was released 16 days ago, Xamarin.Android.* 26.0.2 libraries that support MonoAndroid 8 were released 13 days ago.  

Make sure you are running the 25.3.1 version of Xamarin.Android.* dependencies and MonoAndroid 7 with 0.45.

**Comment by ThaineNorris** [comment]
Thanks for the reply. I downgraded the Android nuget packages from 26.0.2 to 25.4.0.2, and now all is well.

**Comment by mike-rowley** [comment]
Excellent, thanks for the update.

**Comment by superbluecool** [comment]
it's been a few months already, any plans to support Android package v26? Having the same issue:
Method 'Android.Support.V7.App.NotificationCompat/MediaStyle.SetMediaSession' not found.
and:
'Android.Support.V7.App.NotificationCompat/MediaStyle.SetMediaSession' not found.

**Comment by ij0see** [comment]
@ThaineNorris How id you downgrade Android Nuget Packages? 
I'm getting this error when I try to upgrade: 

> Attempting to resolve dependencies for package 'Xamarin.Android.Support.v4.25.4.0.2' with DependencyBehavior 'Lowest'
One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'Xamarin.Android.Support.v4 26.1.0.1'
Unable to find a version of 'Xamarin.Android.Support.Annotations' that is compatible with 'Xamarin.Android.Arch.Core.Common 26.1.0 constraint: Xamarin.Android.Support.Annotations (>= 26.1.0)', 'Xamarin.Android.Arch.Lifecycle.Common 26.1.0 constraint: Xamarin.Android.Support.Annotations (>= 26.1.0)', 'Xamarin.Android.Arch.Lifecycle.Runtime 26.1.0 constraint: Xamarin.Android.Support.Annotations (>= 26.1.0)', 'Xamarin.Android.Support.Compat 25.4.0.2 constraint: Xamarin.Android.Support.Annotations (= 25.4.0.2)'.

**Comment by ignasbagdonas** [comment]
Have the same issue. Any solutions? I don't want downgrade my android packages.
I am playing audio from url, after pause android can't resume audio.

**Comment by ij0see** [comment]
@ignasbagdonas  
https://developer.xamarin.com/guides/android/application_fundamentals/working_with_audio/

It was enough for me, so I didn't use this library...

**Comment by ignasbagdonas** [comment]
Okay, looks like I should go the same way.
Thanks.
