### ISSUE TITLE
iOS never reports MediaPlayerStatus.Stopped

### ISSUE THREAD

**Issue by ThaineNorris** [martijn00/XamarinMediaManager#288]
Perhaps I am missing something, but even though my audio plays to the end, the media player never reports MediaPlayerStatus.Stopped to the StatusChanged event handler. This event *is* reported on Android and UWP.

**Comment by mike-rowley** [comment]
There seems to be an issue with how iOS is reporting those stop events, they come back as a pause.  I will try to investigate this further, if you have a PR with a fix please send it over, we'd be more than happy to have a look at it.
