### ISSUE TITLE
[All Platforms] Play(IEnumerable<IMediaFile> mediaFiles) seems not playing media files in order

### ISSUE THREAD

**Issue by BtrJay** [martijn00/XamarinMediaManager#290]
Hi @martijn00 ,

I've found that there's an issue when you invoke Play overloading method passing list of mediaFiles as a parameter.

Steps to reproduce (Plugin.MediaManager 0.4.5)

1. Create a list of media files

            var list = new List<MediaFile>
            {
                new MediaFile
                {
                    Url = "https://audioboom.com/posts/5766044-follow-up-305.mp3?source=rss&amp;stitched=1",
                    Type = MediaFileType.Audio,
                    Metadata = new MediaFileMetadata
                    {
                        Title = "Test1"
                    }
                },
                new MediaFile
                {
                    Url = "https://media.acast.com/mydadwroteaporno/s3e1-london-thursday15.55localtime/media.mp3",
                    Type = MediaFileType.Audio,
                    Metadata = new MediaFileMetadata
                    {
                        Title = "Test2"
                    }
                },
                new MediaFile
                {
                    Url =
                        "https://audioboom.com/posts/5770261-ep-306-a-theory-of-evolution.mp3?source=rss&amp;stitched=1",
                    Type = MediaFileType.Audio,
                    Metadata = new MediaFileMetadata
                    {
                        Title = "Test3"
                    }
                },
                new MediaFile
                {
                    Url = "https://audioboom.com/posts/5723344-ep-304-the-4th-dimension.mp3?source=rss&amp;stitched=1",
                    Type = MediaFileType.Audio,
                    Metadata = new MediaFileMetadata
                    {
                        Title = "Test4"
                    }
                }
            };

2. pass this list to Play method

await CrossMediaManager.Current.Play(list);

3. Observe the media file CrossMediaManager is currently playing

CrossMediaManager.Current.MediaQueue.Current

Expected
- The current media file in media queue should be the first on in the list

Actual
- The current media file reflects the second item in the list which seems not to be correct.

Please let me know if you would like me to create a PR for that.

Kind Regards,

Jay SIm

**Comment by mike-rowley** [comment]
We would be happy to have a look at a PR that fixes this issue. Thanks

**Comment by BtrJay** [comment]
Thanks @mike-rowley ,

We will create a PR shortly with the fixes for this issue.

Regards,

Jay
