### ISSUE TITLE
Why Wont The MediaNotificationManager Die?

### ISSUE THREAD

**Issue by Nickprovs** [martijn00/XamarinMediaManager#293]
I have this line in my constructor on my page.

```` CrossMediaManager.Current.AudioPlayer.StatusChanged += OnStatusChangedHandler;````

This is a method in that class.

````
private void OnStatusChangedHandler(object sender, StatusChangedEventArgs e)
        {
            if (e.Status == Plugin.MediaManager.Abstractions.Enums.MediaPlayerStatus.Stopped)
                audioCleanup();
        }

````

This is audioCleanup()
````
        protected void audioCleanup()
        {
            if (CrossMediaManager.Current.AudioPlayer.Status != Plugin.MediaManager.Abstractions.Enums.MediaPlayerStatus.Stopped)
                CrossMediaManager.Current.AudioPlayer.Stop();

            if (CrossMediaManager.Current.MediaNotificationManager != null)
            {
                CrossMediaManager.Current.MediaNotificationManager.StopNotifications();
            }
        }
````

The media manager notification bar thing at the top disappears and then reappears in a second. Despite there not being any audio playing. I'm testing on Android atm.

**Comment by mike-rowley** [comment]
I had this exact issue, in my case it was a timer I had setup calling UpdateNotification, which reinitializes the Notification.

**Comment by Nickprovs** [comment]
@mike-rowley I  don't recall ever having called UpdateNotification. My application generates a sound file based on user input upon a button click. At which point, I generate a .wav and await the media manager to play the sound. That's the extent of it.
