### ISSUE TITLE
[Android] Backward/Forward button is missing in Notification bar

### ISSUE THREAD

**Issue by BtrJay** [martijn00/XamarinMediaManager#294]
Hi @martijn00 ,

We have found that backward/forward button is missing in notification bar. (Please see the attachment below)

![backwardforwardbuttons](https://user-images.githubusercontent.com/22138279/32525941-f9c3a4de-c47a-11e7-81b8-33182417e175.png)

The steps to replicate is

1. Play/pause something

2. Check the notification centre

Is there a fix already merged or is it something we need to fix it?

Kind Regards,

Jay

**Comment by mike-rowley** [comment]
Does the playlist have songs ahead and behind it?  There was new code added to show and hide the buttons based on the playlist in MediaSession\MediaNotificationManagerImplementation.cs.

You can change this functionality by using the IAndroidMediaNotificationManager interface and implementing your own version of the Notification Manager.  I would suggest starting with the existing code and modifying it to suit your needs.

Simply assign the newly created Notification Manager in OnCreate
            CrossMediaManager.Current.MediaNotificationManager = new zoMediaNotificationManagerImplementation(Android.App.Application.Context, typeof(MediaPlayerService));


Let me know on here if you have issues and I'll try to help, I wrote the interface for my own use and sent Martijn the PR.

**Comment by BtrJay** [comment]
Hi @mike-rowley ,

I have submitted the pull request to determine visibility of previous/next button, but not backward/forward button.

By the way, thanks for your suggestion.

Kind Regards,

Jay
