### ISSUE TITLE
Notification controls not working with Exoplayer

### ISSUE THREAD

**Issue by potterdev** [martijn00/XamarinMediaManager#295]
The notification controls are not working with the exoplayer implementation.
I tried to write a custom notification manager implementation but I'm probably doing something wrong since OnReceive is never called on the BroadcastReceiver.

Any help is highly appreciated.

Thanks and great work so far !

**Comment by potterdev** [comment]
Seems the same problem happens on ios 11, the controls don't do anything. (using the default player)

**Comment by mike-rowley** [comment]
The MediaManager currently uses V1 of ExoPlayer, we are working on a V1 update that will use ExoPlayer2.

I have no problem with the controls working on Android using MediaPlayer or on iOS using AVPlayer.

**Comment by potterdev** [comment]
Then I must me doing something wrong on my iOS project...

**Comment by potterdev** [comment]
I found the issue:

I am using CrossmediaManager.Current.Audioplayer.Play to start the audio. When using the PlaybackController to pause or stop, it does nothing in either AVMediaPlayer or Exoplayer.

I've overriden the RemoteControlReceived method and used Audioplayer.Stop or Pause and it is working.

**Comment by mike-rowley** [comment]
Is this issue in IOS or Android?  You a mixing the two in the comments.

Have you reviewed the sample app for the appropriate platform?

**Comment by potterdev** [comment]
It happens on both platforms.

**Comment by mike-rowley** [comment]
As we've discussed, exoplayer is not a complete implementation and therefore the notification controls don't work, disable exoplayer, use MediaPlayer and the controls work properly on android.

As for IOS, the sample app works, I am augmenting the forms app to work as well.
Did you override the RemoteControlReceived call as per the documentation?

_If you want to enable RemoteControl features, you will have to override UIApplication.RemoteControlReceived(UIEvent) and forward the event to the MediaManagerImplementation.MediaRemoteControl.RemoteControlReceived(UIEvent) method. See the sample application for more details._

**Comment by Malkiat-Singh** [comment]
@mike-rowley  
--------
> As we've discussed, exoplayer is not a complete implementation and therefore the notification controls don't work, disable exoplayer, use MediaPlayer and the controls work properly on android.

How you make this one works for android. Its not working in my application
