### ISSUE TITLE
Error after roughly 15 minutes of audio

### ISSUE THREAD

**Issue by ThaineNorris** [martijn00/XamarinMediaManager#298]
I have written a podcast player using the XMM player and it works great on iOS. However, on Android the audio stops after roughly 15 minutes. During the playback, Android reports the following error 2-3 times:

W/MediaHTTPConnection(21980): readAt 23084778 / 32768 => java.net.ProtocolException: unexpected end of stream

Then, after approximately 15 minutes, the playback stops and the following errors are reported:

11-08 21:05:32.852 E/ExtMediaPlayer-JNI(21980): env->IsInstanceOf fails
11-08 21:05:32.852 E/MediaPlayer-JNI(21980): JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
11-08 21:05:32.852 E/ExtMediaPlayer-JNI(21980): env->IsInstanceOf fails
11-08 21:05:32.852 E/MediaPlayer-JNI(21980): JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
11-08 21:05:32.860 W/MediaPlayer(21980): Couldn't open requested URI.
Thread started: <Thread Pool> #52
Thread started: <Thread Pool> #53
11-08 21:05:33.292 E/MediaPlayer(21980): Attempt to call getDuration in wrong state: mPlayer=0x7f6e4d5280, mCurrentState=4
11-08 21:05:33.292 E/MediaPlayer(21980): error (-38, 0)
11-08 21:05:33.295 E/MediaPlayer(21980): Attempt to call getDuration in wrong state: mPlayer=0x7f6e4d5280, mCurrentState=0
11-08 21:05:33.295 E/MediaPlayer(21980): error (-38, 0)
11-08 21:05:33.315 E/MediaPlayer(21980): Error (-38,0)

This problem occurs with your Simple MediaSample sample project. All you have to do is play a long stream. If you can't find one for testing, you can try this: https://www.backtojerusalem.com/btj-podcast/episodes/215-Silence-A-BTJ-Movie-Review.mp3. I put it into the mediaUrls collection in MediaPlayerViewModel.cs.

Your sample application uses Xamarin.Android... version 25.3.1. My own application uses version 25.4.0.2. The problem behavior is the same on both.

Can somebody look into this?

Thank you!

**Comment by mike-rowley** [comment]
What version of Android are you testing it on?

**Comment by ThaineNorris** [comment]
Your sample application uses 25.3.1. My application uses 25.4.0.2. Both have the same errors.

Sent from Mail for Windows 10

**Comment by mike-rowley** [comment]
What version of Android is on the phone you are testing with?

**Comment by ThaineNorris** [comment]
The MediaSample application is configured to “Use latest platform (Android 8.0 (Oreo))”

My application is configured to use “Android 7.1 (Nougat)”

I am testing on a Sony xPeria with Android 7.1.1

Sent from Mail for Windows 10

**Comment by mike-rowley** [comment]
I tested your file in the MediaForms Android app, it played the entire file with no error.  I am testing it again now, I'll let you know if I can reproduce the issue but it looks like it may be something else in your setup or code base that is the issue.

I have personally used the MediaManager on Android to play ShoutCast streams for in excess of 8 hours continuously with no issues at all.

There are certainly some issues around MediaPlayer on Android so it may be an OS issue, we are currently working on an ExoPlayer2 version and some other updates you can see in the V1 Spec in the issues list.  ExoPlayer2 will provide much more reliability and functionality.

**Comment by mike-rowley** [comment]
I am getting an error but a different error around the 20 minute mark twice.  I'm testing a different file to ensure it isn't a corrupt mp3.

11-08 22:47:28.592 E/MediaPlayerNative(16824): error (1, -1010)
11-08 22:47:28.593 E/MediaPlayer(16824): Error (1,-1010)

**Comment by mike-rowley** [comment]
I would suggest looking at the connection timeout limit on your server, I am able to play an Azure CDN hosted MP3 via HTTPS stream in excess of 30 minutes and still going.

**Comment by ThaineNorris** [comment]
If there is a timeout limit on our server, would that also affect iOS? The XMM code works without issue on iOS. Is it because the iOS implementation buffers and the Android one does not? I'm not sure where to look for such a timeout if that is the case, but I have asked our host.

You said you used the MediaForms Android app to test it. When I look at that project, the only object available in the Plugin.MediaManager.Forms namespace is a VideoView. Did you play your test audio stream through a VideoView? I was testing the MediaSample.Droid sample app, which my own audio player code is based on.

Finally, what is ExoPlayer? In the sample app (Samples\Simple\MediaSample.Droid\MainActivity.cs) the ShouldUseExoPlayer flag is set to false. If I set it to true, the audio starts playing but then the app crashes immediately. Therefore, I have never used ExoPlayer in my own code. Should I?

Thanks again for looking into this!

**Comment by mike-rowley** [comment]
The timeout may be an issue based on how Android is connecting to the server.  It may differ on iOS because iOS is doing buffering and controlling the transport layer differently.  I am not an export but that is my educated guess.

XamForms apps have a shared lib or PCL that contains the majority of the app code, only startup code and platform specifics are contained in the platform specific projects.

Google ExoPlayer and ExoPlayer 2, they are the recommended Android technology for robust media apps, which is why we are moving that direction.  MediaPlayer is old technology and I suspect why you are having issues.  I am unable to reproduce your issue on a CDN, which suggests to me there is an issue with something server or transport layer related.

**Comment by ThaineNorris** [comment]
That all makes sense. We are looking into the server timeout for a short term solution and ExoPlayer for a long term solution. I opened a separate issue about problems with ExoPlayer in the sample app. I look forward to testing it!

**Comment by ThaineNorris** [comment]
Any news on when an update containing ExoPlayer support is coming?

**Comment by martijn00** [comment]
I don't have time to fix up the missing pieces, or the other feature requests right now. I'm available for hire to fix this up and integrate changes into your project if you or anyone else wants. Drop me an email or message and we can talk about it.
