### ISSUE TITLE
What about ExoMediaPlayer for Android?

### ISSUE THREAD

**Issue by SimonSimCity** [martijn00/XamarinMediaManager#30]
I just saw, that you're also managing a port of the ExoMediaPlayer for Xamarin ... Was there a reason not to use it in this project, or just the lack of time? 😉

**Comment by martijn00** [comment]
There is an implementation of the MediaManagers interface for ExoPlayer somewhere around. It should be easy to use that on top of this library. If i can find that code somewhere again, i could create a Nuget on top of this one to support ExoPlayer.

**Comment by modplug** [comment]
I guess this can be closed now

**Comment by SimonSimCity** [comment]
So, the plan is to create a new project, that can be placed on top of this library on Android, that contains an implementation for the ExoMediaPlayer, am I right?

I just wanted to get a feedback to also get this implementation going.

**Comment by SimonSimCity** [comment]
Yee, now I see. Fixed by #44

**Comment by martijn00** [comment]
I've already added a project for this: https://github.com/martijn00/XamarinMediaManager/tree/master/MediaManager/Plugin.MediaManager.ExoPlayer

The actual implementation still needs to be done.

I also got the nuspec ready to get the Nuget up.
