### ISSUE TITLE
Simple/MediaSample.Droid with ExoPlayer does not work

### ISSUE THREAD

**Issue by ThaineNorris** [martijn00/XamarinMediaManager#301]
Okay, I downloaded the updated sample project and got it to build without any changes to the code. The sample plays the audio as expected. However, it does not use ExoPlayer by default. 

When I changed the ShouldUseExoPlayer flag to true, the audio did not play. Instead it never plays, and endlessly displays "BufferingChanged: 0" It looks like maybe it has trouble finding the file? Of course it works fine w/o the ExoPlayer. 

Here is the output with potentially some clues...

11-09 12:35:37.613 E/AudioManager(10374): Audio focus request denied due to
11-09 12:35:37.613 E/AudioManager(10374): java.lang.IllegalArgumentException: Invalid duration hint
11-09 12:35:37.613 E/AudioManager(10374): at android.media.AudioManager.requestAudioFocus(AudioManager.java:2518)
11-09 12:35:37.613 E/AudioManager(10374): at android.media.AudioManager.requestAudioFocus(AudioManager.java:2477)
11-09 12:35:37.613 E/AudioManager(10374): at android.media.AudioManager.requestAudioFocus(AudioManager.java:2386)
11-09 12:35:37.613 E/AudioManager(10374): at mono.android.view.View_OnClickListenerImplementor.n_onClick(Native Method)
11-09 12:35:37.613 E/AudioManager(10374): at mono.android.view.View_OnClickListenerImplementor.onClick(View_OnClickListenerImplementor.java:30)
11-09 12:35:37.613 E/AudioManager(10374): at android.view.View.performClick(View.java:5685)
11-09 12:35:37.613 E/AudioManager(10374): at android.widget.CompoundButton.performClick(CompoundButton.java:122)
11-09 12:35:37.613 E/AudioManager(10374): at android.view.View$PerformClick.run(View.java:22481)
11-09 12:35:37.613 E/AudioManager(10374): at android.os.Handler.handleCallback(Handler.java:751)
11-09 12:35:37.613 E/AudioManager(10374): at android.os.Handler.dispatchMessage(Handler.java:95)
11-09 12:35:37.613 E/AudioManager(10374): at android.os.Looper.loop(Looper.java:241)
11-09 12:35:37.613 E/AudioManager(10374): at android.app.ActivityThread.main(ActivityThread.java:6274)
11-09 12:35:37.613 E/AudioManager(10374): at java.lang.reflect.Method.invoke(Native Method)
11-09 12:35:37.613 E/AudioManager(10374): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
11-09 12:35:37.613 E/AudioManager(10374): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
11-09 12:35:37.617 D/Mono (10374): DllImport attempting to load: '/system/lib64/liblog.so'.
Could not get audio focus
11-09 12:35:37.618 D/Mono (10374): DllImport loaded library '/system/lib64/liblog.so'.
11-09 12:35:37.618 D/Mono (10374): DllImport searching in: '/system/lib64/liblog.so' ('/system/lib64/liblog.so').
11-09 12:35:37.618 D/Mono (10374): Searching for '__android_log_print'.
11-09 12:35:37.618 D/Mono (10374): Probing '__android_log_print'.
11-09 12:35:37.618 D/Mono (10374): Found as '__android_log_print'.
11-09 12:35:37.619 I/mono-stdout(10374): Could not get audio focus
11-09 12:35:37.631 D/Mono (10374): Assembly Ref addref Plugin.MediaManager[0x7f8d84c900] -> Xamarin.Android.Support.Compat[0x7f8d81be80]: 4
11-09 12:35:37.635 D/Mono (10374): Assembly Ref addref Xamarin.Android.Support.v7.AppCompat[0x7f8d84c480] -> Xamarin.Android.Support.Media.Compat[0x7f8d84c280]: 3
11-09 12:35:37.644 D/Mono (10374): DllImport searching in: '__Internal' ('(null)').
11-09 12:35:37.644 D/Mono (10374): Searching for 'java_interop_jnienv_get_field_id'.
11-09 12:35:37.644 D/Mono (10374): Probing 'java_interop_jnienv_get_field_id'.
11-09 12:35:37.644 D/Mono (10374): Found as 'java_interop_jnienv_get_field_id'.
11-09 12:35:37.645 D/Mono (10374): DllImport searching in: '__Internal' ('(null)').
11-09 12:35:37.645 D/Mono (10374): Searching for 'java_interop_jnienv_set_object_field'.
11-09 12:35:37.645 D/Mono (10374): Probing 'java_interop_jnienv_set_object_field'.
11-09 12:35:37.645 D/Mono (10374): Found as 'java_interop_jnienv_set_object_field'.
11-09 12:35:37.650 D/Mono (10374): DllImport searching in: '__Internal' ('(null)').
11-09 12:35:37.650 D/Mono (10374): Searching for 'java_interop_jnienv_get_int_field'.
11-09 12:35:37.650 D/Mono (10374): Probing 'java_interop_jnienv_get_int_field'.
11-09 12:35:37.650 D/Mono (10374): Found as 'java_interop_jnienv_get_int_field'.
11-09 12:35:37.663 D/Mono (10374): DllImport searching in: '__Internal' ('(null)').
11-09 12:35:37.663 D/Mono (10374): Searching for 'java_interop_jnienv_get_object_field'.
11-09 12:35:37.663 D/Mono (10374): Probing 'java_interop_jnienv_get_object_field'.
11-09 12:35:37.663 D/Mono (10374): Found as 'java_interop_jnienv_get_object_field'.
11-09 12:35:37.666 D/Mono (10374): DllImport searching in: '__Internal' ('(null)').
11-09 12:35:37.666 D/Mono (10374): Searching for 'java_interop_jnienv_call_void_method'.
11-09 12:35:37.666 D/Mono (10374): Probing 'java_interop_jnienv_call_void_method'.
11-09 12:35:37.666 D/Mono (10374): Found as 'java_interop_jnienv_call_void_method'.
11-09 12:35:37.677 D/Mono (10374): DllImport searching in: '__Internal' ('(null)').
11-09 12:35:37.677 D/Mono (10374): Searching for 'java_interop_jnienv_call_int_method'.
11-09 12:35:37.677 D/Mono (10374): Probing 'java_interop_jnienv_call_int_method'.
11-09 12:35:37.677 D/Mono (10374): Found as 'java_interop_jnienv_call_int_method'.
11-09 12:35:37.680 D/Mono (10374): DllImport searching in: '__Internal' ('(null)').
11-09 12:35:37.680 D/Mono (10374): Searching for 'java_interop_jnienv_new_int_array'.
11-09 12:35:37.680 D/Mono (10374): Probing 'java_interop_jnienv_new_int_array'.
11-09 12:35:37.680 D/Mono (10374): Found as 'java_interop_jnienv_new_int_array'.
11-09 12:35:37.681 D/Mono (10374): DllImport searching in: '__Internal' ('(null)').
11-09 12:35:37.681 D/Mono (10374): Searching for 'java_interop_jnienv_set_int_array_region'.
11-09 12:35:37.681 D/Mono (10374): Probing 'java_interop_jnienv_set_int_array_region'.
11-09 12:35:37.681 D/Mono (10374): Found as 'java_interop_jnienv_set_int_array_region'.
11-09 12:35:37.683 D/Mono (10374): DllImport searching in: '__Internal' ('(null)').
11-09 12:35:37.683 D/Mono (10374): Searching for 'java_interop_jnienv_get_int_array_region'.
11-09 12:35:37.683 D/Mono (10374): Probing 'java_interop_jnienv_get_int_array_region'.
11-09 12:35:37.683 D/Mono (10374): Found as 'java_interop_jnienv_get_int_array_region'.
StausChanged Loading
11-09 12:35:37.707 I/mono-stdout(10374): StausChanged Loading
11-09 12:35:37.727 D/Mono (10374): DllImport searching in: '__Internal' ('(null)').
11-09 12:35:37.727 D/Mono (10374): Searching for 'java_interop_jnienv_call_long_method'.
11-09 12:35:37.727 D/Mono (10374): Probing 'java_interop_jnienv_call_long_method'.
11-09 12:35:37.728 D/Mono (10374): Found as 'java_interop_jnienv_call_long_method'.
11-09 12:35:37.735 D/Mono (10374): DllImport searching in: '__Internal' ('(null)').
11-09 12:35:37.735 D/Mono (10374): Searching for 'java_interop_jnienv_call_static_long_method_a'.
11-09 12:35:37.735 D/Mono (10374): Probing 'java_interop_jnienv_call_static_long_method_a'.
11-09 12:35:37.735 D/Mono (10374): Found as 'java_interop_jnienv_call_static_long_method_a'.
11-09 12:35:37.747 D/Mono (10374): DllImport searching in: '__Internal' ('(null)').
11-09 12:35:37.747 D/Mono (10374): Searching for 'java_interop_jnienv_call_boolean_method'.
11-09 12:35:37.747 D/Mono (10374): Probing 'java_interop_jnienv_call_boolean_method'.
11-09 12:35:37.748 D/Mono (10374): Found as 'java_interop_jnienv_call_boolean_method'.
StausChanged Playing
11-09 12:35:37.764 I/mono-stdout(10374): StausChanged Playing
11-09 12:35:37.767 D/Mono (10374): DllImport searching in: '__Internal' ('(null)').
11-09 12:35:37.767 D/Mono (10374): Searching for 'java_interop_jnienv_get_static_int_field'.
11-09 12:35:37.767 D/Mono (10374): Probing 'java_interop_jnienv_get_static_int_field'.
11-09 12:35:37.767 D/Mono (10374): Found as 'java_interop_jnienv_get_static_int_field'.
Thread started: #2
Thread started: #3
Thread started: #4
Thread started: #5
Thread started: #6
11-09 12:35:37.884 D/Mono (10374): DllImport searching in: '__Internal' ('(null)').
11-09 12:35:37.884 D/Mono (10374): Searching for 'java_interop_jnienv_call_nonvirtual_boolean_method_a'.
11-09 12:35:37.885 D/Mono (10374): Probing 'java_interop_jnienv_call_nonvirtual_boolean_method_a'.
11-09 12:35:37.885 D/Mono (10374): Found as 'java_interop_jnienv_call_nonvirtual_boolean_method_a'.
StausChanged Buffering
11-09 12:35:37.888 D/NetworkSecurityConfig(10374): No Network Security Config specified, using platform default
11-09 12:35:37.894 I/mono-stdout(10374): StausChanged Buffering
BufferingChanged: 0
11-09 12:35:37.902 I/mono-stdout(10374): BufferingChanged: 0
StausChanged Buffering
OnTimelineChanged
Loading changed
11-09 12:35:37.914 I/mono-stdout(10374): StausChanged Buffering
11-09 12:35:37.917 I/mono-stdout(10374): OnTimelineChanged
11-09 12:35:37.918 I/mono-stdout(10374): Loading changed
Thread started: #7
BufferingChanged: 0
11-09 12:35:38.026 I/mono-stdout(10374): BufferingChanged: 0
BufferingChanged: 0
11-09 12:35:39.007 I/mono-stdout(10374): BufferingChanged: 0
11-09 12:35:39.422 E/MediaMetadataRetrieverJNI(10374): getEmbeddedPicture: Call to getEmbeddedPicture failed.
File changed: Crazy Love
11-09 12:35:39.467 I/mono-stdout(10374): File changed: Crazy Love
BufferingChanged: 0
11-09 12:35:40.009 I/mono-stdout(10374): BufferingChanged: 0
11-09 12:35:40.633 E/ExoPlayerImplInternal(10374): Source error.
11-09 12:35:40.633 E/ExoPlayerImplInternal(10374): com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: https:/ia800806.us.archive.org/15/items/Mp3Playlist_555/AaronNeville-CrazyLove.mp3: open failed: ENOENT (No such file or directory)
11-09 12:35:40.633 E/ExoPlayerImplInternal(10374): at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:70)
11-09 12:35:40.633 E/ExoPlayerImplInternal(10374): at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:596)
11-09 12:35:40.633 E/ExoPlayerImplInternal(10374): at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
11-09 12:35:40.633 E/ExoPlayerImplInternal(10374): at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
11-09 12:35:40.633 E/ExoPlayerImplInternal(10374): at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-09 12:35:40.633 E/ExoPlayerImplInternal(10374): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
11-09 12:35:40.633 E/ExoPlayerImplInternal(10374): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
11-09 12:35:40.633 E/ExoPlayerImplInternal(10374): at java.lang.Thread.run(Thread.java:761)
11-09 12:35:40.633 E/ExoPlayerImplInternal(10374): Caused by: java.io.FileNotFoundException: https:/ia800806.us.archive.org/15/items/Mp3Playlist_555/AaronNeville-CrazyLove.mp3: open failed: ENOENT (No such file or directory)
11-09 12:35:40.633 E/ExoPlayerImplInternal(10374): at libcore.io.IoBridge.open(IoBridge.java:455)
11-09 12:35:40.633 E/ExoPlayerImplInternal(10374): at java.io.RandomAccessFile.(RandomAccessFile.java:247)
11-09 12:35:40.633 E/ExoPlayerImplInternal(10374): at java.io.RandomAccessFile.(RandomAccessFile.java:128)
11-09 12:35:40.633 E/ExoPlayerImplInternal(10374): at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:62)
11-09 12:35:40.633 E/ExoPlayerImplInternal(10374): ... 7 more
11-09 12:35:40.633 E/ExoPlayerImplInternal(10374): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
11-09 12:35:40.633 E/ExoPlayerImplInternal(10374): at libcore.io.Posix.open(Native Method)
11-09 12:35:40.633 E/ExoPlayerImplInternal(10374): at libcore.io.BlockGuardOs.open(BlockGuardOs.java:187)
11-09 12:35:40.633 E/ExoPlayerImplInternal(10374): at libcore.io.IoBridge.open(IoBridge.java:441)
11-09 12:35:40.633 E/ExoPlayerImplInternal(10374): ... 10 more
Loading changed
11-09 12:35:40.665 I/mono-stdout(10374): Loading changed
StausChanged Loading
11-09 12:35:40.677 I/mono-stdout(10374): StausChanged Loading
StausChanged Playing
11-09 12:35:40.697 I/mono-stdout(10374): StausChanged Playing
BufferingChanged: 0
11-09 12:35:41.009 I/mono-stdout(10374): BufferingChanged: 0
BufferingChanged: 0
11-09 12:35:42.009 I/mono-stdout(10374): BufferingChanged: 0
BufferingChanged: 0
11-09 12:35:43.008 I/mono-stdout(10374): BufferingChanged: 0
BufferingChanged: 0
11-09 12:35:44.013 I/mono-stdout(10374): BufferingChanged: 0
BufferingChanged: 0
11-09 12:35:45.014 I/mono-stdout(10374): BufferingChanged: 0
Thread finished: #4
The thread 'Unknown' (0x4) has exited with code 0 (0x0).
BufferingChanged: 0
11-09 12:35:46.010 I/mono-stdout(10374): BufferingChanged: 0
BufferingChanged: 0
11-09 12:35:47.007 I/mono-stdout(10374): BufferingChanged: 0
BufferingChanged: 0
11-09 12:35:48.011 I/mono-stdout(10374): BufferingChanged: 0
BufferingChanged: 0
11-09 12:35:49.008 I/mono-stdout(10374): BufferingChanged: 0

**Comment by mike-rowley** [comment]
I would recommend using MediaPlayer on Android until our V1 release which will include ExoPlayer2 as the media engine.

**Comment by ThaineNorris** [comment]
Okay, we will wait.

Thank you

**Comment by zabanet** [comment]
Almost a year passed. Do you know when the V1 release will be available?

**Comment by ThaineNorris** [comment]
I am wondering the same thing. Is this project still being worked on?
