### ISSUE TITLE
how to play audio through earpiece speaker

### ISSUE THREAD

**Issue by kfransson** [martijn00/XamarinMediaManager#302]
How can I direct audio to come through the earpiece speaker of the phone?

**Comment by mike-rowley** [comment]
https://www.google.ca/search?q=xamarin+play+sound+in+ear+piece&oq=Xamarin+Play&aqs=chrome.4.69i57j69i60l3j35i39j0.7627j0j7&sourceid=chrome&ie=UTF-8
