### ISSUE TITLE
Mediafile video properties

### ISSUE THREAD

**Issue by lewixlabs** [martijn00/XamarinMediaManager#305]
Hi,
does exist a way to get video width/height properties from a url stream?
I'm using this library in my Xamarin Forms project, and when i set in VideoView horizontal/vertical options to "FillAndExpand" (AspectMode="AspectFill"), video get stretched to max width/height of my Android device in portrait mode.
Video is this streaming url:
http://fms.105.net:1935/live/rmc1/playlist.m3u8
Thank you & sorry if this feature is already implemented.

UPDATE:
I noticed same xaml (Xamarin Forms) in UWP app works correctly: aspect ratio video is ok even if screen height is greater than screen width ("portrait mode" in UWP).

My code is:
Xaml Page
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:CocoTV"
             xmlns:forms="clr-namespace:Plugin.MediaManager.Forms;assembly=Plugin.MediaManager.Forms"
             x:Class="CocoTV.MainPage">
    <ContentPage.Content>
        <forms:VideoView x:Name="videoView"
        HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand"
                     AspectMode="AspectFill"/>
    </ContentPage.Content>
</ContentPage>
```
.cs page
```
namespace CocoTV
{
    public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();
        }

        protected override void OnAppearing()
        {
            base.OnAppearing();

            videoView.Source = "http://fms.105.net:1935/live/rmc1/playlist.m3u8";
            CrossMediaManager.Current.PlaybackController.Play();
        }
    }
}
```
Lewix

**Comment by mike-rowley** [comment]
Download and parse the M3U8 file, the dimensions are contained within the playlist.
#EXT-X-STREAM-INF:BANDWIDTH=1058446,CODECS="avc1.66.31,mp4a.40.2",RESOLUTION=720x432

**Comment by lewixlabs** [comment]
Ok thank you @mike-rowley 
yes i noticed metadata inside m3u file, i will parse them.
But I think issue about wrong aspect radio in portrait mode esists (in UWP issue is not present, aspect ratio is ok)

**Comment by mike-rowley** [comment]
Yes, it is a known issue on Android.

**Comment by DumoulinLander** [comment]
Any possibility of this issue getting fixed anytime soon?

**Comment by adrianknight89** [comment]
Looks like [SimpleExoPlayerView](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/ui/SimpleExoPlayerView.html) has a method called [setResizeMode](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/ui/PlayerView.html#setResizeMode-int-) that we could possibly leverage?
