### ISSUE TITLE
Can't set Android notification icon from Xamarin.Forms

### ISSUE THREAD

**Issue by rob-burrus** [martijn00/XamarinMediaManager#306]
When MediaFile.MetadataExtracted = true, the Title, Artist, and Album fields are correctly reflected in the Android notification. But the notification icon doesn't seem to be settable? Art and AlbumArt don't work. What is the appropriate field with which to set the Android notification icon from Xamarin.Forms? I would prefer to not fall back on the App icon. Note: Using Android.Support.* version 25.4.0.2. Is this version not fully supported?

**Comment by rob-burrus** [comment]
Another note about the Android notification: The "Play" button appears below the Title / Artist and is cutoff in the notification. But it seems like there is plenty of room for it on the right side of the notification.  Assuming this has something to do with lack of support for version 25.4.0.2?

**Comment by mike-rowley** [comment]
I am not sure if IAndroidMediaNotificationManager and its collateral code is in the 0.45 release, if not pull the develop branch and build your own version until it is.
Take a look at this pull request, it explains how to implement your own Android Notification class, this will allow you to customize your own Notifications in any way you like, including moving the play icon to the right.  This is not done in the base code as there are actually 3 buttons that can be rendered in the notification, previous, play or next.

**Comment by Finneyv** [comment]
Hey I ran into this issue myself and the link to the pull request is dead.  Is there any way to fix this issue by overriding IMediaNotificationManager instead of pulling and building the entire MediaManager project?

**Comment by martijn00** [comment]
Hopefully I can get a new release out in a month or so. The work for this is being done on the vNext branch, and you are welcome to contribute!

**Comment by martijn00** [comment]
New api for it soon available: `CrossMediaManager.Android.NotificationIconResource = Resource.Drawable.youricon;`
