### ISSUE TITLE
is there any option to add custom notification controls in Xamarin media manager plugin?

### ISSUE THREAD

**Issue by ijaz321** [martijn00/XamarinMediaManager#308]
I am using Xamarin plugin Media Manager version 0.4.3 on a live audio streaming it is working properly only thing i want to know is how to manage notification controls for example in notification window it is by default showing previous play/pause and next button but in my case i only need play/pause button. is there any option to hide or remove unnecessary buttons from notification window in Android?

**Comment by mike-rowley** [comment]
I don't believe it is within the 0.45 nuget release but this PR covers the implementation of a fully customization MediaNotification class.

https://github.com/martijn00/XamarinMediaManager/pull/277

**Comment by D4rkF4ce** [comment]
is there an example how to hide next/previous buttons in audio lockscreen notification?
Many thx

**Comment by martijn00** [comment]
@D4rkF4ce You can access it here on Android: https://github.com/Baseflow/XamarinMediaManager/blob/develop/MediaManager/Platforms/Android/Notifications/NotificationManager.cs#L16

**Comment by D4rkF4ce** [comment]
@martijn00 Thank you very much, I just implemeted it, it works if I define the UseStopAction and I have to set the next/previous -Seek Millisecs to 0 I also had to SetPlayer to CrossMediaManager.Android.Player :) I am using CrossMediaManager 0.9.6

But I noticed another problem yesterday. I wanted to update to the current CrossMediaManager version (1.0.1). Depending on this, the SDK must also be updated to version 29 (android 10). If I do that, the lockscreen notification doesn't go away after the player is stopped. Have there been any changes to the notifications in this regard.

**Comment by martijn00** [comment]
Yeah here: https://github.com/Baseflow/XamarinMediaManager/commit/004920cd41f42e5100b780a295508c5e76deb914#diff-744ab47974856b1e866d6b4a1c23f92fR132

**Comment by D4rkF4ce** [comment]
@martijn00 Aha ok thank you very much. Can I simply stop the notification in the Stop -StateChanged from the CrossMediaManager? - I cannot find a way to clear the Lockscreen Notification. Its still running while player is stopped.

**Comment by fnandocontreras** [comment]
Hello, is there a way to disable step back/forward buttons from notification area player? 
I only find these 2 options:
CrossMediaManager.Current.Notification.ShowNavigationControls = false;
CrossMediaManager.Current.Notification.ShowPlayPauseControls = false;
What about step buttons?
thanks

**Comment by bhartigarde08** [comment]
@fnandocontreras 
We can hide the step buttons using:
CrossMediaManager.Current.StepSize = TimeSpan.FromSeconds(0);

Hope this will help!
Thanks!

**Comment by dawitalemu** [comment]
> CrossMediaManager.Current.Notification.ShowNavigationControls = false;
> CrossMediaManager.Current.Notification.ShowPlayPauseControls = false;
@fnandocontreras 
Where do I put these method calls? If I put them right before a call to await CrossMediaManager.Current.Play(mediaItem) nothing seems to change.

**Comment by fnandocontreras** [comment]
@dawitalemu you need to put them before `CrossMediaManager.Current.Init();` in App.xaml.cs inside App class constructor
`
CrossMediaManager.Current.Notification.ShowNavigationControls = false;
CrossMediaManager.Current.StepSize = TimeSpan.Zero;
CrossMediaManager.Current.MediaPlayer.ShowPlaybackControls = false;
CrossMediaManager.Current.Init();
`

**Comment by dawitalemu** [comment]
> @dawitalemu you need to put them before `CrossMediaManager.Current.Init();` in App.xaml.cs file inside App class constructor
> 
> ```
> CrossMediaManager.Current.Notification.ShowNavigationControls = false;
> CrossMediaManager.Current.StepSize = TimeSpan.Zero;
> CrossMediaManager.Current.MediaPlayer.ShowPlaybackControls = false;
> CrossMediaManager.Current.Init();
> ```

Thanks @fnandocontreras , but does that mean we cannot change notification properties during the lifetime of an app for example? Or can we call the init() as many times as we need to?

**Comment by VictorMuwaya** [comment]
What about setting the icon for notification playback
