### ISSUE TITLE
Error when use this library with .net standard 2.0 ?

### ISSUE THREAD

**Issue by jerryno6** [martijn00/XamarinMediaManager#311]
In xamarin forms, I replaced PCL project by .net standard 2.0 project
After that, in nuget Manager I couldn't add xamarinMediamanager to project .net standard, it gave me an error  "The given key was not present in the dictionary." 

I don't know how to fix this.

**Comment by mike-rowley** [comment]
We are presently working on the NetStandard 2.0 changes and are hoping to put them out in the 1.0 release for the library.  NetStandard 2.0 is not currently supported.

**Comment by jerryno6** [comment]
**Love you.**

When will we have the release for 1.0
And do we have timeline for 2.0 ? 
about 3 or 6 months ?

**Comment by mike-rowley** [comment]
1.0 of XamarinMediaManager is intended to support NetStandard 2.0 and a few other things outlined in this issue: https://github.com/martijn00/XamarinMediaManager/issues/272

We're going to get it out as soon as possible but its hard to give a timeline.

**Comment by adrianknight89** [comment]
@mike-rowley Any update on the 1.0 timeline? @jerryno6 It's been 6 months already. :)

**Comment by martijn00** [comment]
There is some code for .netstandard merged into develop, but i don't have time to fix up the missing pieces, or the other feature requests right now. I'm available for hire to fix this up and integrate changes into your project if you or anyone else wants. Drop me an email or message and we can talk about it.

**Comment by jerryno6** [comment]
Hi martjijn,
I respect what you have done on this project.I want to join this project to help you fixing this. But I've got an offer from a company, I still not have enough time to join. When I'm ready, I hope I could give you a hand.

Sent from Yahoo Mail on Android 
 
  On Fri, May 18, 2018 at 22:54, Martijn van Dijk<notifications@github.com> wrote:   
There is some code for .netstandard merged into develop, but i don't have time to fix up the missing pieces, or the other feature requests right now. I'm available for hire to fix this up and integrate changes into your project if you or anyone else wants. Drop me an email or message and we can talk about it.
