### ISSUE TITLE
Play video shows me video with 90 degree tilted

### ISSUE THREAD

**Issue by gokuldasc** [martijn00/XamarinMediaManager#312]
Hi,
I am recording a video and then playing back.  I am using customVideorender to record video using native VideoView and Media Recorder.
Recorder was showing  pictures with 90 degree rotation. So I used the below code which corrected the rotation. I had to set display orientation for Camera to 90. 
But now while playing video  it was not playing correctly so I had to use async and await while using 
await CrossMedia.Current.Play(videourl,MediaFiles.Video); Now it plays video but it shows the video with 90 degree rotation. How do I correct this? 
Please advise 
Regards,
Gokul

  video.StopPlayback();
                    recorder = new MediaRecorder();
                    var mCamera = GetCameraInstance();
                    if(mCamera == null)
                    {
                        throw new Exception("Can't open Camera!");

                    }
                    mCamera.SetDisplayOrientation(90);
                    mCamera.Unlock();
                    recorder.SetCamera(mCamera);
                    recorder.SetVideoSource(VideoSource.Camera);
                    recorder.SetAudioSource(AudioSource.Mic);
                    recorder.SetOutputFormat(OutputFormat.Default);
                    recorder.SetVideoEncoder(VideoEncoder.Default);
                    recorder.SetAudioEncoder(AudioEncoder.Default);
                    recorder.SetOutputFile(mainPath);
                    recorder.SetPreviewDisplay(video.Holder.Surface);
             
                    recorder.Prepare();
                    recorder.Start();

**Comment by mike-rowley** [comment]
If the video is playing back rotated 90 degrees, why not change this line
mCamera.SetDisplayOrientation(90);
to
mCamera.SetDisplayOrientation(0);

**Comment by gokuldasc** [comment]
Hi Mike thanks for your reply. But I am using  MediaManager plug to play the video  using 
CrossMedia.Current.Play( videoUrl,MediaFiles.Video) and I can't see any property to  access the Camera to set the orientation to zero.
Regards,
Gokul

**Comment by mike-rowley** [comment]
I repeat my original question.

If the video is playing back rotated 90 degrees, why not change this line
mCamera.SetDisplayOrientation(90);
to
mCamera.SetDisplayOrientation(0);
Which should then record it at 0 orientation as the VideoView would play back at 0 orientation.

**Comment by gokuldasc** [comment]
Hi Mike,
I had to set orientation to 90 degree because camera was recording with 90 degree tilt  when I try to record it in Portrait mode. I want both record and play to work correctly and not one or the other.

**Comment by mike-rowley** [comment]
I would suggest figuring out why the camera is not recording with the correct rotation in portrait mode.   That sounds like the root cause of the video being rotated in the VideoView on playback.

**Comment by jadenrogers** [comment]
For anyone else with this make sure you set the orientation on the video output when setting up your recording.

For me writing to a file it looks something like

AVCaptureConnection connection = ( AVCaptureConnection ) _movieFileOutput.Connections[ 0 ];
connection.VideoOrientation = AVCaptureVideoOrientation.LandscapeRight;

@gokuldasc
