### ISSUE TITLE
Cannot Play Itunes Library

### ISSUE THREAD

**Issue by shahansyed** [martijn00/XamarinMediaManager#316]
I can play audio in IOS thats hosted in google drive, but i cannot get IOS to play a file that is loaded in the Itunes Library 

 **MPMediaQuery mq = new MPMediaQuery();
                var value = NSNumber.FromInt32((int)MPMediaType.Music);
                var type = MPMediaItem.MediaTypeProperty;
                var predicate = MPMediaPropertyPredicate.PredicateWithValue(value, type);
                mq.AddFilterPredicate(predicate);

                var collecttions = mq.Collections;
                NSUrl url = null;

                List<string[]> songs = new List<string[]>();
                foreach(var a in collecttions)
                {
                    if(a.Items[0].AssetURL != null)
                    {
                        songs.Add(new[] { a.Items[0].Title.ToString(), a.Items[0].AssetURL.ToString() });
                        url = a.Items[0].AssetURL;
                    }
            
                }
                CrossMediaManager.Current.Play(url.ToString());**

I get this error 

**-[AVAsset loadValuesAsynchronouslyForKeys:completionHandler:] invoked with unrecognized keys (
    title,
    artwork,
    artist
)**

When i try this 

   **var player = new AVAudioPlayer(url, "mp3", out err);
   player.Play();**

I get this error

System.Exception: Could not initialize an instance of the type 'AVFoundation.AVAudioPlayer': the native 'initWithContentsOfURL:fileTypeHint:error:' method returned nil.
It is possible to ignore this condition by setting MonoTouch.ObjCRuntime.Class.ThrowOnInitFailure to false.
  at Foundation.NSObject.InitializeHandle (System.IntPtr handle, System.String initSelector) [0x00094] in /Users/builder/data/lanes/5520/51128b8c/source/xamarin-macios/src/Foundation/NSObject2.cs:465 
  at AVFoundation.AVAudioPlayer..ctor (Foundation.NSUrl url, System.String fileTypeHint, Foundation.NSError& outError) [0x0003a] in /Users/builder/data/lanes/5520/51128b8c/source/xamarin-macios/src/build/ios/native/AVFoundation/AVAudioPlayer.g.cs:133 
  at RhymeBook.iOS.PlatformSpecific.MusicHelper.GetFile () [0x000c3] in C:\Users\ssyed.IDEA-ESOLUTIONS\source\repos\RhymeBook\RhymeBook\RhymeBook.iOS\PlatformSpecific\MusicHelper.cs:39

**Comment by mike-rowley** [comment]
First I need to know how to get an "iTunes Library URL"

**Comment by shahansyed** [comment]
Sorry !  this works , I wasnt working because i was forcing the music in the simulator like this  : https://maikohermans.github.io/2016/12/28/ios-use-music-library-with-simulator
but it didnt work. It works with the real device i just got. 

For anyone who wants to know heres the bit of code that queries the devices itunes library 

```
var value = NSNumber.FromInt32((int)MPMediaType.Music);
var type = MPMediaItem.MediaTypeProperty;
var predicate = MPMediaPropertyPredicate.PredicateWithValue(value, type);
mq.AddFilterPredicate(predicate);
var collecttions = mq.Collections;

NSUrl url = collecttions[0].Items[0].AssetURL

CrossMediaManager.Current.Play(url.ToString())
```

Thanks for all your hard work !
