### ISSUE TITLE
Plugin.MediaManager.ExoPlayer.GetSource() uses FileDataSourceFactory for http/https urls

### ISSUE THREAD

**Issue by ArthurDumas** [martijn00/XamarinMediaManager#318]
Plugin.MediaManager.ExoPlayer.GetSource() uses FileDataSourceFactory for http/https urls instead of HttpSourceFactory. This is caused because the encoded url ("http%3A%2F%2F") is passed to URLUtil.IsHttpUrl() which looks for "http://" (likewise for https).

This issue was discussed here https://github.com/martijn00/XamarinMediaManager/issues/212 and here https://github.com/martijn00/XamarinMediaManager/pull/213.

**Comment by ArthurDumas** [comment]
While trying to fix ExoPlayer.GetSource(), I ran into a problem.

To test, I modified XamarinMediaManager-develop\Samples\Forms\Droid to use ExoPlayer by adding a reference to Plugin.MediaManager.ExoPlayer and adding the following code to MainActivity.cs:
```
            Plugin.MediaManager.MediaManagerImplementation current
                = Plugin.MediaManager.CrossMediaManager.Current as Plugin.MediaManager.MediaManagerImplementation;

            var exoPlayer
                = new Plugin.MediaManager.ExoPlayer.ExoPlayerAudioImplementation(current.MediaSessionManager);

            Plugin.MediaManager.CrossMediaManager.Current.AudioPlayer
                = exoPlayer;
```

The audio plays but the app throws the following exception and aborts once you acknowledge the exception in Visual Studio.
```
System.NotSupportedException: Unable to activate instance of type Com.Google.Android.Exoplayer2.Trackselection.TrackSelections from native handle 0xbec40210 (key_handle 0x724232c).
```
**Am I missing some other references?**

**Comment by mike-rowley** [comment]
ExoPlayer 2 is being added for the v1.0 release.  I believe only ExoPlayer 1 is partially supported currently.

**Comment by ThaineNorris** [comment]
We will have a new release of our app in March. Is there any hope that the ExoPlayer 2 code you talk about will be released before then?
