### ISSUE TITLE
MediaNotificationManager on Android appears again after I try to close it

### ISSUE THREAD

**Issue by VVK1993** [martijn00/XamarinMediaManager#319]
Hello guys,

Sorry if it is a silly question but I tried to find a solution online or solve it by myself but nothing works for me.

The problem is that when my audio file (audio streaming) has finished playing notification control won't disappear. 

I tried calling this code 

```
            if (CrossMediaManager.Current.MediaNotificationManager != null)
            {
                CrossMediaManager.Current.MediaNotificationManager.StopNotifications();
            }
```
or this: 

```
            CrossMediaManager.Current.MediaQueue.Remove(e.File);
            CrossMediaManager.Current.PlaybackController.Stop();
```
but after this Notification control disappears and briefly after it appears again. Don't know how to get rid of it. Or is there a way to disable notification manager completely?

**Comment by VVK1993** [comment]
I found that after media file is finished I get this in output

> 11-26 15:26:57.348 E/MediaPlayer( 4266): error (-38, 0)
> 11-26 15:26:57.349 E/MediaPlayer( 4266): Attempt to call getDuration without a valid mediaplayer
> 11-26 15:26:57.349 E/MediaPlayer( 4266): Attempt to call getDuration without a valid mediaplayer
> 11-26 15:26:57.444 E/MediaPlayer( 4266): Attempt to perform seekTo in wrong state: mPlayer=0x0, mCurrentState=0
> 11-26 15:26:57.523 E/MediaPlayer( 4266): Error (-38,0)

I don't call any getDuration or seekTo methods directly. Any ideas why it is happening?

**Comment by mike-rowley** [comment]
StopNotifications stop the notification bar until it is accessed again, then if you look at the code, it will reinitialize the Notification.  I had exactly the same issue, I compiled my app with a copy of the code and put a breakpoint on StartNotification and found it was being accessed on a separate thread after my app stopped playing.

If you have a slimmed down sample project reproducing the problem I will have a look at it.

**Comment by SamTheDev** [comment]
So, is there a way to close the Notification bar entirely ?
