### ISSUE TITLE
What's the aim of this package? Minimal corss-platform playing or full-fledged media player?

### ISSUE THREAD

**Issue by SimonSimCity** [martijn00/XamarinMediaManager#32]
Since I've now adjusted much on the `MediaQueue` and am also planing on integrating some stuff like soft-fadeout and jumping to start if the user presses "previous" after he played more than 4sec, I am asking myself: What is the primary goal of this library?

Is it to have a minimal playing instance, or is it to provide a package, that contains all needed to implement a full-fledged feature-loaded media player?

Is f.e. #8 still within the range of this package, or is it more just simply playing items - without any additional work for features a user would expect from a media player?

Should this may be divided into two packages, where one of them just cares about playing cross-platform and the other one focuses on the media player like features?

We could also say, that we aim for the full-fledged implementation and users, who like tiny app-sizes can rely on the linker (https://developer.xamarin.com/guides/ios/advanced_topics/linker/) to shrink the size of the app again. But - in another way - code isn't that large in size, isn't it? It's most likely to be resources that blow up the app-size ...

**Comment by martijn00** [comment]
My aim is to provide a full, but very flexible media playing library. I am looking at a way to interface the Notification and Remote control parts, so users can decide if they want to use that or not.

It should at some point also be possible to play video with this library, and switch out the actual mediaplayer with something like ExoPlayer. This should be doable by providing the correct interfaces.

The linker works on class level, so it doesn't really matter if the library contains things like a Queue. If you don't use it, it will be stripped away.

**Comment by SimonSimCity** [comment]
So I'll keep pushing the features I implement in the app I am moderating and maybe - at some extend - add a configuration-interface where the user can configure, enable or switch off functionality like cross-fading, soft-fadeout, error-messages, back-to-start etc.
