### ISSUE TITLE
iOS first pause works like stop

### ISSUE THREAD

**Issue by madner7** [martijn00/XamarinMediaManager#320]
I have used the plugin to write a forms application for podcasts. As there is some custom logic involved, I clear the Queue and repopulate it based on some events.

When playing I use this
`mediaPlayer.MediaQueue.SetIndexAsCurrent(0);
mediaPlayer.PlaybackController.Play();`

It plays the proper file and that works great.
However the first time pause and then play is hit, it reloads the file and starts playing from start. After that it is working perfectly fine.

`if (Status == MediaPlayerStatus.Paused || Status == MediaPlayerStatus.Stopped)
            {
                
                await mediaPlayer.PlaybackController.Play();
              
            }
            else if (Status == MediaPlayerStatus.Playing)
            {
                
                await mediaPlayer.PlaybackController.Pause();
            }`

Any ideas would be most welcome.

**Comment by mike-rowley** [comment]
Because of your "custom logic" I can't even begin to speculate as to what your problem might be.  If you would like to put together a slimmed down sample outlining the problem I will have a look at it.

**Comment by ZeProgFactory** [comment]
I've the same issue on UWP. I'll try to make up a sample project.

**Comment by Falco20019** [comment]
On android it's restarting the song.

On android, this could be related to my fix in #314 which calls PrepareAsync even for the same file. But if it's not called, the player is getting completely stuck and won't play the same song until another was played. Just informational, shouldn't be the same cause as on iOS or UWP since I haven't touched those.

**Comment by madner7** [comment]
I will try to create .a skeleton project to demonstrate the issue. 

Thanks.

**Comment by madner7** [comment]
Fixed the issue for iOS by changing the logic for 

sameMediaFile in AudioPlayerImplementation, first time on new screen the equals was returning false.
