### ISSUE TITLE
Disable previous and next button

### ISSUE THREAD

**Issue by Doxoh** [martijn00/XamarinMediaManager#321]
Hello,
I want to disable the previous and the next button with this:
`
            commandCenter = MPRemoteCommandCenter.Shared;

            commandCenter.NextTrackCommand.Enabled = false;
            commandCenter.PreviousTrackCommand.Enabled = false;`

But it does not worked. Anybody know why?

**Comment by martijn00** [comment]
commandCenter was not used like that in the past. Try again with 0.5.9
