### ISSUE TITLE
How to detect when streaming connection gets cut off on Android

### ISSUE THREAD

**Issue by Finneyv** [martijn00/XamarinMediaManager#324]
When streaming audio on an android device if the stream connection is cut off the player eventually changes its status to loading then switches it back to playing.  The only indication that the player gives that it has lost it's data stream is the quick transfer from playing to loading and then back to playing.  It does not throw a MediaFailed event nor does it change it's Status to Failed.  How should I best handle this scenario and how should I set up the player to recover from a loss of internet connectivity while streaming?

**Comment by mike-rowley** [comment]
I don't think there is anything in MediaPlayer that will detect the stream failure, but i believe this functionality is available in ExoPlayer 2+ and will be added in the V1.0 release we are working on.

**Comment by Finneyv** [comment]
OK.  Currently I check to see if the player is loading and if the device doesn't have a connection to throw the warning.  I'll be sure to integrate the newest MediaPlayer release into my project as soon as it becomes available.

**Comment by mike-rowley** [comment]
Just as clarification, MediaPlayer refers to the underlying Android system for playing media, ExoPlayer is its replacement which has more transport layer information that should allow detection and retries on a connection glitch.

**Comment by Finneyv** [comment]
Oh sorry for the mix up then.  I'm using CrossMediaManager with ExoPlayer currently and in my previous post I meant to say the CrossMediaManager object.
