### ISSUE TITLE
Play FairPlay Protected HLS Content

### ISSUE THREAD

**Issue by Lezherus** [martijn00/XamarinMediaManager#329]
Hey guys, I'm trying to stream a content from Azure Media Services, but I can't get it to work, so I'm wondering if it's doable, and if so, how do I achieve it? The content is HSL protected by FairPlay DRM.

**Comment by mike-rowley** [comment]
I believe HSL protection requires an ExoPlayer2 implementation which is not yet in the plugin.

**Comment by martijn00** [comment]
This should be possible now. See https://github.com/martijn00/XamarinMediaManager#play-a-non-standard-format-like-hls-dash-or-ss
