### ISSUE TITLE
Android TimeSpan objects like 'Position' or 'Duration' retrieve wrong info.

### ISSUE THREAD

**Issue by NicoKno** [martijn00/XamarinMediaManager#331]
I'm playing a mp4 Video (tried with several). It seems like each second gets multiplied by 1000. Doesnt matter if I get the TotalSeconds or the TimeSpan itself. The numbers are way too high.

**Comment by CSkoubo** [comment]
Got any repro steps or project? Seems a bit of an big effort to setup, to find the bug, if there are any at all.

**Comment by NicoKno** [comment]
You can use the Xamarin.Forms Sample App. If you set a break point to PlayingChanged Event you can have a look at the e.Position.TotalSeconds Property.

**Comment by NicoKno** [comment]
I think I found the issue and created a pull request. #334

**Comment by toverux** [comment]
Found the issue after having encountered the very same problem.

As a workaround, I'm doing this:

```c#
.Select(@event => TimeSpan.FromSeconds(@event.Duration.TotalSeconds / 1000))
```

Thanks for the PR @NicoKno, I hope it could be merged quickly.

**Comment by stefan89** [comment]
I am having the exact same issue for Android

**Comment by toverux** [comment]
The PR has been merged, wait for the next release ;)

**Comment by mhdshbk** [comment]
Can I please know when will be the next release?
Because, I'm getting crazy values for `e.Duration.ToString(@"mm\:ss")` & `e.Position.ToString(@"mm\:ss")`
Or any simple workaround to use these?

Thanks in advance! :)

**Comment by CSkoubo** [comment]
You can make a nuget yourself if you run the cake script :)

**Comment by toverux** [comment]
@mhdshbk You should read the thread... I proposed a workaround above. Take the seconds in the original event, and create a new TimeSpan with FromMilliseconds.

My current workaround:

```cs
// @todo Remove this fix when next version of XamarinMediaManager is released.
// (Workaround a MediaManager bug on Android)
// https://github.com/martijn00/XamarinMediaManager/issues/331 
TimeSpan FixTimeSpan(TimeSpan ts) =>
    Device.RuntimePlatform == Device.Android ? TimeSpan.FromMilliseconds(ts.TotalSeconds) : ts;

var mediaDurationObs = mediaTimingObs
    .Select(@event => FixTimeSpan(@event.Duration))
    .StartWith(requestedMedia.Duration);

var mediaPositionObs = mediaTimingObs
    .Select(@event => FixTimeSpan(@event.Position))
    .StartWith(TimeSpan.Zero);
```

**Comment by KenHowe2010** [comment]
Thanks for reporting this, just used to fix my App too
