### ISSUE TITLE
Any plans for .net standard support?

### ISSUE THREAD

**Issue by MagnusJohansson** [martijn00/XamarinMediaManager#333]
..as per the title.

**Comment by mike-rowley** [comment]
This is planned for the V1 release.  https://github.com/martijn00/XamarinMediaManager/issues/272

There is no time line that I am aware of for this release at this point.

**Comment by XplittR** [comment]
Is there an ETA for when we can expect a release with .NET Standard 2.0 support?

**Comment by thanhcs** [comment]
I would like to know as well... Or is there a workaround for current version to use with .net standard?

**Comment by adrianknight89** [comment]
Guys, we're all waiting for NetStandard support. Also, the proposal in #272 for making ExoPlayer the default Android player is great. Can someone update us on the roadmap? @martijn00

**Comment by martijn00** [comment]
I don't have time to fix up the missing pieces, or the other feature requests right now. I'm available for hire to fix this up and integrate changes into your project if you or anyone else wants. Drop me an email or message and we can talk about it.
