### ISSUE TITLE
Can't get the remote to preview correctly

### ISSUE THREAD

**Issue by TGlev** [martijn00/XamarinMediaManager#337]
Hi!

I'm trying to get the artist name, song name and artwork on the lock screen of iOS. This is my code:

```
var mediaFile = new MediaFile { Type = MediaFileType.Audio, Availability = ResourceAvailability.Remote, Url = App.StreamURL, MetadataExtracted = false };
mediaFile.Metadata.Title = CurrentSongTitle;
mediaFile.Metadata.Artist = CurrentSongArtist;
mediaFile.Metadata.AlbumArtUri = CurrentSongArtwork;

await CrossMediaManager.Current.Play(mediaFile);
CrossMediaManager.Current.MediaNotificationManager.StartNotification(mediaFile);
```

Where I am SURE that all three of the variables contain data and the Artwork one points to an URL with an image on it.

The problem is though, it looks like this on my lockscreen:
[Link to Image](https://gyazo.com/0295e6f229b3641621e6478133b9af49)

As you can see, only the artist's name works. Am I doing something wrong?

**Comment by mike-rowley** [comment]
Have you looked at the sample code?

**Comment by TGlev** [comment]
Yes, I have. @mike-rowley 

I found another issue regarding the image artwork.(Just waiting for the update)

But the Title of the song is not displaying correctly either. It's still the same as in the picture above, even when I use the EXACT same code as used in the sample code.
