### ISSUE TITLE
Playing while downloading?

### ISSUE THREAD

**Issue by VSG24** [martijn00/XamarinMediaManager#339]
I want to make an app like Spotify or Apple Music, but I want it to also work offline. So I need to cache files but I don't want to wait for full download completion. Is it possible to do it with your lib?

**Comment by mike-rowley** [comment]
I don't think that is possible with MediaPlayer on Android therefore is not implemented in the current version of XMM.  It should be possible when we move to exoplayer v2.

**Comment by martijn00** [comment]
You could add it through exoplayer now
