### ISSUE TITLE
Live stream suggestion

### ISSUE THREAD

**Issue by CSkoubo** [martijn00/XamarinMediaManager#342]
I intend to use the plugin for live streaming of video and music. But now that i've gotten a bit more knowledge of it, it seems as if its not suited for that yet. Its more oriented of non-live content. ie. i need to Stop content, and not pause it. Which is my main concern at this point.
So i was wondering if it would make sense to make it able to initialise for such use? I know it will add more complexity to it, but it would also make it useable for such purpose.

**Comment by mike-rowley** [comment]
I use the plugin to stream shoutcast streams live.  It depends on the type of "live stream" you are trying to connect as much of that functionality is only available on android through ExoPlayer2, which isn't implemented yet.
