### ISSUE TITLE
Video is dark

### ISSUE THREAD

**Issue by dmmg83** [martijn00/XamarinMediaManager#343]
Thank you for your great job @SimonSimCity @modplug @candidodmv @nickrandolph @NicoKno .

When I playback a video, the video looks very dark, how can I increase the brightness?
Xamarin Forms PCL. Android.

**Comment by dmmg83** [comment]
I solve it adding this line on mainactivity in Android project:
            this.Window.Attributes.DimAmount = 0;

**Comment by toverux** [comment]
It can also be disabled through an Android style entry:

```xml
<!-- Avoid a strange behavior: when a VideoView is created, screen has a flash of black,
     then the video playback is dim -->
<item name="android:backgroundDimEnabled">false</item>
```
