### ISSUE TITLE
Xamarin.Forms iOS repeat

### ISSUE THREAD

**Issue by Asseks** [martijn00/XamarinMediaManager#346]
I use Xamarin.Forms and add to files queue.
 I set repeat to None.

```
CrossMediaManager.Current.MediaQueue.Repeat = RepeatType.None;
//fill playlist
CrossMediaManager.Current.MediaQueue.AddRange(Playlist);
CrossMediaManager.Current.Play();
```

Android works good and playlist was stopped when playlist was played once, but iOS play doesn't stop when playlist was played once and repeat again and again.

**Comment by FreshApps** [comment]
Hi, 

I have the same problem. Did you find any solution for this ?

**Comment by dylanhares** [comment]
Having the same issue. Would debug it myself but I'm a n00b and can't figure out how to reference the platform implementations.
