### ISSUE TITLE
Xamarin.Forms Android current file progress

### ISSUE THREAD

**Issue by Asseks** [martijn00/XamarinMediaManager#348]
Progress for playing file calculates wrong on Xamarin.Forms Android. 
Maximum value should be 1 instead of 2.64 or more.

**Comment by XplittR** [comment]
> as (I hope) you can see in the graph.

I do not understand your graph. What are the axes?

![Label your axes](https://i2.wp.com/flowingdata.com/wp-content/uploads/2012/06/label-your-axes.png)

**Comment by axeira** [comment]
X real time , Y Progress time, the error increases constantly...Clear now?

**Comment by axeira** [comment]
The problem I reported is not a problem, I misinterpreted the properties.
I was using Progress instead of Position. Now it's working fine.
e.Progress=percentage 0-100
e.Position=seconds
e.Duration=seconds
