### ISSUE TITLE
A lot of XA0106 warnings for Android projects that target Oreo

### ISSUE THREAD

**Issue by runesig** [martijn00/XamarinMediaManager#353]
I am getting like 13 XA0106 warnings for Android projects that target Oreo API 26 for XamarinMediaManager.Forms

### Reproduction steps

Create a new Xamarin Android project and target latest version of Android (Oreo) 8.0. Add the XamarinMediaManager.Forms. Build the project.

### Expected outcome
No warnings.

### Actually happening
A lot of XA0106 warnings

### Your setup

Droid Oreo 8.0, latest version 0.4.5 XamarinMediaManager.Forms

**Comment by runesig** [comment]
Forgot to mention but I am using Visual Studio for Mac

**Comment by ianthetechie** [comment]
Not sure if 8.x had anything to do with it, but I have the same thing these days with 8.1. If I include the ExoPlayer package, I get 74 warnings and 2 errors.

I'm using .NET Standard FWIW.
