### ISSUE TITLE
CrossMediaManager.Current.VolumeManager Not working at all

### ISSUE THREAD

**Issue by dmmg83** [martijn00/XamarinMediaManager#354]
I am trying to control volume of video or just mute it using CrossMediaManager.Current.VolumeManager

if (CrossMediaManager.Current.VolumeManager.Mute)
                {
                    
                    CrossMediaManager.Current.VolumeManager.Mute = false;
                }
                else
                {
                    CrossMediaManager.Current.VolumeManager.Mute = true;
                }

### Expected outcome
Mute the video

### Actually happening
Nothing happening

I am using MediaPlayer 0.4.5 and running my app in android.

**Comment by TGlev** [comment]
Same as #349 that I made.

I figured out that the Volume manager is a placeholder for now, if you want it, you should download the source code and reference it that way.

[Source](https://stackoverflow.com/questions/46860915/how-to-mute-volume-on-button-clicked-in-mediamanager-plugin-xamarin-forms)
