### ISSUE TITLE
Pause the video on last frame

### ISSUE THREAD

**Issue by sskohli** [martijn00/XamarinMediaManager#361]
Hi 
When the player plays a video and finishes it goes back to the first frame. 

### Expected outcome
Can we stop it at the last frame of the video?

### Actually happening
When the player plays a video and finishes it goes back to the first frame. 

### Your setup

Which version of MediaManager are you using? 0.4.5
Which platform iOS, Droid, UWP, Xamarin.Forms? Xamarin.Forms -2.5.0

Thanks,
Sandeep

**Comment by martijn00** [comment]
You can use one of the event handlers for this. Get the current position and the duration, and then pause the player on one second from the end.
