### ISSUE TITLE
.Net Standard support

### ISSUE THREAD

**Issue by TonyHenrique** [martijn00/XamarinMediaManager#362]
Hi, I need to target Windows 10 Mobile, but XamarinMediaManager does not support .Net Standard below 2.0.

It would be good to have support on it, the lower .net standard more compatible with old devices. 
(.net standard 1.2 , or 1.4)

**Comment by martijn00** [comment]
This is in progress. I'm awaiting a fix from Microsoft.
https://github.com/martijn00/XamarinMediaManager/pull/360
