### ISSUE TITLE
Xamarin Forms, No video after using audioplayer

### ISSUE THREAD

**Issue by Neotrickster** [martijn00/XamarinMediaManager#363]
### Reproduction steps
0. The links are both live streaming, 1 for audio and 1 for video (non related):
Video: http://apreal04.triara.com:1935/redirect/canaliberoamericano1/live.mp4?scheme=m3u8
Audio: http://201.159.130.34:8080/radioilce.mp3

1. Using the samples code for mediamanager

2. If you play Video as your first action works fine.

3. if you play audio only source and then switch to video source then play action only brings audio portion of the video.

4. Since I´m learning about Xamarin Forms, I check other apps like the Hanselman one and brings same bug.

### Expected outcome
When using audio only source then video source, the video source should be reproducing audio/video part but only reproduce audio part, however, if I reproduce video first it works fine. Only happen when you reproduce audio only source first. It happen even in the samples for Xamarin Forms.

### Actually happening
The video reproduction only brings the audio component and a blank screen show.

### Your setup

Which version of MediaManager are you using? 0.4.5
Xamarin.Forms, droid project on Visual Studio 2017

**Comment by Neotrickster** [comment]
I resolved, but I probably been using in a bad way in first place.

video part is defined as:
XAML
<forms:VideoView x:Name="MyVideoView"
                    AspectMode="AspectFit"
                    WidthRequest="320"
                    HeightRequest="180"/>
CS
            MyVideoView.Source = videoUrl;
            await CrossMediaManager.Current.VideoPlayer.Play();
 
While the audio part was defined only in the CS without any reference in XAML:
             await CrossMediaManager.Current.Play(audioUrl, MediaFileType.Audio);

The only thing besides make a definition in XAML for the audio part, was changing de Media File Type to Video:
             await CrossMediaManager.Current.Play(audioUrl, MediaFileType.Video);
otherwise the same problem presents.

I hope this help someone.

**Comment by CSkoubo** [comment]
If your issue has been resolved please close it.
