### ISSUE TITLE
Next button on Android notification launch "java.io.FileNotFoundException: No content provider"

### ISSUE THREAD

**Issue by SergioZgz** [martijn00/XamarinMediaManager#366]
Reproduction steps

1. Create app on xamarin forms (lastest version) 

2. Enqueue a few remote mp3 (from http)

3. Launch Android and wait until mp3 starts, then tap on next in the notification control.

Expected outcome
Expected... next song should play

Actually happening
Actually... nothings play (you get an exception, pasted below) I think that the problem is that we are trying to resolve it as local file.

03-17 19:30:43.280 V/MediaPlayer(21159): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
03-17 19:30:43.280 V/MediaPlayer(21159): cleanDrmObj: mDrmObj=null mDrmSessionId=null
03-17 19:30:43.283 W/MediaPlayer(21159): Couldn't open http://............aaaaaaa.mp3: java.io.FileNotFoundException: No content provider: http://............aaaaaaa.mp3
03-17 19:30:43.284 D/MediaPlayer(21159): setDataSource IOException | SecurityException happend : 
03-17 19:30:43.284 D/MediaPlayer(21159): java.io.FileNotFoundException: No content provider: http://............aaaaaaa.mp3
03-17 19:30:43.284 D/MediaPlayer(21159): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1402)
03-17 19:30:43.284 D/MediaPlayer(21159): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1253)
03-17 19:30:43.284 D/MediaPlayer(21159): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1176)
03-17 19:30:43.284 D/MediaPlayer(21159): 	at android.media.MediaPlayer.attemptDataSource(MediaPlayer.java:1163)
03-17 19:30:43.284 D/MediaPlayer(21159): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1135)
03-17 19:30:43.284 D/MediaPlayer(21159): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1159)

Your setup

Which version of MediaManager are you using?
Which platform iOS, Droid, UWP, Xamarin.Forms?

I'm using:
- Xamarin forms lastest version
- My core is netstandard
- Platform Android
- MediaManager 0.4.5 from nuget (I also tested with lastest code in dev branch, but next button in notificacion makes that the same song play again, maybe the button is wrong or the queue, I dont spent time checking it sorry)

**Comment by CSkoubo** [comment]
Have you tried with ExoPlayer?

**Comment by SergioZgz** [comment]
No, I will do that and let you know if works
