### ISSUE TITLE
I don't know how to set picture to the Art from MediaFile to able show it in the MediaNotification

### ISSUE THREAD

**Issue by andresgutice** [martijn00/XamarinMediaManager#369]
Hello everyone, i have a project about Radios, so i need to put the picture each radio when this ones are playing,  for example: i have a ViewModel called RadioViewModel, so when i want to put all its parameters into a MediaFile, this one stays that way:

`var mediaFile = new MediaFile
            {
                Type = MediaFileType.Audio,
                Availability = ResourceAvailability.Remote,
                Url = this.RadioUrl,
                Metadata = new MediaFileMetadata()
                {
                    Title = this.RadioName,
                    Artist = this.RadioFrecuency,                    
                    Album = this.RadioCity,
                    Art = this.RadioPicture
                },
                MetadataExtracted = true
            };`

So the property RadioPicture is a string that it's the name of picture "radio2.png", that it's in the drawable folder Android.

i've been watching the code implementation about MediaNotificationManager in Android, and the porperty Art is where able shows the LargeIcon

` private void SetMetadata(IMediaFile mediaFile)
        {
            _builder.SetContentTitle(mediaFile?.Metadata?.Title ?? string.Empty);
            _builder.SetContentText(mediaFile?.Metadata?.Artist ?? string.Empty);
            _builder.SetContentInfo(mediaFile?.Metadata?.Album ?? string.Empty);
            _builder.SetLargeIcon(mediaFile?.Metadata?.Art as Bitmap);
}`

So how coud i do to that _builder.SetLargeIcon(mediaFile?.Metadata?.Art as Bitmap) can to recognize the file from drawable folder or any project folder?

Sorry for my English, i hope you can help me :)

Thanks...

**Comment by CSkoubo** [comment]
As you already saw it is expecting a Bitmap on Android, on iOS it can take a URL and handle on its own.

To make this work i implemented my own version of MediaNotificationManager and handle the art in the class.

`private CancellationTokenSource cancellationTokenSource = new CancellationTokenSource();

		private void SetMetadata(IMediaFile mediaFile)
		{
			_builder.SetContentTitle(mediaFile?.Metadata?.Title ?? string.Empty);
			_builder.SetContentText(mediaFile?.Metadata?.Artist ?? string.Empty);
			_builder.SetContentInfo(mediaFile?.Metadata?.Album ?? string.Empty);
			_builder.SetLargeIcon(mediaFile?.Metadata?.Art as Bitmap);

			if (!cancellationTokenSource.IsCancellationRequested)
				cancellationTokenSource.Cancel();

			cancellationTokenSource = new CancellationTokenSource();
			try
			{
				Task.Run(() => FetchBitmap(mediaFile?.Metadata?.ArtUri, cancellationTokenSource.Token), cancellationTokenSource.Token);
			}
			catch (Exception e)
			{
				//TODO: currently just swallowing nasty exceptions. Should be logged and handled upon.
				Console.WriteLine(e.Message);
			}
		}

		private async Task FetchBitmap(string uri, CancellationToken token)
		{
			if (string.IsNullOrEmpty(uri))
				return;

			Bitmap bm;
			if (uri.EndsWith(".svg", StringComparison.CurrentCulture))
				bm = BitmapFactory.DecodeResource(_applicationContext.Resources, Resource.Drawable.ic_launcher);
			else
			{
				var bmd = await ImageService.Instance.LoadUrl(uri).AsBitmapDrawableAsync();
				bm = bmd.Bitmap;
			}

			if (token.IsCancellationRequested)
				return;
			Xamarin.Forms.Device.BeginInvokeOnMainThread(() => { _builder.SetLargeIcon(bm); NotificationManagerCompat.From(_applicationContext).Notify(_notificationId, _builder.Build()); });
		}`

Now that i look at it again, i might want to improve it a bit :) but it works for now.

**Comment by andresgutice** [comment]
Hello @CSkoubo, Thanks for your answer

So XamarinMediaManager has this property:
CrossMediaManager.Current.MediaNotificationManager

My question is, how could i to implementmy own version of MediaNotificationManager using the nuget XamarinMediaManager?

do i need necessary implement all the files of the nuget or can i make my own MediaNotificationManage using the nuget files?

Thanks...

**Comment by andresgutice** [comment]
@CSkoubo ok my friends, i've been reading about PR#277 and i could find the solution

Thanks for your time :)
