### ISSUE TITLE
Xamarin Forms Android and IOS video not playing in .Net Standard

### ISSUE THREAD

**Issue by sktdeepak** [martijn00/XamarinMediaManager#373]
Xamarin Forms Android and IOS video not playing in .Net Standard  but in UWP its played, i tried with emulator and device both are showing black screen

PLease help me to resolve this.. in UWP it was working perfectly without any issue...

Thanks in advance.

**Comment by Neotrickster** [comment]
The only time I got that issue was when I did not initialized the MediaManager in the MainActivity in android.
