### ISSUE TITLE
How to plat embedded resource in android 

### ISSUE THREAD

**Issue by antonioreyna** [martijn00/XamarinMediaManager#374]
hello, i added a resource in my project but im not able to play it on android, on ios i was able to get the path using NSBundle but what should i do in android?

**Comment by theD99** [comment]
After playing around a lot with audio files as embedded resources, this eventually worked well for me:
```
MediaFile sampleFile = new MediaFile(Android.Net.Uri.Parse($"android.resource://{Android.App.Application.Context.PackageName}/" + Resource.Raw.AudioSample).ToString()) { Type = MediaFileType.Audio };
await CrossMediaManager.Current.Play(sampleFile);
```
