### ISSUE TITLE
Unable to play mp3 file on android, works well on IOS.

### ISSUE THREAD

**Issue by ganeshrb83** [martijn00/XamarinMediaManager#376]
Hi Martin,

Thanks for the wonderful plugin, makes life easier. I have been able to play mp3 files without issues on IOS, but it can't play on Android and I'm unable to figure out the reason.

Error I get on Android:
Unhandled Exception:

Java.Lang.ClassNotFoundException: Didn't find class "md5cb45d68da0a4a063a9a2b86b6adab38d.VideoPlayerImplementation" on path: DexPathList[[zip file "/data/app/com.nilanga.mobileapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.nilanga.mobileapp-1/lib/arm, /vendor/lib, /system/lib]]

My Code:

await CrossMediaManager.Current.Play(new MediaFile("android.resource://com.nilanga.mobileapp/raw/beep", MediaFileType.Audio, ResourceAvailability.Local));

where beep has been placed in the resources/raw directory. I added the beep.mp3 file without its extension. I have also set the copy to output property as true.

My "build"
Xamarin.Android packages 25.4.0.2
Xamarin Forms"2.5.0.122203"
MediaManager and Xamarin Media Manager 0.4.5

On IOS -Everything work Fine!

Please help!! 

Cheers

**Comment by theD99** [comment]
This worked for me:
```
MediaFile sampleFile = new MediaFile(Android.Net.Uri.Parse($"android.resource://{Android.App.Application.Context.PackageName}/" + Resource.Raw.AudioSample).ToString()) { Type = MediaFileType.Audio };
await _player.MediaManager.Play(sampleFile);
```
My troubles came from the package name not quite being correct, but I also suspect you might not need the "/raw/" in your file path.

**Comment by gnataraj-baseplan** [comment]
Can you please let me know if you are using a dependency service and running this on the Android project?

I am just running this code directly using PCL and it works on IOS but not on Android. Is the only way of getting this to run is by having the code on the Android project?

`if (Device.RuntimePlatform == Device.iOS)
            {
                await CrossMediaManager.Current.Play("beep.mp3", MediaFileType.Audio, ResourceAvailability.Local);
            }
            if (Device.RuntimePlatform == Device.Android)
            {

                //await CrossMediaManager.Current.Play("android.resource://com.nilanga.mobileapp/raw/beep", MediaFileType.Audio, ResourceAvailability.Local);
                await CrossMediaManager.Current.Play(new MediaFile("android.resource://com.nilanga.mobileapp/raw/beep", MediaFileType.Audio, ResourceAvailability.Local));

            }`

**Comment by CSkoubo** [comment]
Yes you would have to make something like that to make it work. We are looking into making it easier in the next release probably.

**Comment by martijn00** [comment]
I don't have time to fix up the missing pieces, or the other feature requests right now. I'm available for hire to fix this up and integrate changes into your project if you or anyone else wants. Drop me an email or message and we can talk about it.
