### ISSUE TITLE
The develop branch cannot be built

### ISSUE THREAD

**Issue by jessejiang0214** [martijn00/XamarinMediaManager#385]
### Steps to reproduce :scroll:

1.Clone the repo

2.Build with VS

### Expected behavior :thinking:
It should be built with Cake script or VS

### Actual behavior :bug:
I tried to build in Cake, VS in Windows and VS for Mac. All of them are failed. I have PR want to submit, but I cannot build in develop, so I do some change in Master.

### Configuration :wrench:

**Version:** 2.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
I don't have time to fix up the missing pieces, or the other feature requests right now. I'm available for hire to fix this up and integrate changes into your project if you or anyone else wants. Drop me an email or message and we can talk about it.

**Comment by adrianknight89** [comment]
`master` is 120 commits behind `develop`. It'd be nice if a working version of `develop` was published so we can submit PRs atop most recent code. @jessejiang0214 Can you work off of `master` for now?

**Comment by jessejiang0214** [comment]
@adrianknight89 , I can do that, but I find the files were moving to another folder. So if you merge develop back to master, maybe these changes will be lost.

**Comment by thomcuddihy** [comment]
@jessejiang0214 I refactored the develop branch to get it to compile to DLLs within VS for one of my projects. It's here if you want to have a look at how I did it: https://github.com/thomcuddihy/XamarinMediaManager/

This was solely for my own project, and only has the platforms that I'm interested in (Android and iOS). I'm not sure if the project owner @martijn00 would be interested in a PR for this, but you may find it handy for developing.
