### ISSUE TITLE
progressbar Xamarin Forms

### ISSUE THREAD

**Issue by nazati** [martijn00/XamarinMediaManager#386]
progress bar no longer moves after updating Xamarin.Forms and Xamarin.Android, e.Progress is in trouble friends?

**Comment by jaybaldwin** [comment]
Confirmed, the following code:

```
 instanceIMediaManager.PlayingChanged += (object s, PlayingChangedEventArgs e) =>
    {
        Debug.WriteLine($"PlayingChanged Position: {e.Position.TotalSeconds}  Duration: {e.Duration.TotalSeconds}  Progress: {e.Progress * 100.0}");
    };
```

... returns this (while the audio plays): 

```
[0:] STATUS CHANGED.  NEW STATUS: Playing
[0:] PlayingChanged Position: 0  Duration: 0  Progress: 0
[0:] PlayingChanged Position: 0  Duration: 0  Progress: 0
[0:] PlayingChanged Position: 0  Duration: 0  Progress: 0
[0:] PlayingChanged Position: 0  Duration: 0  Progress: 0
[0:] PlayingChanged Position: 0  Duration: 0  Progress: 0
[0:] PlayingChanged Position: 0  Duration: 0  Progress: 0
[0:] PlayingChanged Position: 0  Duration: 0  Progress: 0
```

Plugin.MediaManager.Forms 0.4.5 from nuget.
Xamarin.Forms 3.0.0.482510.
Works successfully on iOS.

**Comment by MasKhan20** [comment]
Has this issue been fixed yet?

**Comment by nuc134r** [comment]
Confirmed.

Xamarin.Forms 3.0.0.561731
Plugin.MediaManager 0.4.5 (NuGet)

**Comment by devrcc** [comment]
I have the same issue, my solution was downgrading the Android Nuget packages to the version 25.4.0.2

Tested with NuGet with Xamarin.Forms 3.1.0.637273 on 5.1 and 6.0 Android versions.

**Comment by MasKhan20** [comment]
Any workaround or solution to this? I just removed the slider for now.

**Comment by jeffmoreta** [comment]
i need Slider or progress de current Audio reproduction. i lost this plugins
