### ISSUE TITLE
[Android] VideoPlayerImplementation's Play method runs synchronously

### ISSUE THREAD

**Issue by adrianknight89** [martijn00/XamarinMediaManager#388]
When I open the project in VS, I'm getting a warning in `VideoPlayerImplementation.cs` that [Play](https://github.com/martijn00/XamarinMediaManager/blob/ff9dc784401f0a4942b7e1c8d086331b401afba1/MediaManager/Platforms/Android/Video/VideoPlayerImplementation.cs#L264) method is missing an `await` keyword and run synchronously.

**Comment by kikolopes90** [comment]
It happened to me, and also "AudioPlayer.Play()"
