### ISSUE TITLE
Error:  error: AnalyticsListenerImplementor is not abstract and does not override abstract method onRenderedFirstFrame(EventTime,Surface) in AnalyticsListener public class AnalyticsListenerImplementor

### ISSUE THREAD

**Issue by jrahma** [martijn00/XamarinMediaManager#390]
After using XamarinMediaManager I am getting:

> Error:  error: AnalyticsListenerImplementor is not abstract and does not override abstract method onRenderedFirstFrame(EventTime,Surface) in AnalyticsListener
> public class AnalyticsListenerImplementor

I added:

```
public override void onRenderedFirstFrame()
{
       // LogUtil.i(this, "MainActivity.onRenderedFirstFrame.");
}

```
to my MainActivity.cs but still not fixed.

How can I fix this please?

**Comment by adrianknight89** [comment]
See https://github.com/martijn00/ExoPlayerXamarin/issues/64

**Comment by SamTheDev** [comment]
https://github.com/martijn00/ExoPlayerXamarin/issues/64#issuecomment-393505696

**Comment by SamTheDev** [comment]
This exception still appear on the latest version!
https://github.com/martijn00/ExoPlayerXamarin/issues/64#issuecomment-393505696
