### ISSUE TITLE
Notification tutorial

### ISSUE THREAD

**Issue by dupuisdavid** [martijn00/XamarinMediaManager#391]
Hello guys,
I'm a beginner in Xamarin and I need a full sample for notification control panel like in Hanselman application. I have examined this app but don't understand how it succeeds to display play/pause/stop button controls in the notification panel.
Can you help me?

Regards.

**Comment by thomcuddihy** [comment]
For which platform are you curious about?

**Comment by dupuisdavid** [comment]
Android and iOS.

**Comment by thomcuddihy** [comment]
I would draw your attention to the MediaNotificationManagerImplementation classes for those platforms then:
[Android](https://github.com/martijn00/XamarinMediaManager/blob/develop/MediaManager/Platforms/Android/MediaSession/MediaNotificationManagerImplementation.cs)
[iOS](https://github.com/martijn00/XamarinMediaManager/blob/develop/MediaManager/Platforms/Ios/MediaNotificationManagerImplementation.cs)

Within the Android class, there is a method called `AddActionButtons`. You can see there that it is calling `AddAction` on the `NotificationCompat.Builder` object `_builder` to add either a play or pause icon (depending on `mediaIsPlaying`),  and previous/next icons on whether the `MediaQueue` has previous or next items. More information on NotificationCompat can be found on the Android spec [here](https://developer.android.com/reference/android/support/v4/app/NotificationCompat) and the Xamarin spec [here](https://developer.xamarin.com/api/type/Android.App.Notification+Builder/). There is a general overview of it for Android [here](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/notifications/local-notifications), though the Android MediaNotificationManagerImplementation class in this project is arguably a better method to learn about media specific notifications. For an Oreo compatible MediaNotificationManagerImplementation class, please see [here](https://github.com/thomcuddihy/XamarinMediaManager/blob/develop/MediaManager.Demo.Android/PVLMediaNotificationManager.cs).

For iOS, you can immediately see that the MediaNotificationManagerImplementation class is inheriting from the RemoteControlNotificationManager class, that handles calls to `UIApplication` to either begin or end receiving remote control events. Those events should be handled by overriding `UIApplication.RemoteControlReceived(UIEvent)` as mentioned in the `README.md` to this project.  In terms of displaying the media notification, the MediaNotificationManagerImplementation class uses the `MPNowPlayingInfoCenter` object to notify iOS regarding the media content it is playing (see [here](https://developer.apple.com/documentation/mediaplayer/mpnowplayinginfocenter)). Specifically, see the `CreateNowPlayingInfo` method, which populates a `MPNowPlayingInfo` object with the media metadata. This [page](https://www.c-sharpcorner.com/blogs/xamarin-ios-audio-player-notification) may help explain the bare minimum required, but again the code in this project is quite useful to examine. In this platform, the format of the notification and the media buttons presented on the notification are handled by iOS, ostensibly for app consistency.

**Comment by dupuisdavid** [comment]
Thank you!

**Comment by modplug** [comment]
@thomcuddihy Can you add that to the Wiki?
