### ISSUE TITLE
MediaNotificationManager is null

### ISSUE THREAD

**Issue by arnvanhoutte** [martijn00/XamarinMediaManager#395]
Sample code:

    CurrentPlaying = media ?? throw new ArgumentNullException(nameof(media));
    media = await MediaPlayer.MediaExtractor.ExtractMediaInfo(media).ConfigureAwait(false);
    await MediaPlayer.Play(media).ConfigureAwait(false);

    MediaPlayer.MediaNotificationManager?.StartNotification(media);
    MediaPlayer.MediaNotificationManager?.UpdateNotifications(media, MediaPlayerStatus.Playing);

When running this I notice that MediaNotificationManager always is null. Any reason why this is? Have I forgotten a permission?

Proof: 

![](https://i.imgur.com/4fMoE0x.png)
**Platform:** 
- [x] :robot: Android
- [x] :monkey: Xamarin.Forms

**Comment by ragnarek81997** [comment]
try run this code in main thread?

**Comment by arnvanhoutte** [comment]
Yes I am

**Comment by ragnarek81997** [comment]
download the project, include and rty debug, at one time it helped me

**Comment by arnvanhoutte** [comment]
Eh I just realized that this issue is probably because my main library is running .netstandard 2.0 and it is not fully supported yet
