### ISSUE TITLE
How many video format supported ?

### ISSUE THREAD

**Issue by dhpanteon** [martijn00/XamarinMediaManager#398]
**1) How many video format supported (in ios and android) by this plugin?**

Other questions:
1) Does this plugin play 4k video easily ?
2) Do you have planning to support WPF ?

**Comment by martijn00** [comment]
Currently it supports quite some, but in version 1.0 it will support almost everything. In 1.0 it will also support 4k. There are no plans for WPF at the moment, but you can hire me to make it.

**Comment by dhpanteon** [comment]
Ye but Just for clarity, i want to know how many format supported right now.

**Comment by martijn00** [comment]
Depends on the device and software. There is no number, so you need to find out yourself by testing it.
