### ISSUE TITLE
Xamarin Forms macOS Video not rendered

### ISSUE THREAD

**Issue by NvVijayakumara** [martijn00/XamarinMediaManager#399]
I'm using Visual Studio 2017 with Xamarin.Forms 3.1.0.697729 and using the MediaManager with a PCL. When I start to play a video on macOS only Audio is playing not Video.

**included following packages:**

Plugin.MediaManager
Plugin.MediaManager.Forms

**videopage.Xaml i used like this:**

// included - 
xmlns:forms="clr-namespacelugin.MediaManager.Forms;assembly=Plugin.MediaManager.Forms"
    
<StackLayout>              
<forms:VideoView HeightRequest="180"  x:Name="vv"
                             WidthRequest="320" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" AspectMode="AspectFill" />     
            
            <StackLayout Orientation="Horizontal" Padding="20">
                <Label  x:Name="VideoStatus"
                        HorizontalOptions="StartAndExpand"
                        VerticalOptions="Center"
                        HorizontalTextAlignment="Center"
                        Text="Xamarin Forms"  
                        FontSize="40"  
                        TextColor="Azure"/> 
                <Button x:Name="ControlButton" 
                        Text="Play" 
                        BackgroundColor="Gray"
                        HorizontalOptions="EndAndExpand"
                        VerticalOptions="Center"
                        Clicked="ControlButton_OnClicked" />
            </StackLayout>
</StackLayout>
        
**videopage.xaml.cs i used like this:**

// included
using Plugin.MediaManager;
using Plugin.MediaManager.Abstractions.Enums;

       private string videoUrl = "https://sec.ch9.ms/ch9/e68c/690eebb1-797a-40ef-a841-c63dded4e68c/Cognitive-Services-Emotion_high.mp4";

        public VideoPage()
        {
            InitializeComponent();
        }

        private async void ControlButton_OnClicked(object sender,EventArgs e)
        {  
            switch(ControlButton.Text)
            {
                case "Play":
                    await CrossMediaManager.Current.Play(videoUrl, MediaFileType.Video);  
                    ControlButton.Text = "Pause";
                    ControlButton.BackgroundColor = Color.Crimson;
                    VideoStatus.Text = "PLaying..";
                    break;
                case "Pause":
                    await CrossMediaManager.Current.Pause();
                    ControlButton.Text = "Play";
                    ControlButton.BackgroundColor = Color.LimeGreen;
                    VideoStatus.Text = "Paused";
                    break;
            }
        }  

**AppDelegate.cs i used like this:**

// included following
Plugin.MediaManager
Plugin.MediaManager.Forms 

public override void DidFinishLaunching(NSNotification notification)
        {
            var workaround = typeof(VideoView); 
            Forms.Init();
            LoadApplication(new App());

            base.DidFinishLaunching(notification);         
        }'

I appreciate your help.. :)

**Comment by martijn00** [comment]
Fixed in 0.6.7
