### ISSUE TITLE
Can't read Status before playing

### ISSUE THREAD

**Issue by jmartine2** [martijn00/XamarinMediaManager#4]
If you try to read the Status field of the MediaManager and you haven't called Play() yet, then you get a Null Reference Exception in line 47 of MediaPlayerService.cs (Android).

        public int MediaPlayerState
        {
            get{
                return mediaControllerCompat.PlaybackState.State;
            }
        }

This appears to be because mediaControllerCompat is only initialized in the Play() method.

My application has logic so that if I try to press the Play button, the click handler will return if the Status is not PlayerStatus.STOPPED. So, the first time I try to play a song, I get the exception.

This is happening in the Android implementation. Not sure about other implementations.

**Comment by martijn00** [comment]
That has been fixed some time ago
