### ISSUE TITLE
.NETStandard Support

### ISSUE THREAD

**Issue by eman1986** [martijn00/XamarinMediaManager#403]
This looks very promising for what I'm looking for, however it doesn't support .NET Standards, do you have any plans to add support for it any time soon?

**Comment by CSkoubo** [comment]
It does support it, its just not released yet as there are other things that needs an update. Its work in progress, not many active contributors. Im currently booked till after the 18th sep, then ill chip in. I know Martijn and one of his colleagues are doing some updates atm.

**Comment by martijn00** [comment]
@eman1986 We are working on this, but need backing to speed things up. Send me a message if you are interested in getting paid support.

**Comment by skipper876** [comment]
@CSkoubo any update on .Net Standard 2?

**Comment by adrianknight89** [comment]
any update?

**Comment by thealexcons** [comment]
Any updates?
