### ISSUE TITLE
Xamarin CrossMediaManager Video Only works on the first run

### ISSUE THREAD

**Issue by wpanduka** [martijn00/XamarinMediaManager#406]
Steps to reproduce :

1. I am using the CrossMediaManager to play video in my tab download folder , the video play path is file:///storage/emulated/0/Download/DilmahStory.mp4

the problem is that when i move the video page to another page and coming back to the video page the video paused. the requirement is to start the video from the beginning when every time user open the video page.

2. The existing the video page view model  code as below.
```
public class GuestVideoViewModel : ContextViewModelBase
    {
        private string videoUrl = "file:///storage/emulated/0/Download/DilmahStory.mp4";
        private TimeSpan seekTime;
        public GuestVideoViewModel(IAppContext context) : base(context)
        {
            Title = "Guest Vedio Page";
            ActionCommand = new Command(OnActionCommand);
            PageAppearingCommand = new Command(OnPageAppearingCommand);
            PageDisappearingCommand = new Command(OnPageDisappearingCommand);
        }

        public string GotoMenuName { get; set; } = "START ORDER";

        public ICommand ActionCommand { get; }

        private void OnActionCommand()
        {
            Navigator.PushAsync<DashboardMainFirstViewMode>();
        }

        private async void OnPageDisappearingCommand()
        {
            seekTime = CrossMediaManager.Current.Position;
            await CrossMediaManager.Current.Stop();
            CrossMediaManager.Current.StatusChanged -= CurrentOnStatusChanged;

           // 
        }

        private async void OnPageAppearingCommand()
        {
            if (await GetStoragePermisson())
            {
                CrossMediaManager.Current.StatusChanged += CurrentOnStatusChanged;

                await CrossMediaManager.Current.Play(videoUrl, MediaFileType.Video);

            }
        }

        private void CurrentOnStatusChanged(object sender, StatusChangedEventArgs e)
        {

            Debug.WriteLine($"MediaManager Status: {e.Status}");

        }

        private async Task<bool> GetStoragePermisson()
        {
            var status = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Storage);
            if (status != PermissionStatus.Granted)
            {
                var results = await CrossPermissions.Current.RequestPermissionsAsync(new[] { Permission.Storage });
                status = results[Permission.Storage];
            }
            return status == PermissionStatus.Granted;
        }
    }
} 
```

3.
I have no idea why the video doesn't start from the beginning when open the vediopage.( after the first run)

Expected behavior : Expecting the video should play from the begging every time the page appears to the user 

Actual behavior :bug: every time leave the page( video playing page ) the video paused and never play again until the application close and open again , which is totally not the behavior we want

Configuration :wrench:
Version:** 4.9.0 xamarin ( visual studio 15.6.5)

Platform:
- : Android
- : Xamarin.Forms

I will be really grateful if someone can guide me what should I change on the OnPageAppearingCommand() or OnPageDisappearingCommand(), Thank you in advance for your support.

**Comment by Shan11812** [comment]
Try setting source to null on disappearing

**Comment by wpanduka** [comment]
Thnak you @Shan11812 for the reply, as you said it will work but the problem is that if the user press the back button and go back to the page , exception throws since the source is null, is their any other solution as far as you know, thank you once again for the support,

**Comment by jadenrogers** [comment]
@wpanduka 

Added PR to address issue on master https://github.com/martijn00/XamarinMediaManager/pull/413
