### ISSUE TITLE
AudioPlayer.PlayingChanged not returning values on Android with latest Xamarin Forms (3.2.0)

### ISSUE THREAD

**Issue by SGDAT** [martijn00/XamarinMediaManager#407]
Hi,

I am having trouble with the CrossMediaManager.Current.AudioPlayer.PlayingChanged event not returning any updated values. Although the audio plays, there are no values being returned in this event.

This worked fine until I updated xamarin forms to the latest version (3.2.0) and other xamarin android packages (Xamarin.Android.Support).

I have been working on an audio app for all platforms for a charity and would appreciate the support. I have created a very basic project at the GitHub link below:-

https://github.com/SGDAT/MediaManagerAndroidTest

Running it will run the code in question in the OnAppearing override method.

If I can be at least pointed at code that I can update myself in order to get the correct values being returned or be shown another event/or method I can use for getting the actual position of the audio, that would be great.

Thanks.

Kind Regards,

Samson

**Comment by cklenk** [comment]
I too have this problem. I am using Xamarin forms 3.3.0.912540 with .NetStandard Library 2.03. I play the media file and then check the MediaPlayerStatus and it always returns stopped. Even though the audio is playing (you can hear it). Any updates on this?

**Comment by SGDAT** [comment]
Unfortunatly there is no real update.

However I was able to solve this by using the source files from the fork provided by "thomcuddihy" https://github.com/thomcuddihy/XamarinMediaManager. it's very Android and iOS focused but I was able to add UWP project pretty easily. I will publish that to my fork later.

**Comment by cklenk** [comment]
Thanks @SGDAT I will take look. I'm only interested in Android and iOS anyways! I see there was some updates to the vNext branch yesterday so maybe @martijn00 is working on it?

**Comment by martijn00** [comment]
I'm doing some work on a new version. It might be ready in some weeks or so.

**Comment by cklenk** [comment]
@martijn00 I'm curious if the new version is still being actively developed or still on hold? Thanks!
