### ISSUE TITLE
Music stops in the middle in Android... Exoplayer code never start playing music

### ISSUE THREAD

**Issue by Alexabreu007** [martijn00/XamarinMediaManager#410]
I'm trying to use Exoplayer in Android so I can play the music in background and avoid that system kills my app in the middle of the music, but when I use the exoplayer code the music does not starts, if I remove the exoplayer code the music starts but the android OS kill my app to save resource in the cellphone.

Also, I saw that http files does not work with exoplayer, let me know if that's true or not.

Note 1. I don't have this issue in Forms iOS, it works fine and music ends to the end.

Note 2: My music files has 1 hour duration.

Android code:

        private MediaPlayerViewModel ViewModel { get; set; }

        private IMediaManager MediaManager => ViewModel.MediaPlayer;

        private IPlaybackController PlaybackController => MediaManager.PlaybackController;

ViewModel = new MediaPlayerViewModel();

                ((MediaManagerImplementation)CrossMediaManager.Current).MediaSessionManager = new MediaSessionManager(Application.Context, typeof(ExoPlayerAudioService), MediaManager);
                var exoPlayer = new ExoPlayerAudioImplementation(((MediaManagerImplementation)CrossMediaManager.Current).MediaSessionManager);
                CrossMediaManager.Current.AudioPlayer = exoPlayer;

### Steps to reproduce :scroll:

1. 

2.

3.

### Expected behavior :thinking:
Play the music in background and avoid that system kill my app in the middle of the music

### Actual behavior :bug:
Music stop playing because the app being kill by Androis OS and when I use ExoPlayer music never starts.

### Configuration :wrench:

**Version:** 0.4.5

**Platform:** 
- [ X] :iphone: iOS
- [X ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ X] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
You need to wait for the next version, which will fix this. See https://github.com/martijn00/XamarinMediaManager/tree/vNext

**Comment by abreucruz** [comment]
Hi Martin, when do you estimate you can fix this?
