### ISSUE TITLE
Resume play

### ISSUE THREAD

**Issue by cswanne** [martijn00/XamarinMediaManager#411]
### Steps to reproduce :scroll:

Load a video into VideoView
1. on button1 - use CrossMediaManager.Current.Play(videoUrl1, MediaFileType.Video);

2. when button2 pressed use CrossMediaManager.Current.PlaybackController.PlayPause();

3. when button1 pressed use CrossMediaManager.Current.Play(videoUrl1, MediaFileType.Video);

### Expected behavior :thinking:
Should play video on button1, pause on button2 then resume from paused position on button1

### Actual behavior :bug:
Starts the video playing from the beginning again

### Configuration :wrench:

**Version:** 0.4.5

**Platform:** 

- [X ] :robot: Android
- [X ] :monkey: Xamarin.Forms

**Comment by jadenrogers** [comment]
@cswanne This can be solved in code. You are passing in a new media file be it the same one on button1.
I tend to setup the video in the onappearing event, and then just have play and pause on your button events / commands.

**Comment by Nanolocity** [comment]
It says that it's "Done" and so I assume it should be implemented already but it still doesn't work. There is no option to do so.(doing SeekTo and then doing PlayPause or Play just doesn't work and either starts from the beginning or doesn't do anything)
