### ISSUE TITLE
Can't an audio be paused and resumed?

### ISSUE THREAD

**Issue by mwallon** [martijn00/XamarinMediaManager#419]
Is it true that you can't pause an audio file and then resume its again on Android? I've tried in a lot of ways but nothing seems to work? My latest test is as simple as this:
1. Start the sound(this works):
 await CrossMediaManager.Current.Play(url);
2. Pause the sound(this works):
await CrossMediaManager.Current.Pause();
3. Try to resume(Doesn't work, nothing happens):
await CrossMediaManager.Current.Play();

/magnus

**Comment by DanMburu** [comment]
I'm also experiencing the same issue. It plays for a second and then stops.

**Comment by Muthutc** [comment]
hi @DanMburu and @mwallon 

use await CrossMediaManager.Current.PlayPause();
