### ISSUE TITLE
Cant build XamarinMediaManager on MacOS

### ISSUE THREAD

**Issue by MrSerWin** [martijn00/XamarinMediaManager#436]
## 💬 Can you please help me to build project

Error: The version of the .NET Core SDK currently installed (/usr/local/share/dotnet/sdk/2.2.106/Sdks) is not supported and continuing to use it may result in a broken tooling experience. 
https://aka.ms/vs/mac/install-netcore (MediaManager)

**Comment by martijn00** [comment]
Unfortunately this is a problem on Microsoft's side: https://github.com/mono/monodevelop/projects/1
The workaround is to compile from command line with msbuild.
