### ISSUE TITLE
Error getting response stream

### ISSUE THREAD

**Issue by MrSerWin** [martijn00/XamarinMediaManager#438]
## 🐛 Bug Report
Unhandled Exception:
System.Net.WebException: Error getting response stream (ReadDoneAsync2): ReceiveFailure

### Expected behavior
call next traсk from remote control. I expect that track will change 

### Reproduction steps
set playlist and play track, in notify pannel click to next\prev button

### Configuration

**Version:** 0.5.3

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Can you make a PR to showcase this in this repo sample?

**Comment by MrSerWin** [comment]
@martijn00 Sorry, I'm not sure that I understood you. Can you please rephrase.
What I should show in this PR? I have this error on my local project

**Comment by martijn00** [comment]
I need a public github repo with a reproduction case.

**Comment by MrSerWin** [comment]
I see. ok, will prepare

**Comment by MrSerWin** [comment]
https://github.com/MrSerWin/QirimOnline/blob/master/x.qo/x.qo/ViewModels/AlbumTraksVM.cs
in Play() - I configure playlist and call await CrossMediaManager.Current.Play(_playList);
after that try to use remotecontrol (on lockscreen ot notification panel Android)

**Comment by MrSerWin** [comment]
1. start app
2. select one item form albums list
3. on opened form click play
4. use remote control to switch track

**Comment by MrSerWin** [comment]
@martijn00 also, if you change android manfest file and set android:targetSdkVersion="28"
you can see error 
java.lang.securityexception: <timeout exceeded getting exception details> occurred

**Comment by martijn00** [comment]
@MrSerWin Add the full stacktrace please. And use code blocks for it.

**Comment by MrSerWin** [comment]
@martijn00 
1. if call CrossMediaManager.Current.Play(_playList); twice
```
{System.InvalidOperationException: Collection was modified; enumeration operation may not execute.  
at System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () [0x00013] in <58604b4522f748968296166e317b04b4>:0   
at System.Collections.Generic.List`1+Enumerator[T].MoveNext () [0x0004a] in <58604b4522f748968296166e317b04b4>:0   
at MediaManager.MediaManagerImplementation.Play (System.Collections.Generic.IEnumerable`1[T] items) [0x000d7] 
in C:\Users\mhvdi\Documents\OpenSource\XamarinMediaManager\MediaManager\Platforms\Android\MediaManagerImplementation.cs:153   
at x.qo.ViewModels.AlbumTraksVM.Play () [0x00051] in D:\Temp\x.qo\x.qo\x.qo\ViewModels\AlbumTraksVM.cs:102 }
```

2. I could not get stacktrase for remote controll. I did not find place to catch it
```
Unhandled Exception:
System.Net.WebException: Error getting response stream (ReadDoneAsync2): ReceiveFailure occurred
```

3. for android:targetSdkVersion="28". The same problem, I did not find place to catch it  
Just call Play:
```
Unhandled Exception:
Java.Lang.SecurityException: <Timeout exceeded getting exception details> occurred
```

**Comment by MrSerWin** [comment]
fixed. just should add FOREGROUND_SERVICE

> Unhandled Exception:
Java.Lang.SecurityException: <Timeout exceeded getting exception details> occurred
