### ISSUE TITLE
[Forms][Android][iOS] StateChanged wrong event when Play

### ISSUE THREAD

**Issue by valentin-debris** [martijn00/XamarinMediaManager#441]
## 🔙 Regression
When press play, stop and re-play, the StateChanged  event send "Stopped" at first when re-play.

### Old (and correct) behavior
When the play function is called, the only states that should be triggered to the StateChanged event should be Loading, Buffering, Playing (if no Error of course)

### Current behavior
The first event returns when replay is Stopped (and then Buffering and Playing). This is a problem because when I receive the "Stopped" State (generated when click on stop button in the notification for example), I do some modification in the UI that now, let user thinking the song is stopped.

### Reproduction steps
[https://github.com/valentin-debris/MediaManagerStates](https://github.com/valentin-debris/MediaManagerStates)

### Configuration

**Version:** 0.5.3

**Platform:** 
- [] :iphone: iOS (not tested)
- [x] :robot: Android
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Why not use Pause instead of Stop?

**Comment by NickA55** [comment]
> Why not use Pause instead of Stop?

I use stop when I want to stop the stream from a streaming radio service.  For me, stop and pause have very different meanings, and when the user resumes from a pause MediaManager still reports "Stopped" instead of "Playing".  So I can't update the UI properly.

**Comment by martijn00** [comment]
Can you test this again in 0.5.7?

**Comment by NickA55** [comment]
Version 0.5.7 is giving me a TIC Read Status [1:0x0]: 1:57 Unhandled Exception
 System.NullReferenceException,  That's usually an iOS thing for I/O I think.

I had to revert back to 0.5.5.

**Comment by martijn00** [comment]
Do you have an url which I can test?

**Comment by NickA55** [comment]
> Do you have an url which I can test?

Here you go: https://github.com/NickA55/mmtest

It's currently using 0.5.7 and errors on play.  Works fine on 0.5.6

**Comment by martijn00** [comment]
Can you test again with 0.5.8?

**Comment by NickA55** [comment]
0.5.8 is working.  Calling await CrossMediaManager.Current.Pause() still causes CrossMediaManager.Current.MediaPlayer.State to report "Stopped" however.  

I've updated the sample project with pause/stop and a status label.

**Comment by martijn00** [comment]
It seems like you get the state from the player itself. That might be different on the different platforms. I might close off that API, so there is only a single state API. I'm not sure if this is a bug or not.
