### ISSUE TITLE
[Forms][Android] MediaManager.Forms Breaks project compilation with Android Platform Target 9.0

### ISSUE THREAD

**Issue by tehort** [martijn00/XamarinMediaManager#444]
## 🐛 Bug Report

When compiling an project using XamarinMediaManager.Forms 0.5.3 and Target Android Framework: 9.0, compiler throws an error:
"java exited with code 2" 

Compiles fine if using Android Framework 8.1

### Expected behavior
Allow compilation of projects.

### Reproduction steps
Create a new Xamarin.Forms project, add MediaManager.Forms, set Android Target Framework to 9.0 and compile.

Results with: "Java exited with code 2"

### Configuration
VS 2019
Android Target Framework 9.0
**Version:** 0.5.3

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
You absolutely need 9.0. if you get `java exited with code 2` you need to enable multidex because there are too much libraries in your project.

**Comment by tehort** [comment]
> 
> 
> You absolutely need 9.0. if you get `java exited with code 2` you need to enable multidex because there are too much libraries in your project.

Tried on a new, empty project.
