### ISSUE TITLE
[Android] Usage on API 28

### ISSUE THREAD

**Issue by karak** [martijn00/XamarinMediaManager#446]
## 💬 Questions and Help

Thank you for your work. I have used it in our product.

Please tell me whether this plugin requires new FOREGROUND permission on Android Pie(API 28) or any other work when we update SDK version?

Especially audio controller on the lock screen

**Comment by MrSerWin** [comment]
you are right. I had the same problem. on 28 need additional permission FOREGROUND
if I'm not mistaken on older versions it was MediaContentControl

**Comment by karak** [comment]
@MrSerWin Thanks!

**Comment by martijn00** [comment]
I've added an assembly attribute in 0.5.4 for this.
