### ISSUE TITLE
The type or namespace name 'Plugin' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by jsanon10** [martijn00/XamarinMediaManager#447]
## 🔙 Regression

Despite having the latest Nuget package(Plugin.MediaManager.Forms 0.5.3) installed in my project, the name space **"using Plugin.MediaManager;"** is showing a red underline under "Plugin"

It's been working fine for over a month now.

Has anybody seen this problem before?

![image](https://user-images.githubusercontent.com/46775334/56345721-705e7680-618e-11e9-9e4a-266865ddd8c5.png)

### Configuration

**Version:** 1.x

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android
- [x] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by valentin-debris** [comment]
@jsanon10 ,
Just remove the word "Plugin", or the entire line and let VS add what it proposed to you, this is due to the new version.

**Comment by jsanon10** [comment]
Thanks, that fixed most of the problem

However, I haven't been able to play video anymore

//my previous 'play' code that use to work.....the video played 
CrossMediaManager.Current.Play(videoUrl, MediaFileType.Video);

//my current code that doesn't work....the video doesn't play
CrossMediaManager.Current.Play(videoUrl);

**Comment by jsanon10** [comment]
I was able to resolve the second "Play" issue by updating the video Init() code on these 3 files; from "_VideoViewRenderer.Init();_" to "_CrossMediaManager.Current.Init();_"
-AppDelagate.cs
-MainPage.xaml.cs
-MainActivity.cs

![image](https://user-images.githubusercontent.com/46775334/56466005-2963c180-63d8-11e9-9769-204273a445ff.png)

**Comment by martijn00** [comment]
You need to set a player view, see the readme.

**Comment by jrahma** [comment]
Why I can't get the MediaFileType?

`CrossMediaManager.Current.Play("https://www.jeccd.ae/gallery/Welcome.mp4", MediaFileType.Video);
`
**The name 'MediaFileType' does not exist in the current context**

**Comment by martijn00** [comment]
@jrahma look at the documentation. This changed a long time ago.
