### ISSUE TITLE
Can't play m3u8 video in Android

### ISSUE THREAD

**Issue by mariksel** [martijn00/XamarinMediaManager#450]
### Old (and correct) behavior
Video played correctly

### Current behavior

com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.

### Reproduction steps
await CrossMediaManager.Current.Play("http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8");

### Configuration

**Version:** 0.5.3

**Platform:** 

- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Try: `await CrossMediaManager.Current.Play(new MediaItem("http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8") { MediaType = MediaType.Hls });`
