### ISSUE TITLE
Error: Failed to resolve assembly: 'Plugin.MediaManager.Forms

### ISSUE THREAD

**Issue by Denaindra** [martijn00/XamarinMediaManager#452]
## 🐛 Bug Report

- [ ] :monkey: Xamarin.Forms

I'm trying 0.5.3 version which is latest. And i set namespace as xmlns:forms="clr-namespace:Plugin.MediaManager.Forms;assembly=Plugin.MediaManager.Forms"  But still i'm unable to build the project.

**Comment by valentin-debris** [comment]
@Denaindra 
Try to remove the line and set what VS proposes to you. Since 0.5.0, it's not "Plugin.MediaManager" but just "MediaManager".
