### ISSUE TITLE
Notifications are not clearing even after video page is removed from navigation stack. And It is only clearing when the app is closed

### ISSUE THREAD

**Issue by SatyaRamprasad** [martijn00/XamarinMediaManager#454]
## 🐛 Bug Report

Notifications are not clearing even after video page is removed from navigation stack. And It is only clearing when the app is closed

### Expected behavior
Media Notification should clear if the video page is not active.

### Reproduction steps
Create a page and call video view  in Xamarin forms

### Configuration

**Version:** 0.5.3

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :monkey: Xamarin.Forms

Media Player Notifications are not clearing even after video page is removed from navigation stack in xamarin forms . And It is clearing when the app is closed.

Any help? @martijn00 
Thanks in advance.

**Comment by martijn00** [comment]
Please use the issue template.

**Comment by martijn00** [comment]
Should be mostly fixed in 0.5.4. Let me know in a new issue if there are problems
