### ISSUE TITLE
Close the player after finalizing the audio

### ISSUE THREAD

**Issue by ivanteles** [martijn00/XamarinMediaManager#455]
## 💬 Questions and Help

How to close the player after the audio is finished?
![image](https://user-images.githubusercontent.com/843086/56699854-b014e900-66cd-11e9-863f-51f3e670af3c.png)

**Comment by valentin-debris** [comment]
@ivanteles 
I assume you are using Android. @martijn00 says [here](https://github.com/martijn00/XamarinMediaManager/issues/439#issuecomment-483634709) to use Exoplayer to control the behavior for the notifs in Android (https://medium.com/google-exoplayer/the-mediasession-extension-for-exoplayer-82b9619deb2d).

**Comment by martijn00** [comment]
Fixed in 0.5.4
