### ISSUE TITLE
Access media on an authenticated host

### ISSUE THREAD

**Issue by jemunk** [martijn00/XamarinMediaManager#456]
Hi. I have tried and searched a lot for a solution on how to access media on an authenticated host. 
On Android i get this response:
```
04-25 08:50:07.344 E/ExoPlayerImplInternal(17164): Source error.
04-25 08:50:07.344 E/ExoPlayerImplInternal(17164): com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
```

I have a System.Net.Http.HttpClient that is authenticated and have the cookies stored for it. But how do I tell MediaManager to use that client or copy the cookies to the client used by MediaManager?

I am on .Net Standard

**Comment by martijn00** [comment]
Add headers to `CrossMediaManager.Current.RequestHeaders`

**Comment by jemunk** [comment]
Thanks a lot! That did it.
