### ISSUE TITLE
Close Activity and Start again Player never start new mp3 file

### ISSUE THREAD

**Issue by ScpInteractive** [martijn00/XamarinMediaManager#457]
Hi,

I'm using this code in Player Activity in Android.

CrossMediaManager.Current.Init(this);

After that i played all feautre but i'm finish this activity with ClearTop and ClearTask Flags. After that i'm returning player activity with another mp3 file. Player doesn't play anything. How can i successfully close and dispose CrossMediaManager.

Thanks.

**Comment by martijn00** [comment]
Can't you call Init again with the new activity?

Also, please use and update the issue with an issue template.

**Comment by martijn00** [comment]
You can also use `CrossMediaManager.Android.SetContext(this);` on any specific Activity in the app.
