### ISSUE TITLE
Question: Simultaneous MP3 Playback?

### ISSUE THREAD

**Issue by robbpriestley** [martijn00/XamarinMediaManager#458]
Just a quick question, please.

Is it possible to play multiple MP3 files simultaneously using XamarinMediaManager? By "multiple" I mean a variable number: from zero to three, controlled programatically by the application code.

**Comment by martijn00** [comment]
No this is not possible at the moment. You can only play 1 item at the time.

**Comment by robbpriestley** [comment]
OK thanks for the info!
