### ISSUE TITLE
Question: Background Mode?

### ISSUE THREAD

**Issue by robbpriestley** [martijn00/XamarinMediaManager#459]
Another quick question, please.

When playing back audio, does XamarinMediaManager have support for lock screen media playback controls on iOS and Android?

Also for iOS and Android, if audio is playing and a phone call is received, how does this affect XamarinMediaManager audio playback (I believe the audio playback should be paused or otherwise dealt with as a lower priority).

**Comment by martijn00** [comment]
Yes there is support for lock screen media controls, but there are some open requests for enhancements.

Please use the issues templates.

**Comment by robbpriestley** [comment]
OK thanks for the info!

Sorry for not using the templates.
