### ISSUE TITLE
MediaItemFinished, MediaItemChanged event handlers are not working

### ISSUE THREAD

**Issue by SatyaRamprasad** [martijn00/XamarinMediaManager#461]
## 🐛 Bug Report

MediaItemFinished, MediaItemChanged event handlers are not working

### Expected behavior
MediaItemFinished, MediaItemChanged event handlers should fire, if media item is changed in playlist of media items.
### Reproduction steps
create a video player page and send the list of videos to CrossMediaManager.Current.Play(MediaItemsList);

when the video is finished or changed,MediaItemFinished, MediaItemChanged are not firing.
### Configuration

**Version:** 0.5.3

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android
- [x] :monkey: Xamarin.Forms

 Here is my view model code and i am using latest version of your plug in.

public PlayerViewModel()
        {
            CrossMediaManager.Current.MediaItemFailed += Current_MediaItemFailed;
            CrossMediaManager.Current.MediaItemFinished += Current_MediaItemFinished;
            CrossMediaManager.Current.MediaItemChanged += Current_MediaItemChanged;
        }
        private async void Current_MediaItemChanged(object sender, MediaItemEventArgs e)
        {
            await Application.Current.MainPage.DisplayAlert("Message", "NextVideo", "OK");
            MediaItem.MediaId = e.MediaItem.MediaId;
        }

        private async void Current_MediaItemFinished(object sender, MediaManager.Media.MediaItemEventArgs e)
        {
            IsBusy = false;
            if (PlayList.Count() == 0)
                await CrossMediaManager.Current.Stop();
        }

  private async void Current_MediaItemFailed(object sender, MediaManager.Media.MediaItemFailedEventArgs e)
        {
            await CrossMediaManager.Current.Stop();
        }

**Comment by martijn00** [comment]
Please use the issue templates.

**Comment by martijn00** [comment]
Fixed in 0.5.5. Let me know if anything doesn't work as expected.

**Comment by adambarath** [comment]
@martijn00 : On iOS MediaItemChanged does not work right now. (0.7.3, Xamarin Forms version, iOS 12.3.1). Control center's play/pause/prev/nect buttons does not work. At least do not do any action.

**Comment by martijn00** [comment]
@adambarath then you need to raise a new issue. And don't forget to fill in the template.
