### ISSUE TITLE
Failed to build Android sample app

### ISSUE THREAD

**Issue by PingPongSet** [martijn00/XamarinMediaManager#462]
I got the errors below when I tried to build ElementPlayer.Android project. I don't need to build for other platform.

Error		"java.exe" exited with code 2.	ElementPlayer.Android			

My environment:

VS 2017
Windows 7

**Comment by martijn00** [comment]
Your software is too old. Use Windows 10 with VS 2019. Make sure to enable multidex and set build RAM size to at least 1G.
