### ISSUE TITLE
Xamarin.Forms Android RepeatMode & ShuffleMode won't be applied

### ISSUE THREAD

**Issue by mattiabaldinger** [martijn00/XamarinMediaManager#464]
## 🐛 Bug Report

In some states, the RepeatMode, ShuffleMode (and also the ToggleShuffle and ToggleRepeat) doesn't have a effect on the CrossMediaManager and the mode remains the same as it was before (off)

### Expected behavior

Set the RepeatMode, ShuffleMode should always have an effect.

### Reproduction steps
var media = new[]{
    "https://ia800806.us.archive.org/15/items/Mp3Playlist_555/AaronNeville-CrazyLove.mp3",
    "https://ia800605.us.archive.org/32/items/Mp3Playlist_555/CelineDion-IfICould.mp3",
    "https://ia800605.us.archive.org/32/items/Mp3Playlist_555/Daughtry-Homeacoustic.mp3",
    };
CrossMediaManager.Current.RepeatMode = MediaManager.Playback.RepeatMode.One;
//RepeatMode is still off

await CrossMediaManager.Current.Play(media );
        
CrossMediaManager.Current.RepeatMode = MediaManager.Playback.RepeatMode.One;
//RepeatMode is still off
### Configuration

**Version:** 0.5.4

**Platform:** 
- [ ] :iphone: iOS
- [x ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
There are some fixes in 0.6.2 for this. Can you give it a try and report back?
