### ISSUE TITLE
How to set the current position of the mediaqueue

### ISSUE THREAD

**Issue by mattiabaldinger** [martijn00/XamarinMediaManager#465]
## 💬 Questions and Help

I want to set the CurrentPosition of my MediaQueue. So let's say I have a playlist with audio file A, B and C but instead of the starting with playing audio file A, I want to start with B. So I can execute previous and A will be played.

I did set the CurrentPosition of the MediaQueue (see option 1 and option 2) but both seems to have no effect or is reseted after the mediaplayer starts.

**Sample option 1**

var media = new[]{ pathA, pathB, pathC, };

await CrossMediaManager.Current.Play(media ); CrossMediaManager.Current.MediaQueue.CurrentIndex = 1;

**Sample option 2**

var extractor = CrossMediaManager.Current.MediaExtractor

CrossMediaManager.Current.MediaQueue.Add(await extractor.CreateMediaItem(pathA)); CrossMediaManager.Current.MediaQueue.Add(await extractor.CreateMediaItem(pathB)); CrossMediaManager.Current.MediaQueue.Add(await extractor.CreateMediaItem(pathC));

CrossMediaManager.Current.MediaQueue.CurrentIndex = 1;

//same code as in the existing play method

var mediamanager = CrossMediaManager.Current as MediaManagerImplementation; mediamanager.MediaBrowserManager.MediaController.GetTransportControls().Prepare();

**Comment by martijn00** [comment]
await CrossMediaManager.Current.PlayQueueItem(mediaItem);

Available in 0.6.3
