### ISSUE TITLE
[Forms][Android][iOS] Disable notification controls in Android and iOS

### ISSUE THREAD

**Issue by tehort** [martijn00/XamarinMediaManager#468]
## 💬 Questions and Help

Is there an easy way to completely disable notification controls in Android and iOS?
I've looked around into ExoPlayer sources, but it looks a bit overwhelming. Haven`t gotten into iOS yet.

Any direction or tips?

**Comment by martijn00** [comment]
CrossMediaManager.Current.NotificationManager.Enabled = false;

Available in 0.5.6

**Comment by Muthutc** [comment]
Hi @tehort Did you tried

`CrossMediaManager.Current.NotificationManager.Enabled = false; `

Is it working ??

**Comment by tehort** [comment]
> 
> 
> Hi @tehort Did you tried
> 
> `CrossMediaManager.Current.NotificationManager.Enabled = false; `
> 
> Is it working ?? Please Let me know.

Yes, working just fine.

**Comment by kishor010** [comment]
Hi @tehort 
Please help me out in this.
In Android it is working.
For iOS it is not working.
