### ISSUE TITLE
IMediaManager.Cover no longer exists

### ISSUE THREAD

**Issue by jmartine2** [martijn00/XamarinMediaManager#47]
I was attempting to use the lastest MediaManager with my project, and it appears that IMediaManager.Cover no longer exists (as of PR# 44 I believe). 

If this was intentional, what is the new way of accessing the current cover?

**Comment by martijn00** [comment]
The Cover is now in the IMediaFile, IMediaFileMetadata object: https://github.com/martijn00/XamarinMediaManager/blob/master/MediaManager/Plugin.MediaManager.Abstractions/IMediaFileMetadata.cs#L38

Using the default `MediaFile` you can get the Cover, or you could provide your own implementation.

**Comment by jmartine2** [comment]
Thanks.  Given an IMediaManager object, How can I access the IMediaFile object for the currently playing song? I don't see any reference to it in IMediaManager.

**Comment by modplug** [comment]
The MediaQueue has a QueueChanged event if I remember correctly

**Comment by jmartine2** [comment]
Is that the only way to get it now? My application has places where it needs to access the cover of the currently playing song. Before, I was just able to access the Cover property of the MediaManager object to get it. Adding a QueueChanged listener is more cumbersome, as I would then need to cache it somewhere for later use.

**Comment by martijn00** [comment]
The Items playing are now put into the `MediaQueue`by default. This means you can get the current items cover with this: `CrossMediaManager.Current.MediaQueue.Current.Metadata.Cover`

Be aware that the current, MetaData and Cover can be null, so what you can do is listen for changes on the MediaFileChanged event.

**Comment by jmartine2** [comment]
Perfect, thanks!
