### ISSUE TITLE
CrossMediaManager.Current.Init() issue

### ISSUE THREAD

**Issue by ramprudvi** [martijn00/XamarinMediaManager#470]
Issue: We are getting not implemented issue when trying to implement CrossMediaManager

**Comment by Muthutc** [comment]
hey,I am also getting same issue for android.

**Comment by ramprudvi** [comment]
Unhandled Exception:

System.NotImplementedException: <Timeout exceeded getting exception details> occurred this issue exactly mine

**Comment by martijn00** [comment]
Fill out the issue template.

Duplicate of https://github.com/martijn00/XamarinMediaManager/issues/437
