### ISSUE TITLE
Working with remote files.

### ISSUE THREAD

**Issue by siwaphatpg** [martijn00/XamarinMediaManager#475]
Mr.Martijn.
I need some description.
I'm new at Xamarim development and I'm developing a Xamarin project to work with media files.
I have tried to play media file (Both of .mp3 and .mp4) with the sample file url in your site project it works well.
But when I come back to work with my project and play with given file URL from local web site look like this ("http://127.0.0.1:1111/Files/xxxx.mp3") but it doesn't work.

I tired 2 ways to give file URL to the CrossMediaManager.Current.Play method.
1.Giving direct URL to that method like this "CrossMediaManager.Current.Play("http://127.0.0.1:1111/Files/xxxx.mp3")".
2. Create a MediaItem object and give their attribute.
    MediaItem mediaItem = new MediaItem("http://127.0.0.1:1111/Files/xxxx.mp3") { MediaType = MediaType.Audio, MediaLocation = MediaLocation.Remote };

Both of these approaches don't work with my project.
Can you let me know how to use your project properly?

**Comment by siwaphatpg** [comment]
I tested a lot of file URLs it works well.
"https://sec.ch9.ms/ch9/84bf/d74cd12c-419b-4333-b74f-1c5e22f284bf/azfr-Malhotra.mp3"
"https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_20mb.mp4"
But for my URL it doesn't work (such as an URL from my local machine).
Please let me know what I have to know before go next.

**Comment by martijn00** [comment]
Do you even have access to the file on the phone or emulator? 127.0.0.1 is not accessible normally. If you want a local file you need to add it as embedded resource, or in a folder in the app project.

**Comment by siwaphatpg** [comment]
Sorry for my bad explanation.
I know I can't access the 127.0.0.1 IP from the emulator.
What I mean is I give binding port to a local website and I can access it from the emulator by using xxx.xxx.xxx.xxx:1111.
That web site has media files that I want to display with your component my code look like this "xxx.xxx.xxx.xxx:1111/Files/xxx.mp3".

Thanks for your response.

**Comment by martijn00** [comment]
I can't say without any details. You should be able to stream any normal mp3 file. Maybe you need to add headers or something?

**Comment by siwaphatpg** [comment]
Thanks I will check it tomorrow.
Is the problem I’m facing just only relating with file header or it is relating with web site configuration too?

**Comment by martijn00** [comment]
As said, you don't give any details, so i can't tell. All my tests work so i suspect there is something wrong in your code.

**Comment by siwaphatpg** [comment]
`CrossMediaManager.Current.Play("http://192.168.220.110:1113/SampleVideo_1280x720_1mb.mp4");`
`CrossMediaManager.Current.Play("https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4");`

I give 2 lines of code that I use to test.
First line doesn't work but second work as I expect.
I still don't know the problem why I can't use my URL.

**Comment by siwaphatpg** [comment]
It seems I can play media files only when I use the URL that has https.
`http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4` <<< This can't play.
'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4' <<< This can.
As you can see both of URL are public.

**Comment by martijn00** [comment]
Both url's play fine for me. Maybe your device is not working?

**Comment by siwaphatpg** [comment]
Do I have to config something?
Is it relating that I use .NET standard project?

**Comment by siwaphatpg** [comment]
[https://github.com/siwaphatpg/XamMediaTest](url)
this is a sample project that I'm testing.
It would be good if you help me determine.
It think I must do something wrong.

**Comment by ihassantariq** [comment]
@martijn00 I am having the same problem with my url which looks like this. 
http://devfra.dev.vms.me:1337/api/files/vms/d4c1b50887315fc2319800da4acdd469_8OJ06GZUT0DGSDSG.mp3

**Comment by ihassantariq** [comment]
@martijn00 can you give me insight on how I can fix this. Every other urls are working.

**Comment by ihassantariq** [comment]
@martijn00 I think issue is related to giving port number.

**Comment by martijn00** [comment]
Can you look at: https://github.com/martijn00/XamarinMediaManager#important under the iOS section? You probably have to take care of ATS. Let me know if that works.

**Comment by ihassantariq** [comment]
Right now, I am not using http, I am using https

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by siwaphatpg** [comment]
@ihassantariq 
Did you solve your problem?
I'm still having the same problem a few day ago I moved to another part of my project.
I will comeback to this issue soon.
Please let me know if someone found the solution for my issue.
This is the most important part of my project.

**Comment by ihassantariq** [comment]
@siwaphatpg No, I have opened an issue. I don't exactly know why it is not working on IOS. Although, its working perfectly in Android.

**Comment by ihassantariq** [comment]
@siwaphatpg here is an issue link. 
https://github.com/martijn00/XamarinMediaManager/issues/486

**Comment by siwaphatpg** [comment]
@ihassantariq 
What kind of web server you are using?
I'm using IIS I don't know that I have to config something additionally?

**Comment by ihassantariq** [comment]
@siwaphatpg mine is based on Node.js. As it is Parse server. Also, I don't have any idea whether do I have to configure additional parameters to file or not.

**Comment by siwaphatpg** [comment]
I have tried to add handle event `Current_MediaItemFailed` to see what happens on my code.
And after I added handle it It see that after I execute this code.
`            var mediaItem = await CrossMediaManager.Current.Play("http://dev.testsite.nat.go.th/SampleVideo_1280x720_1mb.mp4");
            mediaItem.MetadataUpdated += (sender, args) => {
                var title = args.MediaItem.Title;
            };`
It go to the event I have handled.
` private void Current_MediaItemFailed(object sender, MediaManager.Media.MediaItemFailedEventArgs e)
        {
             
        }`
I have to figure out what is clause of problem.
In debug mode I get `{Com.Google.Android.Exoplayer2.ExoPlaybackException}`.

**Comment by ihassantariq** [comment]
@siwaphatpg you defined url is not working for me. Also, I don't get any failure events other than I have described in my issue.

**Comment by siwaphatpg** [comment]
It is local url only working in my PC.
Thank for your spending time to describe me.
If I have something to ask I will come again.

**Comment by siwaphatpg** [comment]
I get error that shows `Java.IO.IOException: Cleartext HTTP traffic to 192.168.220.102 not permitted`

**Comment by siwaphatpg** [comment]
But after I searched how to fix this issue.
Follow this
[cleartext-http-traffic-not-permitted](https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted).
I got an error .
`{System.NullReferenceException: Object reference not set to an instance of an object.
  at MediaManager.MediaManagerImplementation+<Play>d__45.MoveNext () [0x000f7] in C:\Users\mhvdi\Documents\OpenSource\XamarinMediaManager\MediaManager\Platforms\Android\MediaManagerImplementation.cs:159 
--- End of stack trace from previous location where exception was thrown ---`

**Comment by siwaphatpg** [comment]
Thanks for all response from both of you.
My project works as my expectation.
It is my faults that I didn't read enough before doing.

**Comment by thanoue** [comment]
@martijn00  Hi can't play any media flies on IOS app.
I got a HTTPS link that stores an mp4 file on it. It can play on Android, but on IOS  it can't. I tried to download the song to file storage and play from the local file path, but it still had no luck. It's always returns an IMediaItem with duration = 0:00:00. 
Thanks.

**Comment by dawitalemu** [comment]
I am having the last problem that @thanoue is having and I am pulling my hair out here. It used to work just fine few weeks ago, and I am stuck here one day before production release. Works on Android just fine, but iOS gives the above error. @martijn00, please help.
