### ISSUE TITLE
"java.exe" exited with code 2.	MediaManagerStates.Android

### ISSUE THREAD

**Issue by Muthutc** [martijn00/XamarinMediaManager#477]
While i try to debugging i got this Error 

"java.exe" exited with code 2.	MediaManagerStates.Android

**Comment by martijn00** [comment]
Please fill out the issue template, and provide better details.

**Comment by Muthutc** [comment]
> Please fill out the issue template, and provide better details.

While i try to debug an Application its showing

"java.exe" exited with code 2.	MediaManagerStates.Android

**Comment by martijn00** [comment]
You just copied your own post? As said, fill out the proper template.
