### ISSUE TITLE
UWP compilation error "Cannot find type Windows.UI.Xaml.Controls.MediaPlayerElement"

### ISSUE THREAD

**Issue by mikescandy** [martijn00/XamarinMediaManager#479]
## 🔙 Regression

UWP doesn't build.

### Old (and correct) behavior
Up to version 0.5.6 builds correctly

### Current behavior
From version 0.5.7 build fails with the following error:
Xaml Internal Error error WMC9999: Cannot find type Windows.UI.Xaml.Controls.MediaPlayerElement in module Windows.winmd.

### Reproduction steps
1. Create a blank Xamarin.Forms app including UWP
2. Add Mediamanager.Forms to UWP
3. Build UWP
4. Should fail

### Configuration

**Version:** 
Xamarin.Forms 4.0.0.394984-pre10
UWP targets 17134, but it's the same with 16299

**Platform:** 
 - [ X] :earth_americas: UWP

**Comment by martijn00** [comment]
0.6.1 will be available soon and should include a fix. That said playing on UWP is still a bit buggy, so please reports other bugs for uwp as well so i can get it on par with Android and iOS.

**Comment by martijn00** [comment]
@mikescandy can you give it a try and see if it works for you?

**Comment by mikescandy** [comment]
I'm getting this error now:
Payload contains two or more files with the same destination path 'MediaManager\MediaManager.xr.xml'. Source files: 

C:\Users\michele.scandura\.nuget\packages\plugin.mediamanager\0.6.1\lib\uap10.0.16299\MediaManager\MediaManager.xr.xml

C:\Users\michele.scandura\.nuget\packages\plugin.mediamanager.forms\0.6.1\lib\uap10.0.16299\MediaManager\MediaManager.xr.xml	

C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets	1806

Am i doing something wrong here?

**Comment by martijn00** [comment]
@mikescandy hmm interesting. I didn't test it with Forms like that. Let me give that a go.

**Comment by martijn00** [comment]
@mikescandy can you check 0.6.2?

**Comment by mikescandy** [comment]
builds ok! thanks!
now if only collectionview worked on UWP... :)
