### ISSUE TITLE
[Forms][iOS] CrossMediaManager.Current.NotificationManager.Enabled Doesn't seem to respond on iOS

### ISSUE THREAD

**Issue by tehort** [martijn00/XamarinMediaManager#480]
## 🐛 Bug Report

Using the CrossMediaManager.Current.NotificationManager.Enabled on iOS doesn`t seem to respond.
Works fine on Android (huge thanks, by the way)

### Expected behavior
Disable or enable NotificationManager on iOS

### Reproduction steps
Try to disable or enable on Xamarin Forms running on iOS
CrossMediaManager.Current.NotificationManager.Enabled = false;

### Configuration

**Version:** 0.6

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Fixed in 0.6.1
