### ISSUE TITLE
VideoView ShowControls only applied after load

### ISSUE THREAD

**Issue by stntz** [martijn00/XamarinMediaManager#483]
## 🏗 Enhancement Proposal

The video view now shows player controls, sometimes you already have your custom controls and would like to hide the players controls. At the moment, when i set this globally, it throws an exception

CrossMediaManager.Current.MediaPlayer.VideoView.ShowControls = false; 

I can only set it after video view and it works after the first play.

Would be nice to be able to set this globally.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
0.6.2 has a fix for this. Problem is that you could have multiple videoviews that attach to the same player. They can all have their own properties like ShowControls. It should now work to set it before first play.
