### ISSUE TITLE
Play pause not working in 0.4.5 version

### ISSUE THREAD

**Issue by ranjithkumaraa** [martijn00/XamarinMediaManager#490]
void  PlayClicked(object sender, System.EventArgs e)
        {
            await CrossMediaManager.Current.Play();
            CrossMediaManager.Current.Play();
        }
        void PauseClicked(object sender, System.EventArgs e)
        {
            await CrossMediaManager.Current.Pause();
            CrossMediaManager.Current.Pause();
        }

using this method for loading from url 
           await CrossMediaManager.Current.Play("");

its loading and playing, but once we pause its not playing again.

**Comment by martijn00** [comment]
@ranjithkumaraa Update the issue by using an issue template, or it will be closed.

Also only the latest version is supported.
