### ISSUE TITLE
[Forms][iOS] Playing remote url too long to start

### ISSUE THREAD

**Issue by valentin-debris** [martijn00/XamarinMediaManager#491]
## 🐛 Bug Report

Hi Martjn, I'm facing a weird issue with Forms but only for iOS platform. For an App, I have to play a remote url (a radio live stream) which needs to authentificate me. The process we made for security purpose is that I have to call the stream with extra datas (client_id & token, example : https://dummyurl.com/rock.mp3?token=o6fxwaTiw&client_id=2sdfseo04o). Once dummyurl receives the call, it automaticaly call another website (example dummyserver !) to ask it if the user (with this token&client_id) can listen the stream. If dummyserver says Yes, dummyurl starts sending data to https://dummyurl.com/rock.mp3, so the stream can start, otherwise, it returns an error. All this process takes around 0.3s to validate & start the stream. 

For Android, all is good, when calling the URL, the song comes after around 2sec (the buffer I guess). But for iOS, we have to when arround 6-7 sec before having music). 

After a little search in dummyserver, it appears that for iOS, the MediaPlayer call twice the main URL (https://dummyurl.com/rock.mp3?token=o6fxwaTiw&client_id=2sdfseo04o), like if the first time, it has to way to long for a response and retry the call. Do you have any idea why I have this behavior ?

### Expected behavior

iOS should call the URL one time and waits for the stream to begin

### Reproduction steps

Due to the system when develop, I can't create a step to reproduce. But if you want it, I can send you by email accesss to our repo and other access to test it.

### Configuration

**Version:** 0.6.2

**Platform:** 
- [X ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Hard to say why this is. I am looking into some improvements but if you are interested i could provide commercially support.

**Comment by martijn00** [comment]
Is this better in the last release? @valentin-debris

**Comment by valentin-debris** [comment]
@martijn00 ,

The problem seems fixed in the latests releases (I think it was due to the fetchMetaData, but with the changes made about that, no more multilples requests).

Thanks
