### ISSUE TITLE
Able to add a list of MediaItem and play the item in the desire index

### ISSUE THREAD

**Issue by AlenToma** [martijn00/XamarinMediaManager#492]
Hi. I would like to add a list of MediaItem to play and then play the item at the index 3 for example. There is no feature for this. And i really would like it to be. 

maybe this is not a right place to say but i have to trigger Play two time the next time i change MediaQueue. So this is clearly a bug.

And lastly much thx for the greet library you have provided us. and keep upp the good work.

**Comment by martijn00** [comment]
@AlenToma Update the issue by using an issue template, or it will be closed.

**Comment by AlenToma** [comment]
Well i did, I added a  Feature Request

**Comment by martijn00** [comment]
@AlenToma you didn't fill it in. You removed all the items in the template.

**Comment by AlenToma** [comment]
Aha i see ok will do soon, sorry for the trouble

**Comment by martijn00** [comment]
await CrossMediaManager.Current.PlayQueueItem(mediaItem);

Available in 0.6.3

**Comment by AlenToma** [comment]
thx for the fast support
