### ISSUE TITLE
Can't add Plugin.MediaManager.Forms to project

### ISSUE THREAD

**Issue by higher-faster-better** [martijn00/XamarinMediaManager#493]
I tried to add Plugin.MediaManager.Forms package froom NuGet to my project. 
But it shows me error "Unable to get repository signature information for source https://api.nuget.org/v3-index/repository-signatures/4.7.0/index.json".
I can still add Plugin.MediaManager, but Plugin.MediaManager.Forms is not added.

Can you please let me know what is wrong? Thanks

**Comment by martijn00** [comment]
This is unrelated and works for everyone else. Also use the issue templates.
