### ISSUE TITLE
UWP System.NullReferenceException

### ISSUE THREAD

**Issue by MusicPartner** [martijn00/XamarinMediaManager#497]
### Old (and correct) behavior
No Error

### Current behavior
After correct Init in a UWP Xamarin Forms App I allways get System.NullReferenceException when I try to for example:
await CrossMediaManager.Current.Stop()

It works on all other platforms.

### Reproduction steps
await CrossMediaManager.Current.Stop()

### Configuration

**Version:** 0.6.3

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Fixed in 0.6.5
