### ISSUE TITLE
Xamarin Forms[iOS] previous and next buttons missing.

### ISSUE THREAD

**Issue by SatyaRamprasad** [martijn00/XamarinMediaManager#499]
## 🐛 Bug Report

When I play a list of media items, Media player is not showing previous and next buttons.

### Expected behavior
Player should show previous and next buttons.

### Reproduction steps
Play a list of media items

### Configuration

**Version:** 0.6.3

**Platform:** 
- [x] :iphone: iOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Where do you expect those buttons? Can you give more information?

**Comment by SatyaRamprasad** [comment]
Next button next to forward button and Previous button before to backward button.

**Comment by martijn00** [comment]
But where do you expect this? Can you add a screenshot?

**Comment by SatyaRamprasad** [comment]
![image](https://user-images.githubusercontent.com/17923089/59092703-d4e8b700-892f-11e9-962e-6a15067094b3.png)

I need some thing like this for previous and next media items to play

**Comment by martijn00** [comment]
So why don't you just add buttons to the layout then? See for example: https://github.com/martijn00/XamarinMediaManager/pull/473

**Comment by SatyaRamprasad** [comment]
Okay, I will try to add those.
Thanks @martijn00
