### ISSUE TITLE
AndroidMediaPlayer.Init () System.ArgumentNullException: Value cannot be null. Parameter name: MediaSession

### ISSUE THREAD

**Issue by SatyaRamprasad** [martijn00/XamarinMediaManager#500]
## 🐛 Bug Report

AndroidMediaPlayer.Init ()
System.ArgumentNullException: Value cannot be null. Parameter name: MediaSession

AndroidMediaPlayer.Init ()
AndroidMediaPlayer.get_Player ()
MediaPlayerExtensions.SetPlayerView (MediaManager.IMediaPlayer mediaPlayer, MediaManager.Platforms.Android.Video.VideoView videoView)
VideoViewRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] args)
VisualElementRenderer`1[TElement].SetElement (TElement element)
IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element)
Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context)
VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren)
VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement)
VisualElementPackager.Load ()
VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager)
VisualElementRenderer`1[TElement].SetElement (TElement element)
IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element)
Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context)
VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren)
VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement)
VisualElementPackager.Load ()
VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager)
VisualElementRenderer`1[TElement].SetElement (TElement element)
IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element)
Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context)
VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren)
VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement)
VisualElementPackager.Load ()
VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager)
VisualElementRenderer`1[TElement].SetElement (TElement element)
IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element)
Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context)
ScrollViewContainer.set_ChildView (Xamarin.Forms.View value)
ScrollViewRenderer.LoadContent ()
ScrollViewRenderer.SetElement (Xamarin.Forms.VisualElement element)
Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context)
VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren)
VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement)
VisualElementPackager.Load ()
VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager)
VisualElementRenderer`1[TElement].SetElement (TElement element)
IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element)
Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context)
VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren)
VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement)
VisualElementPackager.Load ()
VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager)
VisualElementRenderer`1[TElement].SetElement (TElement element)
IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element)
Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Support.V4.App.FragmentManager fragmentManager, Android.Content.Context context)
FragmentContainer.OnCreateView (Android.Views.LayoutInflater inflater, Android.Views.ViewGroup container, Android.OS.Bundle savedInstanceState)
Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_inflater, System.IntPtr native_container, System.IntPtr native_savedInstanceState)

### Expected behavior
App should work without crashing 

### Reproduction steps
1. Open the app for sometime and close the app or Press back button to close the app.
2.Getting Media Session is null exception

### Configuration

**Version:** 0.6.7

**Platform:** 
- [x] :robot: Android
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
I'll add some fixes for this in the next release.

**Comment by Pujolsluis** [comment]
Hey @martijn00 , just wanted to report I'm having the same problem👍

**Comment by martijn00** [comment]
@Pujolsluis I've already added a fix for this in develop. I need to finish up some other things before i can make a release.

**Comment by Pujolsluis** [comment]
Great! Thanks for your hard work @martijn00🙌

**Comment by khairnar** [comment]
> @Pujolsluis I've already added a fix for this in develop. I need to finish up some other things before i can make a release.

Please publish changes, Thanks

**Comment by martijn00** [comment]
0.6.8 is online now.

**Comment by SatyaRamprasad** [comment]
Hi @martijn00 , Still i am getting same issue in 0.7.1

**Comment by SatyaRamprasad** [comment]
Hi @Pujolsluis Is it working fine for you or getting the issue?
