### ISSUE TITLE
MediaItemChanged is firing multiple times for every media item

### ISSUE THREAD

**Issue by SatyaRamprasad** [martijn00/XamarinMediaManager#501]
## 🐛 Bug Report

MediaItemChanged is firing multiple times for every media item

### Expected behavior
MediaItemChanged should fire single time for media item

### Reproduction steps
steps:
1.pass a list of items to player.
2.check MediaItemChanged
3. MediaItemChanged gets fired multiple times
4.if not reproduced, try 1 and 2 steps multiple times

### Configuration

**Version:** 0.6.7

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
I'll look into this. Thanks for reporting.

**Comment by SatyaRamprasad** [comment]
Hi @martijn00 Any update on this bug?
Thanks in advance
