### ISSUE TITLE
PlayPause() control is not working Properly in 0.6.7

### ISSUE THREAD

**Issue by Muthutc** [martijn00/XamarinMediaManager#504]
## 🐛 Bug Report

If a song is paused, and you un-pause it by calling
`await CrossMediaManager.Current.PlayPause()`, the song starts over from the beginning instead of continuing where it left off.
Please Help me out..

### Configuration
Version 0.6.7

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by sis2004** [comment]
I have noticed the same issue. It seems to have started from version 0.6.4 published to NuGet.

Interestingly, the last release on GitHub is still 0.6.3, so it's not clear why the latest versions have been published to NuGet without making a release on GitHub.

**Comment by Muthutc** [comment]
Hi @martijn00 Please take a look.

**Comment by martijn00** [comment]
Fixed in 0.6.8

**Comment by Muthutc** [comment]
Awesome!@martijn00
