### ISSUE TITLE
Question about ability to play resources (on Android)

### ISSUE THREAD

**Issue by speaker** [martijn00/XamarinMediaManager#505]
## 💬 Questions and Help

I currently use MediaPlayer and a selector intent to play local media and embedded resources and have had significant difficulty finding how to replace this capability using XMM.  Is there an example or explanation of how these are accomplished with XMM?

e.g.
To play a local resource currently on android:
static MediaPlayer _player = MediaPlayer.Create(Forms.Context, Resource.Raw.DefaultMusic);
_player.Start();

**Comment by martijn00** [comment]
Try again in 0.7.5 and let me know if it works.

You should get the resource url and pass that to play.
