### ISSUE TITLE
Loading / Busy Indicator

### ISSUE THREAD

**Issue by jrahma** [martijn00/XamarinMediaManager#506]
## 🚀 Feature Requests

Show a Busy Indicator / Animated Loading Image while Video is buffering or loading

### Contextualize the feature
This will help to tell the user that there is something is loading because the current doesn't show anything and user assumes there is nothing started so they click Play button again

### Describe the feature
When the control loads with a video then on the player user will see an animated loading image. They can choose the type of animation, e.g. Gear, Globe, Circle, etc..

### Platforms affected (mark all that apply)
- [ X] :iphone: iOS
- [ X] :robot: Android
- [ X] :checkered_flag: WPF
- [ X] :earth_americas: UWP
- [ X] :apple: MacOS
- [ X] :tv: tvOS
- [ X] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
@jrahma please fill in a proper issue template, or this will be closed.

**Comment by jrahma** [comment]
## 🚀 Feature Requests


Show a Busy Indicator / Animated Loading Image while Video is buffering or loading

### Contextualize the feature
This will help to tell the user that there is something is loading because the current doesn't show anything and user assumes there is nothing started so they click Play button again

### Describe the feature
When the control loads with a video then on the player user will see an animated loading image. They can choose the type of animation, e.g. Gear, Globe, Circle, etc..

### Platforms affected (mark all that apply)
- [ X] :iphone: iOS
- [ X] :robot: Android
- [ X] :checkered_flag: WPF
- [ X] :earth_americas: UWP
- [ X] :apple: MacOS
- [ X] :tv: tvOS
- [ X] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
You can add the indicator to your own layout and bind it to a Buffering property.

**Comment by jrahma** [comment]
Where can I find the doc for this please?

I tried:

```
CrossMediaManager.Current.BufferedChanged += (sender, e) =>
{
    Console.WriteLine(e.Buffered.ToString());
};

```
but getting:

> 'IMediaManager' does not contain a definition for 'PlayingChanged' and no accessible extension method 'PlayingChanged' accepting a first argument of type 'IMediaManager' could be found (are you missing a using directive or an assembly reference?)

**Comment by martijn00** [comment]
Maybe do a clean? Doesn't sound like this is a problem in MediaManager

**Comment by jrahma** [comment]
this looks working for me

```
CrossMediaManager.Current.StateChanged += (sender, e) =>
{
    if (e.State == MediaManager.Playback.MediaPlayerState.Buffering)
    {
        VideoViewWelcome.IsVisible = false;
        loadingWelcome.IsVisible = true;
    }
    else if (e.State == MediaManager.Playback.MediaPlayerState.Playing)
    {
        loadingWelcome.IsVisible = false;
        VideoViewWelcome.IsVisible = true;
    }
};

```
