### ISSUE TITLE
How to play a local embedded file on Android / IOS without platform specific code?

### ISSUE THREAD

**Issue by CurtisHerrick** [martijn00/XamarinMediaManager#507]
I would like to embed a file named electronic_chime.mp3 in my Android and IOS projects and play them using Xamarin MediaManager.

All the solutions I see to locating local files seem to use platform specific code.  How can I access this same-named file on Andriod and IOS without having to code specifically for Android or IOS?

I see that on IOS, I should put the file inside Resources, and on Android I should put the same named file in Assets (and set it with buildaction 'Embedded Resource').
So far on Android, I've tried accessing the file with paths "electronic_chime", "electronic_chime.mp3", "file://electronic_chime.mp3", not working.

On each platform: IOS and Android - where do I put the file, how should I set it to be embedded, and what is a URI string or code that I can use that would work on both platforms?

**Comment by JigarM** [comment]
+1

**Comment by martijn00** [comment]
Try again in 0.7.5 and let me know if it works

**Comment by CurtisHerrick** [comment]
As you've coded/fixed, and tested this feature, do you have handy the code that one should use with this component to play an embedded audio file on IOS and Android?  I'll likely be able to figure it out, but for the user community can you provide it?  That said, thanks for fixing the issue!  It's on my backlog now to apply the update and get it fixed in my app.

**Comment by martijn00** [comment]
I'll add some docs on this later.

**Comment by CurtisHerrick** [comment]
Ok thanks!

- Curtis
via phone gmail
