### ISSUE TITLE
VideoView shows a blank video but doesn't load source in Android.

### ISSUE THREAD

**Issue by StevenGranados** [martijn00/XamarinMediaManager#508]
## 🐛 Bug Report

I have a VideoView and I when it gets loaded I end up with a blank black box with controls. The play button and skip to beginning buttons flicker.
![tempsnip](https://user-images.githubusercontent.com/51818199/60273658-80ad7300-98ee-11e9-8fbc-88bf8171661d.png)
If I exit the app I can play the video audio in the notification bar.
The following errors loop.

06-27 14:04:35.639 V/MediaHTTPService( 7855): MediaHTTPService(android.media.MediaHTTPService@81af46c): Cookies: null
06-27 14:04:35.657 V/MediaHTTPService( 7855): makeHTTPConnection: CookieHandler (java.net.CookieManager@1a6fedc) exists.
06-27 14:04:35.657 V/MediaHTTPService( 7855): makeHTTPConnection(android.media.MediaHTTPService@81af46c): cookieHandler: java.net.CookieManager@1a6fedc Cookies: null
06-27 14:04:35.727 E/MediaMetadataRetrieverJNI( 7855): getEmbeddedPicture: Call to getEmbeddedPicture failed.
06-27 14:04:36.206 V/MediaHTTPService( 7855): MediaHTTPService(android.media.MediaHTTPService@fc772a0): Cookies: null
06-27 14:04:36.208 V/MediaHTTPService( 7855): makeHTTPConnection: CookieHandler (java.net.CookieManager@1a6fedc) exists.
06-27 14:04:36.208 V/MediaHTTPService( 7855): makeHTTPConnection(android.media.MediaHTTPService@fc772a0): cookieHandler: java.net.CookieManager@1a6fedc Cookies: null
06-27 14:04:36.342 I/OpenGLRenderer( 7855): Davey! duration=3561ms; Flags=0, IntendedVsync=9050861039694, Vsync=9053711039580, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=9053717294200, AnimationStart=9053717357400, PerformTraversalsStart=9053717414800, DrawStart=9053721990200, SyncQueued=9053722413800, SyncStart=9053722464600, IssueDrawCommandsStart=9053722565000, SwapBuffers=9054415801400, FrameCompleted=9054422278900, DequeueBufferDuration=116000, QueueBufferDuration=599000, 
06-27 14:04:36.560 W/ks.ChatUIXForm( 7855): Long monitor contention with owner Thread-7 (7883) at java.net.InetAddress[] libcore.io.Linux.android_getaddrinfo(java.lang.String, android.system.StructAddrinfo, int)(Linux.java:-2) waiters=0 in int android.media.MediaHTTPConnection.readAt(long, byte[], int) for 614ms
06-27 14:04:37.178 I/OpenGLRenderer( 7855): Davey! duration=1301ms; Flags=0, IntendedVsync=9053803714001, Vsync=9054237047317, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=9054239286200, AnimationStart=9054239351700, PerformTraversalsStart=9054239408900, DrawStart=9054258791900, SyncQueued=9054274057800, SyncStart=9054427104200, IssueDrawCommandsStart=9054458605500, SwapBuffers=9055227793100, FrameCompleted=9055258294700, DequeueBufferDuration=125000, QueueBufferDuration=5667000, 
06-27 14:04:37.513 I/Choreographer( 7855): Skipped 78 frames!  The application may be doing too much work on its main thread.
06-27 14:04:37.533 V/MediaHTTPService( 7855): MediaHTTPService(android.media.MediaHTTPService@4335a3d): Cookies: null
06-27 14:04:37.544 V/MediaHTTPService( 7855): makeHTTPConnection: CookieHandler (java.net.CookieManager@1a6fedc) exists.
06-27 14:04:37.544 V/MediaHTTPService( 7855): makeHTTPConnection(android.media.MediaHTTPService@4335a3d): cookieHandler: java.net.CookieManager@1a6fedc Cookies: null
06-27 14:04:37.577 E/MediaMetadataRetrieverJNI( 7855): getEmbeddedPicture: Call to getEmbeddedPicture failed.
06-27 14:04:37.697 E/MediaMetadataRetrieverJNI( 7855): getEmbeddedPicture: Call to getEmbeddedPicture failed.
06-27 14:04:37.889 E/MediaMetadataRetrieverJNI( 7855): getEmbeddedPicture: Call to getEmbeddedPicture failed.
06-27 14:04:37.920 E/MediaMetadataRetrieverJNI( 7855): getEmbeddedPicture: Call to getEmbeddedPicture failed.
06-27 14:04:38.115 I/Choreographer( 7855): Skipped 34 frames!  The application may be doing too much work on its main thread.
06-27 14:04:38.152 V/MediaHTTPService( 7855): MediaHTTPService(android.media.MediaHTTPService@53ff95c): Cookies: null
06-27 14:04:38.168 V/MediaHTTPService( 7855): makeHTTPConnection: CookieHandler (java.net.CookieManager@1a6fedc) exists.
06-27 14:04:38.169 V/MediaHTTPService( 7855): makeHTTPConnection(android.media.MediaHTTPService@53ff95c): cookieHandler: java.net.CookieManager@1a6fedc Cookies: null

### Expected behavior
Get an embedded video playing.

**Version:** 0.6.7

**Platform:** 
- [ ] :robot: Android
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Try again in 0.7.5 and let me know if it works

**Comment by StevenGranados** [comment]
Thanks for the update :). I have a simple demonstration with a single videoview in a stacklayout that failed before and now it works, so I guess the bug is fixed. However in the more complex messaging app project, the video doesn't draw in both Android and iOS. Not much to show as it just doesn't appear. No error or warnings of note, however the audio plays and I can control the video in the notification bar. I guess it's a layout issue. I am making use of DataLayouts, carouselpages, collectionview and grid. I might create a new bug if I can't get to the bottom of it.
