### ISSUE TITLE
[iOS] Notification play not working

### ISSUE THREAD

**Issue by valentin-debris** [martijn00/XamarinMediaManager#515]
## 🔙 Regression

On iOS, when we press the play/pause button, the icon changes but the player is still playing

### Old (and correct) behavior
When press pause button, the song should pause.
When press play butoon, the song should play where it was paused

### Current behavior
The player keeps playing the song

### Configuration

**Version:** 0.6.7

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Can you try with 0.6.8? It seems to work for me. It is out on nuget now.

**Comment by valentin-debris** [comment]
@martijn00 , I tried with the latest version and it's still not working on iOS. Here a repo for reproduce https://github.com/valentin-debris/XamarinMediaDebug/tree/0.6.8-stop_player

**Comment by valentin-debris** [comment]
@martijn00 , after debugging the Media Player, I found own to make the notif working.
I have to set **CrossMediaManager.Current.NotificationManager.ShowPlayPauseControls = true.** 
It's confusing because without it, the buttons are visible and clickable, but there are no callbacks assign I guess. And for Android, it works without adding this line.

**Comment by BuddyLReno** [comment]
I set `CrossMediaManager.Current.NotificationManager.ShowPlayPauseControls = true` when I started playing audio, but it didn't work for me. Waiting for the changes merged in #535 to hopefully help with this issue.

**Comment by martijn00** [comment]
@valentin-debris can you check again with 0.7.4?

**Comment by BuddyLReno** [comment]
Verified that 0.7.4 worked for me without the additional line. 👍

**Comment by adambarath** [comment]
I can also verify, this feature works properly on my side.

**Comment by adambarath** [comment]
Seems OK.

**Comment by cklenk** [comment]
For anyone else having issues on 0.7.3, setting ShowPlayPauseControls to true worked on iOS 12.4

Thanks
