### ISSUE TITLE
Can't dismiss notification of paused media

### ISSUE THREAD

**Issue by rrispoli** [martijn00/XamarinMediaManager#517]
## 🐛 Bug Report

I want to be able to dismiss the notification when the content is Paused, just like the Spotify app, but the notification only disappear if I click in Stop notification command.

Here a sample gif of Spotify app: https://media.giphy.com/media/iFaWBSDZfLbWKD9fi4/source.mp4

### Expected behavior
The notification allow to be canceled if the media is Paused.

### Reproduction steps
1) Play some audio/video.
2) Click on Pause notification command.
3) Try to dismiss the notification.

### Configuration

**Version:** 0.6.7

**Platform:** 
- [ ] :iphone: iOS
- [x ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by valentin-debris** [comment]
@rrispoli , 

This is not a bug, as the default behavior for pausing is to keep the notif, so the user can re-play the song. It's like that for all the app, Spotify as well

**Comment by rrispoli** [comment]
Here the Spotify app allow to dismiss the notification if the audio is Paused.

**Comment by valentin-debris** [comment]
> Here the Spotify app allow to dismiss the notification if the audio is Paused.

My bad, I thought you were asking to remove it automatically.

**Comment by rrispoli** [comment]
I upload a sample gif here: https://media.giphy.com/media/iFaWBSDZfLbWKD9fi4/source.mp4

**Comment by martijn00** [comment]
https://github.com/martijn00/XamarinMediaManager/blob/develop/MediaManager/Platforms/Android/Notifications/NotificationManager.cs#L16 You can use `SetCancelable(true)` on that property.

Not sure if it is worth making something cross platform for this. I think it only exists on Android?

**Comment by rrispoli** [comment]
Hi @martijn00 I can't find SetCancelable method in PlayerNotificationManager.

I really don't know if it exists only in Android, but I tested some Android apps and all have this feature, to allow dismiss notification if media is Paused.

My problem is that in old Android versions, the notification only show Play/Pause button visible and too see the Stop button, user need do click the small arrow down to expand the notification, but many people don't know about it and can't dismiss the notification except if press Stop inside the app player. Here some screenshots: https://i.imgur.com/K6gkn7d.jpg

**Comment by martijn00** [comment]
@rrispoli (CrossMediaManager.Android.NotificationManager as MediaManager.Platforms.Android.Notifications.NotificationManager).PlayerNotificationManager.SetOngoing(false);

**Comment by rrispoli** [comment]
@martijn00 I make some tests, but can't dismiss the notification too. Here the code I've used in my Android project:
```
CrossMediaManager.Current.StateChanged += (s, e) =>
{
	if (e.State != MediaPlayerState.Buffering && e.State != MediaPlayerState.Failed && CrossMediaManager.Current.MediaQueue.Current != null && CrossMediaManager.Current.MediaQueue.Current.MediaType == MediaType.Audio)
	{
		var playerNotificationManager = (CrossMediaManager.Android.NotificationManager as MediaManager.Platforms.Android.Notifications.NotificationManager).PlayerNotificationManager;
		if (playerNotificationManager != null)
		{
			//playerNotificationManager.SetOngoing(e.State != MediaPlayerState.Paused);
			playerNotificationManager.SetOngoing(false);
		}
	}

};
```

**Comment by martijn00** [comment]
What about:

```
var intent = new Intent(ApplicationContext, Java.Lang.Class.FromType(typeof(MediaManager.Platforms.Android.MediaSession.MediaBrowserService));
            StopService(intent);
```

From your activity when the state is changed to pause?

**Comment by rrispoli** [comment]
@martijn00 tested here, not working too. There is a way to do this? https://github.com/google/ExoPlayer/issues/4256#issuecomment-388936681

**Comment by martijn00** [comment]
The essential part for me is the 3th. I can figure out how to start the notification again at the moment. See here: https://github.com/martijn00/XamarinMediaManager/commit/01f0b0dff4fd4a9dda188583a1b6d296b42e6dd0#diff-744ab47974856b1e866d6b4a1c23f92fR55

**Comment by rrispoli** [comment]
I see your code now, StartForeground and StopForeground is working?

**Comment by martijn00** [comment]
Yeah those are working. But if you would pause, then hit play again, the notification is still dismissible. The case should be that when you hit play again, it should not be able to swipe away until you pause.

**Comment by rrispoli** [comment]
@martijn00 you are calling StartForeground(), but if you call StartForeground(notificationId, notification) ?

**Comment by martijn00** [comment]
StartForeground() is not valid. That's why it is commented out. StartForeground(notificationId, notification) is not possible because I don't have access to the notification, because exoplayer manages that internally.

**Comment by rrispoli** [comment]
@martijn00 in OnNotificationStartedImpl = (notificationId, notification) it is possible to store "notification" in a Notification property and, when Notification != null use this StartForeground(ForegroundNotificationId, Notification) ?

**Comment by martijn00** [comment]
I've implemented the changes for this, but for some weird reason it doesn't work: https://github.com/martijn00/XamarinMediaManager/commit/fc7f309ffa33bf3cf61fb3e4b56db914239c92a7#diff-744ab47974856b1e866d6b4a1c23f92fR80

The StopForeground(false); after pause does not make it able to swipe away.

**Comment by rrispoli** [comment]
@martijn00 I see here, your code should work. According to this https://github.com/google/ExoPlayer/issues/5792#issuecomment-486269001, the StopForeground(false); after pause should allow the user dismiss the notification.

**Comment by martijn00** [comment]
It seems like some methods are missing in the ExoPlayer bindings because they use default interfaces. That makes it a little bit harder, but it should work now. I've released 0.7.0 so you can give it a try.

**Comment by rrispoli** [comment]
Great, I'll make some tests.

**Comment by rrispoli** [comment]
@martijn00 I did some tests and it seems to be working!

**Comment by rrispoli** [comment]
@martijn00 after release for other people test, this exception is occurring many times in Android Pie 9.0 and the app crash, the only information in Google Play fail reports is:

```
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{md5bc84c97450f22337f6e1991a43223866.MediaBrowserService}
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1745)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6718)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by martijn00** [comment]
@rrispoli This seems to be related to https://stackoverflow.com/questions/44425584/context-startforegroundservice-did-not-then-call-service-startforeground

Do you know how i can reproduce this? Please also open a new issue for this so i can track it.

**Comment by rrispoli** [comment]
I really don't know how to reproduce this. In my device with Android 7.1.2 the app works fine.

**Comment by rrispoli** [comment]
@martijn00 here the issue, I think it is related: https://github.com/martijn00/XamarinMediaManager/issues/522
