### ISSUE TITLE
java.exe exited with code 2

### ISSUE THREAD

**Issue by zmklark** [martijn00/XamarinMediaManager#518]
## 💬 Questions and Help

Xamarin.Android.Common.targets(1783,2): warning XA0106: Skipping FastBusinessShop.Droid.Resource.Style.Platform_V14_AppCompat_Light. Please check that your Nuget Package versions are compatible.

Getting error "java.exe exited with code 2"

**Comment by valentin-debris** [comment]
@zmklark ,
Nobody can help you without so less informations ! And it doesn't show anything related to this nuget. Please, use the template and give more information related to MediaManager.
