### ISSUE TITLE
Notifications show wrong play/pause/etc. buttons

### ISSUE THREAD

**Issue by RichardSV15** [martijn00/XamarinMediaManager#519]
### Expected behavior
Notification with proper buttons. Currently showing foward button for play/puase and once expanded it's ordered (Pause|Forward|Play|Play) 

and it should be (Play/Pause) and once expanded (back|Play/Pause|forward|Stop)

buttons work like they should, they just show the wrong image

### Reproduction steps
run 
await CrossMediaManager.Current.Play(item.url);

where item.url is an mp3 url file

### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
I can't reproduce this on the ElementPlayer sample. Please provide more information and a url.

**Comment by RichardSV15** [comment]
> I can't reproduce this on the ElementPlayer sample. Please provide more information and a url.

the url is a firebase storage url: 
https://firebasestorage.googleapis.com/v0/b/los-networks.appspot.com/o/audios%2FCTD002?alt=media&token=5a3a81a2-aa44-45b4-843a-c20eeee3c87d

The way I play it:

IMediaItem mMedia = await CrossMediaManager.Current.Play(item.url);
mMedia.Title = item.title;
mMedia.MediaId = item.key;
mMedia.Author = item.author;
etc...

here's two photos of how it looks on android using Xamarin.Forms... *haven't test on IOS*

![20190704_172859](https://user-images.githubusercontent.com/49900619/60691055-89b7ba80-9e81-11e9-9a38-1b0a712f92e4.jpg)
![20190704_172842](https://user-images.githubusercontent.com/49900619/60691058-8e7c6e80-9e81-11e9-9de6-3dd0c7b68b0e.jpg)

**Comment by martijn00** [comment]
I still can't reproduce this. Please make a repo and put it on Github so it is clear what you are doing.

Also try to use `CrossMediaManager.Current.NotificationManager.ShowNavigationControls` to show controls or not and `CrossMediaManager.Current.NotificationManager.UpdateNotification()` after changing metadata.
