### ISSUE TITLE
[Forms][Android] Wrong state returned when stop

### ISSUE THREAD

**Issue by valentin-debris** [martijn00/XamarinMediaManager#521]
## 🔙 Regression

When stopping the player using the notification or the function .Stop(), CrossMediaManager.Current.StateChanged return Loading instead of Stop state.

### Old (and correct) behavior

MediaManager.Playback.StateChangedEventArgs should return Stop

### Current behavior

MediaManager.Playback.StateChangedEventArgs return Loading

### Configuration

**Version:** 0.7.0

**Platform:** 
- [ ] :iphone: iOS NOT TESTED
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Fixed in 0.7.1
