### ISSUE TITLE
MediaItemFinished is not working in 0.7.1

### ISSUE THREAD

**Issue by rrispoli** [martijn00/XamarinMediaManager#525]
## 🔙 Regression

I was using MediaManager 0.6.7 with ExoPlayer 2.8.8 and the MediaItemFinished event was working normally. When I update MediaManager to 0.7.1 with ExoPlayer 2.9.6 it is not working anymore.

### Old (and correct) behavior

MediaItemFinished event work when media finish.

### Current behavior

MediaItemFinished event is not working anymore when media finish.

### Reproduction steps

Just add this code, play some media and wait it finish:

```
CrossMediaManager.Current.MediaItemFinished += (s, e) =>
{
	//your code...
};
```

### Configuration

**Version:** 0.7.1

**Platform:** 
- [ ] :iphone: iOS
- [x ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
This is a bit weird. This line https://github.com/martijn00/XamarinMediaManager/blob/develop/MediaManager/Platforms/Android/Player/AndroidMediaPlayer.cs#L166 is not called anymore. The other states are called, but not StateEnded.

**Comment by rrispoli** [comment]
@martijn00 look this please https://stackoverflow.com/a/49316029

**Comment by martijn00** [comment]
Yes i already use Player.STATE_ENDED so that is not the case.

**Comment by martijn00** [comment]
0.7.2 should contain a fix for this. Can you test?

**Comment by rrispoli** [comment]
I made some tests here with 0.7.2 and ExoPlayer 2.9.7, but MediaItemFinished still not working. In my app I always have only one item on queue. This should work? https://github.com/martijn00/XamarinMediaManager/blob/develop/MediaManager/Platforms/Android/Player/AndroidMediaPlayer.cs#L208

**Comment by martijn00** [comment]
Hmm right. My assumption was that there were more than 1 item. Strange, i have to look into another fix.

**Comment by martijn00** [comment]
Can you test again with 0.7.3?

**Comment by rrispoli** [comment]
Yes, I'll make some tests right now.

**Comment by rrispoli** [comment]
Hi @martijn00 it is working in 0.7.3, thanks!
