### ISSUE TITLE
defining a default interface method requires --min-sdk-version >= 24

### ISSUE THREAD

**Issue by jrahma** [martijn00/XamarinMediaManager#526]
Hi,

I upgraded to the latest MediaManager and then started getting:

> java/lang/Object;I)V: defining a default interface method requires --min-sdk-version >= 24 (currently 13) for interface methods: com.google.android.exoplayer2.Player$EventListener.onTimelineChanged : (Lcom/google/android/exoplayer2/Timeline;Ljava/lang/Object;I)V

Now I downgraded to get rid of this error but still getting the same error!

This is my AndroidManifest:

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="100" android:versionName="1.0" package="com.jafaria.app" android:installLocation="auto">
	<uses-sdk android:minSdkVersion="28" android:targetSdkVersion="28" />
	<application android:label="الأوقاف الجعفرية" android:icon="@drawable/icon" android:supportsRtl="true" android:largeHeap="true">
		<!-- Set default notification icon and color. -->
		<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/ic_notification" />
		<!-- <meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@color/notification" /> -->
		<!-- remove these lines -->
	</application>
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
	<uses-permission android:name="android.permission.ACCESS_MOCK_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.MEDIA_CONTENT_CONTROL" />
	<uses-permission android:name="android.permission.WAKE_LOCK" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
</manifest>

```

**Comment by jrahma** [comment]
It only worked with version 6.9

**Comment by martijn00** [comment]
ExoPlayer 2.9.6 and higher use Java 8. You need to set the Dex tool to D8 <AndroidDexTool>d8</AndroidDexTool>

See: https://github.com/martijn00/XamarinMediaManager#important

**Comment by martijn00** [comment]
Duplicate of https://github.com/martijn00/XamarinMediaManager/issues/524

**Comment by RKamoha** [comment]
Dear @martijn00, thank you for your valuable work!

 - I have exactly same issue, however I do not understand your answer at all.

I haveNew everything:
new Visual Studio 2019
new Xamarin Forms App
new Installed Plugin.Media Manager 0.8.18 

Result is the reported error (on compilation) reported in this thread:

Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error		java/lang/Object;I)V: defining a default interface method requires --min-sdk-version >= 24 (currently 13) for interface methods: com.google.android.exoplayer2.Player$EventListener.onTimelineChanged : (Lcom/google/android/exoplayer2/Timeline;Ljava/lang/Object;I)V

Where do we find and set:
ExoPlayer 2.9.6 and higher use Java 8. You need to set the Dex tool to D8 d8

Shall I install ExoPlayer? Where do I find the key:<AndroidDexTool></AndroidDexTool> ? In what project and file?

At a dead end without your help.

thanks!
