### ISSUE TITLE
[UWP] PositionChanged is missing

### ISSUE THREAD

**Issue by joseluisct** [martijn00/XamarinMediaManager#527]
## 🐛 Bug Report
MediaManager PositionChanged event implementation is missing in UWP. Same issue with WPF.

It's necessary to modify class WindowsMediaPlayer.cs with this code:

      public void Initialize()
      {
          Player = new MediaPlayer();
          Player.MediaEnded += Player_MediaEnded;
          Player.MediaFailed += Player_MediaFailed;
          Player.PlaybackSession.BufferingProgressChanged += PlaybackSession_BufferingProgressChanged;
          Player.PlaybackSession.PlaybackStateChanged += PlaybackSession_PlaybackStateChanged;
          Player.PlaybackSession.PositionChanged += PlaybackSession_PositionChanged;
      }

      private void PlaybackSession_PositionChanged(MediaPlaybackSession sender, object args)
      {
            MediaManager.OnPositionChanged(this, new PositionChangedEventArgs(sender.Position));
      }

      public void Dispose()
      {
          Player.MediaEnded -= Player_MediaEnded;
          Player.MediaFailed -= Player_MediaFailed;
          Player.PlaybackSession.PlaybackStateChanged -= PlaybackSession_PlaybackStateChanged;
          Player.PlaybackSession.PositionChanged -= PlaybackSession_PositionChanged;
          Player.Dispose();
          Player = null;
      }

### Expected behavior
Subscribe to PositionChanged event and get notified when position changes.

### Reproduction steps
Subscribe to event:  CrossMediaManager.Current.PositionChanged
Play an item: await CrossMediaManager.Current.Play(item.url);

### Configuration
**Version:** 0.7.1

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [x] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

### Reproduction Link
https://github.com/joseluisct/MediaManagerIssue

**Comment by martijn00** [comment]
Position is set in the base: https://github.com/martijn00/XamarinMediaManager/blob/develop/MediaManager/MediaManagerBase.cs#L249

I'm not sure why that wouldn't trigger for you. Any ideas? I'm thinking in the future using the PositionChanged in uwp might be better, but it should already work for now.

**Comment by joseluisct** [comment]
Then I think it's an issue with base class, I've tested it with WPF and event PositionChanged doesn't fire either.

I've created a test repo with UWP and WPF projects to see this issue, with version 0.7.2:
https://github.com/joseluisct/MediaManagerIssue

**Comment by martijn00** [comment]
You are not calling Init anywhere. That's why this fails. I'll maybe add some sort of error message for this to make it more explicit.

**Comment by joseluisct** [comment]
I've called Init at native projects and with UWP it is working OK. I am migrating from old version and I didn't know it.

But with WPF it still fails, I can open a new issue with this.
I've updated test repo with the changes. Thank you.
