### ISSUE TITLE
AndroidMediaPlayer.Initialize () System.ArgumentNullException: MediaSession cannot be null. Make sure the MediaBrowserService sets it up Parameter name: MediaSession

### ISSUE THREAD

**Issue by SatyaRamprasad** [martijn00/XamarinMediaManager#528]
## 🐛 Bug Report
AndroidMediaPlayer.Initialize () System.ArgumentNullException: MediaSession cannot be null. Make sure the MediaBrowserService sets it up Parameter name: MediaSession

Here is the stack trace found in App center :
AndroidMediaPlayer.Initialize ()
AndroidMediaPlayer.get_Player ()
AndroidMediaPlayer.set_VideoView (MediaManager.Video.IVideoView value)
VideoViewRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] args)
VisualElementRenderer`1[TElement].SetElement (TElement element)
IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element)
Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context)
VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren)
VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement)
VisualElementPackager.Load ()
VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager)
VisualElementRenderer`1[TElement].SetElement (TElement element)
IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element)
Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context)
VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren)
VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement)
VisualElementPackager.Load ()
VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager)
VisualElementRenderer`1[TElement].SetElement (TElement element)
IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element)
Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context)
VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren)
VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement)
VisualElementPackager.Load ()
VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager)
VisualElementRenderer`1[TElement].SetElement (TElement element)
IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element)
Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context)
ScrollViewContainer.set_ChildView (Xamarin.Forms.View value)
ScrollViewRenderer.LoadContent ()
ScrollViewRenderer.SetElement (Xamarin.Forms.VisualElement element)
Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context)
VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren)
VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement)
VisualElementPackager.Load ()
VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager)
VisualElementRenderer`1[TElement].SetElement (TElement element)
IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element)
Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context)
VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren)
VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement)
VisualElementPackager.Load ()
VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager)
VisualElementRenderer`1[TElement].SetElement (TElement element)
IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element)
Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Support.V4.App.FragmentManager fragmentManager, Android.Content.Context context)
FragmentContainer.OnCreateView (Android.Views.LayoutInflater inflater, Android.Views.ViewGroup container, Android.OS.Bundle savedInstanceState)
Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_inflater, System.IntPtr native_container, System.IntPtr native_savedInstanceState)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.74(intptr,intptr,intptr,intptr,intptr)
### Expected behavior
App should work properly without crashing

### Reproduction steps
1. Play a media item.
2. Close the app.
3. Re-open the app, then app crashes and getting Media Session null exception.

### Configuration

**Version:** 0.7.2

**Platform:** 
- [x] :robot: Android
- [x] :monkey: Xamarin.Forms

**Comment by jongallion** [comment]
I am also seeing this same error with 0.7.2

**Comment by jrahma** [comment]
I am getting similar on Android:

> 07-13 03:42:50.977 E/mono-rt (16863): [ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentNullException: Value cannot be null.
> 07-13 03:42:50.977 E/mono-rt (16863):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.31(intptr,intptr,intptr)
> 07-13 03:42:50.977 E/mono-rt (16863):   at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.31(intptr,intptr,intptr)
> FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7d413fcd40)
> 07-13 03:42:51.070 F/libc    (16863): FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7d413fcd40)
> 07-13 03:42:51.074 F/libc    (16863): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 17049 (ExoPlayerImplIn), pid 16863 (com.jafaria.app)
>

**Comment by marcelovargas** [comment]
I have this erro!

**Comment by JigarM** [comment]
same error

**Comment by marcelovargas** [comment]
MediaSession cannot be null. Make sure the MediaBrowserService sets it up

**Comment by marcelovargas** [comment]
I can listing then song, but not video  (
if I clean this
<mm:VideoView VerticalOptions="FillAndExpand" Source="http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4" /> 
============================================
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:mm="clr-namespace:MediaManager.Forms;assembly=MediaManager.Forms"
             mc:Ignorable="d"
             x:Class="TesteVideo2.MainPage">

    <ContentPage.Content>
        <StackLayout>
            
        </StackLayout>
    </ContentPage.Content>

</ContentPage>

=======================================================
using MediaManager;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace TesteVideo2
{
    // Learn more about making custom code visible in the Xamarin.Forms previewer
    // by visiting https://aka.ms/xamarinforms-previewer
    [DesignTimeVisible(false)]
    public partial class MainPage : ContentPage
    {
        
        public MainPage()
        {
            InitializeComponent();

            Reproducir();

        }

        private async void Reproducir()
        {

            await CrossMediaManager.Current.Play(http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4" );
        }
    }
}
===============================================
using System;

using Android.App;
using Android.Content.PM;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Android.OS;
using MediaManager;

namespace TesteVideo2.Droid
{
    [Activity(Label = "TesteVideo2", Icon = "@mipmap/icon", Theme = "@style/MainTheme", MainLauncher = true, ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]
    public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
    {
        protected override void OnCreate(Bundle savedInstanceState)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(savedInstanceState);

            Xamarin.Essentials.Platform.Init(this, savedInstanceState);
            global::Xamarin.Forms.Forms.Init(this, savedInstanceState);

            CrossMediaManager.Current.Init(this);

            LoadApplication(new App());
        }
        public override void OnRequestPermissionsResult(int requestCode, string[] permissions, [GeneratedEnum] Android.Content.PM.Permission[] grantResults)
        {
            Xamarin.Essentials.Platform.OnRequestPermissionsResult(requestCode, permissions, grantResults);

            base.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }
    }
}

**Comment by jrahma** [comment]
This problem is solved after enabling d8 and updating the MediaPlayer BUT I am now having another problem.

My app runs perfectly on Debug and when I deploy to the device but when I build on Release I get this error:

> java/lang/Object;I)V: defining a default interface method requires --min-sdk-version >= 24 (currently 13) for interface methods: com.google.android.exoplayer2.Player$EventListener.onTimelineChanged : (Lcom/google/android/exoplayer2/Timeline;Ljava/lang/Object;I)V

**Comment by martijn00** [comment]
@jrahma you need to set the d8 compiler in both Release and Debug mode.

**Comment by martijn00** [comment]
Can you test with 0.7.3?

**Comment by SatyaRamprasad** [comment]
It's working @martijn00 
Thanks
