### ISSUE TITLE
defining a default interface method requires --min-sdk-version >= 24 (currently 13) 

### ISSUE THREAD

**Issue by AlenToma** [martijn00/XamarinMediaManager#529]
## 🔙 Regression

I have upgraded to the latest MediaManager and uncepcted error happend
### Old (and correct) behavior
I could build without problem
### Current behavior
I cant build the project.

this is the error im seeing 
even though i have this sdk versions

`	<uses-sdk android:minSdkVersion="24" android:targetSdkVersion="28" />`

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		java/lang/Object;I)V: defining a default interface method requires --min-sdk-version >= 24 (currently 13) 
for interface methods: com.google.android.exoplayer2.Player$EventListener.onTimelineChanged : (Lcom/google/android/exoplayer2/Timeline;Ljava/lang/Object;I)V	Youtube.Manager.Android	
```	
### Reproduction steps
Upgrade Android MediaManager to 0.7.2
And simple Build the project.
### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :robot: Android

**Comment by AlenToma** [comment]
Obs got it `<AndroidDexTool>d8</AndroidDexTool>` sorry for the extra issue

**Comment by martijn00** [comment]
Duplicate of https://github.com/martijn00/XamarinMediaManager/issues/524
