### ISSUE TITLE
Application is not responding on disappearing

### ISSUE THREAD

**Issue by SatyaRamprasad** [martijn00/XamarinMediaManager#534]
## 🔙 Regression

Application is not responding on disappearing after playing a Media Item

### Old (and correct) behavior
Application is working properly on disappearing 

### Current behavior
Application is not responding

### Reproduction steps
1.Play a media item
2.Click on back button 
3.Application is not responding
### Configuration

**Version:** 0.7.3

**Platform:** 
- [x] :iphone: iOS
- [x] :monkey: Xamarin.Forms

**Comment by developering** [comment]
Same issue here. Also on iOS with Xamarin.Forms.

**Comment by orzech85** [comment]
For me only iOS with Xamarin.Forms.

**Comment by martijn00** [comment]
0.7.4 is out now.
