### ISSUE TITLE
Not set speed in real time android

### ISSUE THREAD

**Issue by EduardoPac** [martijn00/XamarinMediaManager#543]
## 🐛 Bug Report

The playback speed property, when i want to put another value at runtime on android, the same doesn't change, when i do the same on ios it **works**

### Reproduction steps
CrossMediaManager.Current.Speed = 2f;

**Version:** 0.7.4 
nuget Plugin.MediaManager

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by ricardoprestes** [comment]
I'm with de some problem.

**Comment by martijn00** [comment]
It looks like https://github.com/martijn00/XamarinMediaManager/blob/develop/MediaManager/Platforms/Android/MediaManagerImplementation.cs#L201 needs a new instance of PlaybackParameters instead of changing speed on the existing. I will release a change for that so you can try.

**Comment by EduardoPac** [comment]
OK, I will be waiting, thank you

**Comment by martijn00** [comment]
Potential fix is here: https://github.com/martijn00/XamarinMediaManager/commit/eb25a41f873b7f28f3c11d850776bda2cf8b7a79

Release will be later this week.

**Comment by EduardoPac** [comment]
Thanks dude
