### ISSUE TITLE
MediaItemChanged is not fired on iOS

### ISSUE THREAD

**Issue by adambarath** [martijn00/XamarinMediaManager#544]
## 🐛 MediaItemChanged is not fired on iOS
I added some items to the MediaQueue. It starts playing the queue well, but when the code hits PlayNext(), the MediaItemChanged event is not got fire. 

Note: MediaItemChanged fired if a song finished playing.

### Expected behavior
MediaItemChanged should got fired after calling PlayNext() task.

### Reproduction steps
```
var mediaItem = await CrossMediaManager.Current.MediaExtractor.CreateMediaItem(mediaFilePath);
CrossMediaManager.Current.MediaQueue.Add(mediaItem);
await CrossMediaManager.Current.Play();
await CrossMediaManager.Current.PlayNext();
```
### Configuration
Xamarin Forms 4.1.0.581479
Device iOS 12.3.1 (iPhone 5s)
**Version:** 0.7.4

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by karak** [comment]
Same for me. `PlayPreviousOrSeekToStart` is a bit more troublesome.

**Comment by karak** [comment]
Manual changing has simple work-around, but **remote control** has no solution.

I searched the codes of iOS for `OnMediaItemChanged`, and never found it.  Should `AppleMediaManager` override `Timer_Elapsed` and detect the change there, or observe `MediaQueue`?
