### ISSUE TITLE
Please help me basic sample

### ISSUE THREAD

**Issue by flashomer** [martijn00/XamarinMediaManager#547]
## 💬 Questions and Help

Hi,
I'm a student at university.  I have a project at Xamarin. 
if it is possible, could you please, help me?
My project is a university radio app.
I read all your Xamarin tutorial. However it very complex for me. 
My project sample: http://prntscr.com/okdd0o
it's very basic. is this possible?
can you prepare a basic example for me?

**Comment by martijn00** [comment]
This is not how open source works. Look into the api because all of this is possible.
