### ISSUE TITLE
[iOS] MediaItem with a local path is denied to play.

### ISSUE THREAD

**Issue by karak** [martijn00/XamarinMediaManager#548]
## 🐛 Bug Report

I create MediaItems from local path like "/var/mobile/Containers/.../foo.mp3" and queue them to play, but none of them sound.

I found AVPlayerItem has error information claiming "unsupported URL."
It is certain that fixing them to file form as starting with "file://" makes them sound, but this affects some other parts and platforms like MediaExtractor.

### Expected behavior

Play them successfully by, for example, formatting in `MediaPlayerImplementation`.

### Reproduction steps

1. Create MediaItems from local path like "/var/mobile/Containers/.../foo.mp3"
1. Add them to MediaQueue.
1. Start to play.

### Configuration

**Version:** 
0.7.4

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
This should be fixed in 0.7.5 and 0.7.6 try those and let me know.

**Comment by karak** [comment]
Thank you.

As I tried, one of iOS works fine, but one of Android failed to play. I'm going to continue using FileInfo version.
