### ISSUE TITLE
Please change CPU architecture in iOS debug to i386 + x86_64

### ISSUE THREAD

**Issue by escamoteur** [martijn00/XamarinMediaManager#55]
Hi,

currently the debug project settings for iOS is set to 64Bit only which makes the Forms sample crash when startet on an iPhone 5

**Comment by martijn00** [comment]
Can you make a PR for this?

**Comment by modplug** [comment]
This should be fixed in [#60](https://github.com/martijn00/XamarinMediaManager/pull/60)
