### ISSUE TITLE
where is the problem? Ios Notification Problem!

### ISSUE THREAD

**Issue by flashomer** [martijn00/XamarinMediaManager#553]
## 💬 Questions and Help

https://screencast-o-matic.com/watch/cqiur0OgOY

https://github.com/flashomer/xAppR5

I don't find where is the problem? 
Everything is ok however it doesn't work the ios notifications.

**Comment by martijn00** [comment]
Can you stop opening questions without proper description?

**Comment by flashomer** [comment]
`2019-07-29 05:23:10.641812-0700 AppR5.iOS[2347:18766] -[AVAsset loadValuesAsynchronouslyForKeys:completionHandler:] invoked with unrecognized keys (
    title,
    artwork,
    artist
).

Video : https://screencast-o-matic.com/watch/cqiur0OgOY
Sample: https://github.com/flashomer/xAppR5
I took a video and threw sample codes. If you follow, you understand the problem.`

**Comment by martijn00** [comment]
I don't have time to look into your problems. As i said provide clear descriptions of any bugs you find and i might take a look.

**Comment by flashomer** [comment]
oke, I'm sorry.
I did everything.

Visual Studio 2019
Plugin.MediaManager 0.7.7

it works perfectly at Android. However, it does not work background notification at Ios.
Music is work but the notification does not.  I try several mp3 and several codes :/ 
Please help me.

**Logs:** 
`2019-07-29 06:10:30.036490-0700 AppR5.iOS[3885:46343] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=3885
2019-07-29 06:10:30.037369-0700 AppR5.iOS[3885:46343] SecTaskCopyDebugDescription: AppR5.iOS[3885]/0#-1 LF=0
2019-07-29 06:10:30.052256-0700 AppR5.iOS[3885:46343] libMobileGestalt MobileGestalt.c:890: MGIsDeviceOneOfType is not supported on this platform.
Thread started:  #2
Thread started: <Thread Pool> #3
Thread started: <Thread Pool> #4
Thread started: <Thread Pool> #5
Thread started: <Thread Pool> #6
2019-07-29 06:10:34.042338-0700 AppR5.iOS[3885:46343] -[AVAsset loadValuesAsynchronouslyForKeys:completionHandler:] invoked with unrecognized keys (
    title,
    artwork,
    artist
).
2019-07-29 06:10:34.090552-0700 AppR5.iOS[3885:46391] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=3885
2019-07-29 06:10:34.090967-0700 AppR5.iOS[3885:46391] SecTaskCopyDebugDescription: AppR5.iOS[3885]/0#-1 LF=0
Thread started:  #7
2019-07-29 06:10:42.724127-0700 AppR5.iOS[3885:46466] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=3885
2019-07-29 06:10:42.724917-0700 AppR5.iOS[3885:46466] SecTaskCopyDebugDescription: AppR5.iOS[3885]/0#-1 LF=0`


**MainPage.xaml.cs:**
` public MainPage()
        {
            InitializeComponent();
            CrossMediaManager.Current.StepSize = TimeSpan.Zero;
            CrossMediaManager.Current.Init();
            CrossMediaManager.Current.NotificationManager.ShowPlayPauseControls = true;
            CrossMediaManager.Current.NotificationManager.ShowNavigationControls = false;

            
        }


        private async void Button_Clicked_1(object sender, EventArgs e)
        {
            await StartMusicFunc();
        }


        private async Task StartMusicFunc()
        {
            var mediaItem = await CrossMediaManager.Current.Play("https://womenhairstyles.net/hs.mp3");
            mediaItem.Title = "Title";
            mediaItem.Album = "Album";
            mediaItem.Artist = "Artist";
            mediaItem.AlbumArt = "https://womenhairstyles.net/superFm.png";
            mediaItem.Art = "https://womenhairstyles.net/superFm.png";
            mediaItem.AlbumArtUri = "https://womenhairstyles.net/superFm.png";

            CrossMediaManager.Current.MediaQueue.Current.Title = "Title";
            CrossMediaManager.Current.MediaQueue.Current.Album = "Album";
            CrossMediaManager.Current.MediaQueue.Current.Artist = "Artist";
            CrossMediaManager.Current.MediaQueue.Current.AlbumArt = "https://womenhairstyles.net/superFm.png";
            CrossMediaManager.Current.MediaQueue.Current.Art = "https://womenhairstyles.net/superFm.png";
            CrossMediaManager.Current.MediaQueue.Current.AlbumArtUri = "https://womenhairstyles.net/superFm.png";

            CrossMediaManager.Current.NotificationManager.UpdateNotification();

            
            mediaItem.MetadataUpdated += (sender, args) => {
                var title = args.MediaItem.Title;
                var album = args.MediaItem.Album;
                var artist = args.MediaItem.Artist;
                var artwork = args.MediaItem.AlbumArt;
                var albumArt = args.MediaItem.AlbumArt;
                var art = args.MediaItem.Art;
                var MediaType = args.MediaItem.MediaType;
                var albumArtUri = args.MediaItem.AlbumArtUri;
            };
        }`

**info.plist**
` <string>Assets.xcassets/AppIcon.appiconset</string>
    <key>NSAppTransportSecurity</key>
    <dict>
      <key>NSAllowsArbitraryLoads</key>
      <true/>
    </dict>
    <key>UIBackgroundModes</key>
    <array>
      <string>audio</string>
      <string>fetch</string>
    </array>
  </dict>
</plist>
`
