### ISSUE TITLE
WPF Property Bugs

### ISSUE THREAD

**Issue by CDarbonne** [martijn00/XamarinMediaManager#555]
## 🐛 Bug Report

State property does not change according to the actual state change, instead is always set to "stopped". PositionChanged never fires its event. `IsPlaying()` always returns false even when media is playing. This was referenced in Issue #527 where the poster intended to create a separate issue for WPF, but never did. I have tried using both `Current.IsPlaying()` and `Wpf.IsPlaying()`. Please let me know if I am missing something or if this is an actual bug/missing feature. The above-referenced issue was the only reference to this I could find online.

### Expected behavior

Correct data in respective properties and appropriate event firing.

### Reproduction steps
Subscribe to event: `CrossMediaManager.Current.PositionChanged` or `CrossMediaManager.Wpf.PositionChanged`
Check `IsPlaying()` or State property while media is playing
### Configuration

**Version:** v0.7.7

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [x] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Fixes will be available in 0.7.8

**Comment by CDarbonne** [comment]
Thank you!

**Comment by CDarbonne** [comment]
@martijn00 Thanks for the new release and fix for State Property! Just wanted to point out the still existing issue of `PositionChanged` event not being triggered though. Is/Should this be a separate issue and therefore get its own issue post?

**Comment by martijn00** [comment]
Are you sure you call Init? This works for me in the sample.

**Comment by CDarbonne** [comment]
@martijn00 I initialize the CrossMediaPlayer and Current/Wpf `Initialized` property is true, however, `Wpf.Player.IsInitialized` is false. I dont see how to initialize this though. There is no `Init()` for player and `BeginInit()` does not change this property. Im probably missing something here, can you tell what it is from this info or do I need to provide more?

**Comment by CDarbonne** [comment]
@martijn00 It is firing now, it just seems to be sporadic. I was under the impression it would fire every second as the current position of the media changed, but it seems to only fire on seeking. This is most likely a misunderstanding on my part, I just need to get more familiar with the codebase. Thanks for your help!

**Comment by martijn00** [comment]
I am available for hire as an consultant if you need any help. Drop me an email if you are interested.
