### ISSUE TITLE
Can I use Xamarin Media Manager to generate thumbnails for my videos?

### ISSUE THREAD

**Issue by DavidLBrandt** [martijn00/XamarinMediaManager#557]
## Xamarin Media Manager Thumbnails

I use Plugin.MediaManager.Forms 0.6.7 on Android and iOS to view videos.  My app allows teams to share video clips from their phones and is cross platform.  The videos are stored locally for offline access.

I tried using [this native approach](https://forums.xamarin.com/discussion/119450/create-thumbnail-from-video) to generate thumbnails.  And it works in all cases except for MOV video files on Android devices.

I am completely blocked trying to generate thumbnails for MOV video files on Android and am looking for a success path.

I am hoping that because MediaManager can play MOV files on Android it may also provide the means to create thumbnails. If not any pointer in the right direction would be greatly appreciated.

Thanks for your help!

**Comment by martijn00** [comment]
This is something I have no plans for at the moment, but could probably make pretty quickly if you are willing to pay for commercial support on this. Send me an email if you are interested.

**Comment by DavidLBrandt** [comment]
Thanks for the quick reply!  I'll follow up with email.

**Comment by DavidLBrandt** [comment]
Hi Martijn,
 
The app I am building is for a very small group of athletes and their coach to help with training.  I expect that the total number of users will never grow beyond 50 people.  I share this so I don’t misrepresent the scale of our venture. 😉
 
What might the cost on something like this be?
 
Thanks!
 
David Brandt 
Mobile: (206) 370-1330
 <https://www.linkedin.com/in/david-brandt-58a18720/> LinkedIn

**Comment by martijn00** [comment]
@DavidLBrandt it seems you send the email to this GitHub issue. Can you send it to Martijn at baseflow dot com ?
