### ISSUE TITLE
iOS: The package 'Plugin.MediaManager' tried to add a framework reference to 'System.Drawing.Common.dll' which was not found in the GAC

### ISSUE THREAD

**Issue by rrispoli** [martijn00/XamarinMediaManager#558]
## 💬 Questions and Help

Hi, I can't update to version 0.7.5, 0.7.6 and 0.7.7 in Xamarin.iOS. The Nuget show "Xamarin.iOS,Version=1.0 No Dependencies", but when I try to update, it show this error:

```
Failed to add reference. The package 'Plugin.MediaManager' tried to add a framework reference to 'System.Drawing.Common.dll' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
Reference unavailable.		
```

**Comment by martijn00** [comment]
For some reason this is added to the nuget package, but I don't use it anywhere in the code. Very weird, i'll look into it.

**Comment by martijn00** [comment]
It seems like this is a problem in vs2019 16.2.

This might be related:
https://developercommunity.visualstudio.com/content/problem/585711/visual-studio-2019-preview-1620-preview-10-xamarin.html

https://developercommunity.visualstudio.com/content/problem/623875/xamarinios-fails-to-link-when-using-the-systemdraw.html

**Comment by rrispoli** [comment]
Hi @martijn00 the recommendation then is to wait a new VS 2019 version?

**Comment by abreucruz** [comment]
I just updated to VS 16.3 and having the same issue upgrading the package.

**Comment by bgavrilMS** [comment]
I have the same problem with Microsoft.Identity.Client 
I tried to manually update the ios project and it seems to build.

**Comment by martijn00** [comment]
Same as https://github.com/aritchie/userdialogs/issues/654

**Comment by jamesmontemagno** [comment]
@martijn00 did you figure this out? I am seeing this in my media plugin. The nuget packaging is adding it for some reason....

**Comment by abreucruz** [comment]
I had this issue when I migrated an old project to .NET standard because the package is trying to install the DLL from the new package locaation.  The workaround is add the reference system.drawing.common.dll from the old package location.

**Comment by jamesmontemagno** [comment]
@martijn00 if building in 2019 add
<DisableExtraReferences>true</DisableExtraReferences>

This will fix the nuget
