### ISSUE TITLE
Can't access	Plugin.MediaManager.Abstractions.Implementations from iOS

### ISSUE THREAD

**Issue by tarisaig** [martijn00/XamarinMediaManager#56]
Hi,

I can't seem to access Plugin.MediaManager.Abstractions.Implementations for my Xamarin.iOS project. I'm looking to use the default implementations of IMediaFile (MediaFile) and IMediaQueue (MediaQueue), but this namespace isn't coming up.

**Comment by martijn00** [comment]
Which version are you on?

**Comment by tarisaig** [comment]
Version 0.09 NuGet package

**Comment by martijn00** [comment]
I think this is only included in the 0.1.0-beta. Can you try those?

**Comment by tarisaig** [comment]
Perfect - got it now. Thanks Martijn
