### ISSUE TITLE
Android : Video is not visible but audio is playing

### ISSUE THREAD

**Issue by onebuild** [martijn00/XamarinMediaManager#562]
## 🐛 Bug Report

I have two screens A and B. When I play video in screen A and when user clicks on maximizing the same video I am trying to play it in screen B. Video is playing in screen B no issues but when I go back from screen A to screen B the video is playing but it is not visible. I am not getting where I am doing wrong.

Screen A Code
`
CrossMediaManager.Current.MediaPlayer.SetPlayerView(videoView);
CrossMediaManager.Current.Play(videoSrc);
`

Screen B Code

`CrossMediaManager.Current.MediaPlayer.SetPlayerView(newVideoView);
CrossMediaManager.Current.MediaPlayer.Play();
`

**Comment by martijn00** [comment]
Please fill out the complete template and don't remove things. Also you are clearly using a very outdated version of the plugin.

**Comment by EchoSKSh** [comment]
@onebuild i am facing the same situation did u figure out any thing on this. Could you please guide me on this
