### ISSUE TITLE
Android AlternateRemoteCallback missing 

### ISSUE THREAD

**Issue by jmartine2** [martijn00/XamarinMediaManager#57]
A while back, I added the MediaManagerImplementation.AlternateRemoteCallback property in order to handle remote media commands (play, pause, skip, etc.). This property seems to have been removed when the interface was changed recently. Was this intentional? If so, what is the new way to handle these events?

**Comment by martijn00** [comment]
This is work in progress, and also why it is still beta. I am aiming to provide this through the common interface.

**Comment by SimonSimCity** [comment]
@martijn00 I suggest adding `TODO`s always when events are added and removing them after they're fully implemented.

I think it's better in the long run to have more actually resolved `TODO`s in the code than not knowing what's actually going on.

All these triggers should also be tested in some way, that we're sure they are triggered ...
