### ISSUE TITLE
Error when push repeat to often

### ISSUE THREAD

**Issue by OdetteP** [martijn00/XamarinMediaManager#575]
## 🐛 Bug Report
When repeat is pushed multiple times an error appears saying "AVPlayerItem can occupy only one position in a player's queue at a time"

### Expected behavior
Click on repeat without getting an error

### Reproduction steps
click on repeat button multiple times 

<img width="816" alt="Screenshot 2019-08-06 at 14 51 28" src="https://user-images.githubusercontent.com/43118107/62551945-25678c80-b86d-11e9-83fb-3518ffd8f191.png">

### Configuration

**Version:** 1.x

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Should be fixed in 0.8.10
