### ISSUE TITLE
Full screen option for videoView

### ISSUE THREAD

**Issue by kishor010** [martijn00/XamarinMediaManager#577]
## 🚀 Feature Requests
 Need an option for full screen and ESC to full screen like how AVPlayer is doing in iOS.

### Contextualize the feature
Many of user wants to play Video in full screen mode and there is not option available

### Describe the feature
Full screen option and Esc to full screen option.

### Platforms affected (mark all that apply)
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Duplicate of https://github.com/martijn00/XamarinMediaManager/issues/571
