### ISSUE TITLE
FMRadio stream doesn't work

### ISSUE THREAD

**Issue by revealyan** [martijn00/XamarinMediaManager#578]
## 🐛 Bug Report
Good day!
I'm trying to implement fm radio based on your library.
In the Play method, I pass the link to the radio station. 
in this case, the State = Paused.
If call the PlayPause method, the State changes to Buffering, but is not reproduced (nothing is buffered)

This does not work, but what’s most interesting is on devices with iOS 12.x (tested on real devices and a simulator). On a device with pre-installed beta iPadOS (iOS 13), everything works fine.

**Version:** 0.8.4

**Platform:** 
- [ X] :iphone: iOS
- [X ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Can you add the steps to reproduce and a test url?
