### ISSUE TITLE
Works only from "https://" sources

### ISSUE THREAD

**Issue by FeduniakVitalii** [martijn00/XamarinMediaManager#579]
## 🐛 Bug Report
Hello! I can't play video from http:// , only from https:// works.

 //https://sec.ch9.ms/ch9/e68c/690eebb1-797a-40ef-a841-c63dded4e68c/Cognitive-Services-Emotion_high.mp4 - this link play
            //http://acccms.mediamyne.nl/api/api/GetFile/GetVideo?VideoName=156953-DE5568A3DC478F0F3F9D8191C1201FB5.mp4 - this I need, but it doesn't play
            //http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4 - this doesn't play

my example project: https://github.com/FeduniakVitalii/XamarinMediaManager

Please help. What I'm doing wrong?

**Platform:** 
- [x] :robot: Android
- [x] :monkey: Xamarin.Forms

**Comment by adambarath** [comment]
I think transport security blocks the requests by Android OS, but not the XamarinMediaManager library.

You should enable and allow unsecure protocols.

**Comment by FeduniakVitalii** [comment]
> enable and allow unsecure protocols

Where and how I can do it?

**Comment by adambarath** [comment]
General .NET untrusted cert topic: https://stackoverflow.com/questions/12553277/allowing-untrusted-ssl-certificates-with-httpclient

For Android: https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/http-stack
For iOS: https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/ats

**Comment by FeduniakVitalii** [comment]
I found: the problem was in Emulator
