### ISSUE TITLE
Event when a new media file starts playing?

### ISSUE THREAD

**Issue by jmartine2** [martijn00/XamarinMediaManager#58]
I used to subscribe to the CoverReloaded event so that I would know when new album art was available, so that I could update my UI.  However, with the new interface change, that event no longer exists. So, I decided that I should subscribe to an event that tells me when a new song starts playing instead. However, I can't find one that works.

I first tried using MediaQueue.QueueMediaChanged. However, if I subscribe to this event, my handler never gets called. Due to the way that my app works, I only play one song at a time, using the Play() function, so there is never more than one song in the queue. I am assuming that this is the reason.

I then though of using the IMediaManager.MediaFileChanged event, but it appears (from the comments in the Interface) and looking at the code, that this event is only raised when a song FINISHES playing, not when it starts, which is what I need.

I was thinking of adding a call to OnMediaFileChanged in the Play() method so that I could get a notification when a new song starts, but I'm not sure if this is the best solution. Is this a good solution, or is there a better way to achieve this?

**Comment by SimonSimCity** [comment]
Try something like this code:

    CrossMediaManager.Current.MediaQueue.PropertyChanged += (object sender, PropertyChangedEventArgs e)
    {
        switch (e.PropertyName)
        {
            case "Current":
                if (CrossMediaManager.Current.MediaQueue.Current.MetadataExtracted) {
                    // Do something with CrossMediaManager.Current.MediaQueue.Current.Metadata.Cover
                } else {
                    // Take a listener on CrossMediaManager.Current.MediaQueue.Current and watch for a change on MetadataExtracted.
                }
                break;
        }
    }

If you don't know if your item already is the current one, just execute the code inside immediately.

**Comment by martijn00** [comment]
The reason that `MediaQueue.QueueMediaChanged` isn't working is a bug. I think it would be correct to use that once the bug has been fixed.

**Comment by martijn00** [comment]
I think we could add an event for the Cover changed to the MediaExtractor

**Comment by SimonSimCity** [comment]
@martijn00 I would add the `INotifyPropertyChanged` interface to the `IMediaFileMetadata`, since the object is instanciated in the constructor of every `MediaFile` even though the metadata isn't available there.

**Comment by martijn00** [comment]
@SimonSimCity That is a good idea! But i would still like to add it as a separate event, so we can pass the cover object as argument in the event handler.

**Comment by martijn00** [comment]
Started on this in https://github.com/martijn00/XamarinMediaManager/commit/8ad9a80459b8ad5b4ef96f3529afa78d6f2dc83c

**Comment by jmartine2** [comment]
@SimonSimCity Thanks for the solution. Could you elaborate on how to "Take a listener on CrossMediaManager.Current.MediaQueue.Current and watch for a change on MetadataExtracted."? MetadataExtracted is a method, not an event.

**Comment by SimonSimCity** [comment]
Right, but the `IMediaFile` interface includes the `INotifyPropertyChanged` interface.

So you can just use that and check which property changed. Take a switch on the property-name, like I did in the first example and you're ready to go.

**Comment by jmartine2** [comment]
@SimonSimCity Got it, thanks!

**Comment by jmartine2** [comment]
I agree with @martijn00. I think that having a dedicated event would be better, so that the cover can be passed in via the EventArgs. Using INotifyPropertyChanged is more cumbersome, and could also be error prone since there is no guarantee that the cover value won't change between the firing of PropertyChanged and reading the Cover value. Also, since "Metadata" is the property that changes, Cover is actually a level removed, so there is no way to know that the Cover actually changed. It could be the Title, Album, etc. that changed. Correct me if I'm wrong on this.
