### ISSUE TITLE
How can we change image icon for audio player?

### ISSUE THREAD

**Issue by kishor010** [martijn00/XamarinMediaManager#583]
I am playing audio on **VideoView**.
I want to change icon which is coming default.
How can I resolve this ?

**Comment by martijn00** [comment]
Why are you not following the rules and make correct issues?

**Comment by martijn00** [comment]
CrossMediaManager.Android.NotificationIconResource = Resource.Drawable.exo_controls_play;

**Comment by kishor010** [comment]
> CrossMediaManager.Android.NotificationIconResource = Resource.Drawable.exo_controls_play;

I don't know properly.
Can you please help me out in this ?

**Comment by kishor010** [comment]
> CrossMediaManager.Android.NotificationIconResource = Resource.Drawable.exo_controls_play;

For iOS ?
