### ISSUE TITLE
streaming video not playing on android pie but playing else where

### ISSUE THREAD

**Issue by tirathpal** [martijn00/XamarinMediaManager#586]
## 🔙 Regression

08-10 08:06:05.961 E/ExoPlayerImplInternal(25199): Source error.
08-10 08:06:05.961 E/ExoPlayerImplInternal(25199): com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://45.120.42.68:1935/live/gnenews/playlist.m3u8

### Reproduction steps
my code is             var item = await CrossMediaManager.Current.MediaExtractor.CreateMediaItem(videoUrl);
            item.MediaType = MediaType.Hls;
            await CrossMediaManager.Current.Play(item);

### Configuration 
using latest vs 2019 and latest mediamanager plugin v0.8.6
**Version:** 1.x

**Platform:** 
- [-] :iphone: iOS
- [-] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Probably need to add the permission for that in your app: https://github.com/google/ExoPlayer/issues/6023#issuecomment-508707202

http is not secure and they block it on Android 9 and higher.

**Comment by tirathpal** [comment]
thanks martijn00
