### ISSUE TITLE
To Know when the playlist is finished

### ISSUE THREAD

**Issue by marcelovargas** [martijn00/XamarinMediaManager#587]
## 🐛 Bug Report

I am using a playlist. 
And the this method  only is for a one element (video/music):

private void Current_MediaItemFinished(object sender, MediaManager.Media.MediaItemEventArgs e)
        {

        }

### Expected behavior

To know when the playlist is fineshed.

### Reproduction steps
public IList<string> Mp3UrlList => new[]{
	"https://ia800806.us.archive.org/15/items/Mp3Playlist_555/AaronNeville-CrazyLove.mp3",
	"https://ia800605.us.archive.org/32/items/Mp3Playlist_555/CelineDion-IfICould.mp3",
	"https://ia800605.us.archive.org/32/items/Mp3Playlist_555/Daughtry-Homeacoustic.mp3",
	"https://storage.googleapis.com/uamp/The_Kyoto_Connection_-_Wake_Up/01_-_Intro_-_The_Way_Of_Waking_Up_feat_Alan_Watts.mp3",
	"https://aphid.fireside.fm/d/1437767933/02d84890-e58d-43eb-ab4c-26bcc8524289/d9b38b7f-5ede-4ca7-a5d6-a18d5605aba1.mp3"
	};

 private async void Player()
  {
          await CrossMediaManager.Current.Play(Mp3UrlList);
  }

       
### Configuration
VS 2019 windows 10
**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
CrossMediaManager.Current.MediaQueue.QueueEnded +=

**Comment by marcelovargas** [comment]
I am using the code, but it is not working.

CrossMediaManager.Current.MediaQueue.QueueEnded += MediaQueue_QueueEnded;

 private void MediaQueue_QueueEnded(object sender, MediaManager.Queue.QueueEndedEventArgs e)
        {
            Player();
        }

        private async void Player()
        {
            await LoadList();

            if (playlist.Count != 0)
            {
                await CrossMediaManager.Current.Play(playlist);
            }

        }

**Comment by marcelovargas** [comment]
I want to update a list after finish a list and play again.
