### ISSUE TITLE
Aspect ratio on video view

### ISSUE THREAD

**Issue by StevenGranados** [martijn00/XamarinMediaManager#589]
## 🐛 Bug Report

Firstly, this is working way better than in 0.7.x, when I last gave it a go.
I have a video of Big Buck in a videoview in a StackLayout in a Collectionview. I would expect it to fill out as far as possible in width since this is a vertical list of things. It actually fills in a fixed height. The actual video I want to display is 9:16 so appears very small.
### Expected Behaviour
Video fills whole width of bubble and expands in height as needed to maintain aspect ratio.
### Actual Behaviour
Video fills a fixed height and size of video suffers.
![Capture](https://user-images.githubusercontent.com/51818199/62859233-7572a300-bcf4-11e9-830f-60845d65837e.PNG)
![Capture2](https://user-images.githubusercontent.com/51818199/62859234-7572a300-bcf4-11e9-8d2f-1d336151c2e6.PNG)

**Version:** 0.8.6

**Platform:** 
- [x] :robot: Android Pie Emulator
- [x] :monkey: Xamarin Forms 4.2.0-pre3.

**Comment by martijn00** [comment]
Fixed in 0.8.7
