### ISSUE TITLE
App crash in release mode

### ISSUE THREAD

**Issue by eramrit78** [martijn00/XamarinMediaManager#592]
## 🔙 Regression

Hi
I am using visual studio 2019. When i try to deploy android app in release mode it crash after first screen.in debug mode it run perfectly. 

### Old (and correct) behavior
Worked before 10 days
### Current behavior
Crash on release mode
### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by eramrit78** [comment]
Hi

Now it worked. issue in mainactivity file. now we resoled.

Thanks

**Comment by marcelovargas** [comment]
This work for me: 

Dex tool to D8: <AndroidDexTool>d8</AndroidDexTool>

The same configuration of the Debug in the Realese.
