### ISSUE TITLE
Updating Plugin from 0.8.5 to 0.8.7 version is breaking for iOS.

### ISSUE THREAD

**Issue by kishor010** [martijn00/XamarinMediaManager#596]
## 🐛 Bug Report

I just updated my plugin from 0.8.5 to 0.8.7 and same code is placed, but it is not playing for iOS devices.

It should play for all devices.

Reproduction steps :-
1) Uodate Mediamanager plugin.
2) Write code to play mp3 url.

```
async void playAudio()
        {
            var item =  await CrossMediaManager.Current.MediaExtractor.CreateMediaItem("https://file-examples.com/wp-content/uploads/2017/11/file_example_MP3_5MG.mp3");
            item.MediaType = MediaType.Audio;
            item.Album = "Kishor";
            item.Author = "Geeky";
            item.Title = "Impelsys";
            item.Artist = "Prinju";
            await CrossMediaManager.Current.Play(item);
            //await CrossMediaManager.Current.Play("https://file-examples.com/wp-content/uploads/2017/11/file_example_MP3_5MG.mp3");
        } 
```

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :monkey: Xamarin.Forms

**Comment by adambarath** [comment]
It works. See sample project: ElementPlayer.Forms.iOS

**Comment by kishor010** [comment]
> ElementPlayer.Forms.iOS

Where can I see @adambarath ?
Thanks

**Comment by adambarath** [comment]
https://github.com/martijn00/XamarinMediaManager/tree/develop/Samples/ElementPlayer.Forms.iOS
