### ISSUE TITLE
Stop the current queue is not working.

### ISSUE THREAD

**Issue by kishor010** [martijn00/XamarinMediaManager#597]
## 🐛 Bug Report

I am trying to play a mp3 streaming audio and one local from storage.
Issue is once I tap on online url and inserted code to play, before playing I am coming back and stopping the queue and removing it but I am not able to do it, If I go for local one it is playing online audio.

Once I stop the current audio, it should remove from the current media queue.

### Reproduction steps
1) I have two buttons :- 
     a) Online audio
     b) Local audio

2) I tap on online audio button and I am trying to load url

  ```
async void playAudio()
        {
            var item =  await CrossMediaManager.Current.MediaExtractor.CreateMediaItem("https://file-examples.com/wp-content/uploads/2017/11/file_example_MP3_5MG.mp3");
            item.MediaType = MediaType.Audio;
            item.Album = "Kishor";
            item.Author = "Geeky";
            await CrossMediaManager.Current.Play(item);
        }
```

Before state change I come back to my home screen and stopping the audio 

 ```
 void StopAudio()
        {
            CrossMediaManager.Current.StateChanged -= StateChangedFunc;
            activity.IsVisible = false;
            CrossMediaManager.Current.Stop();
            CrossMediaManager.Current.MediaPlayer.Stop();   
        }
```
Problem is After coming back to home screen I am trying to play another video from local storage but in that class I am getting one queue already present and I am trying to remove and stop but still not happening and it is playing old audio (online) only.

I am just assuming that it is not getting synced to native queue.

Please help me out in this and yes lates update MediaManager is completely not working for iOS.

Can you please share some steps to handle it.
Thanks

**Version:** 1.x

**Platform:** 
- [x] :monkey: Xamarin.Forms

**Comment by adambarath** [comment]
It is better to use Task procedures, but not void ones. Please try it as you can see below.

```
await StopAudio();
await PlayAudio();

...
       async Task PlayAudio() { ... }

       async Task StopAudio()
       {
           CrossMediaManager.Current.StateChanged -= StateChangedFunc;
           activity.IsVisible = false;
           await CrossMediaManager.Current.Stop();
       }
```

**Comment by kishor010** [comment]
> It is better to use Task procedures, but not void ones. Please try it as you can see below.
> 
> ```
> await StopAudio();
> await PlayAudio();
> 
> ...
>        async Task PlayAudio() { ... }
> 
>        async Task StopAudio()
>        {
>            CrossMediaManager.Current.StateChanged -= StateChangedFunc;
>            activity.IsVisible = false;
>            await CrossMediaManager.Current.Stop();
>        }
> ```

OK Let me try, I will come back to you.
Thank you for the reply.

**Comment by kishor010** [comment]
@martijn00 and @adambarath 
I will share one demo sample with steps.
