### ISSUE TITLE
Play Media file from Resource

### ISSUE THREAD

**Issue by jrahma** [martijn00/XamarinMediaManager#598]
Hi,

I have an MP3 file in my Android's **Resources/Raw** folder, the file name is myAudio.mp3

The same file is placed in my iOS **Resources/myAudio.mp3**

I am trying to play the file uaing Xamarin Mediamanager plugin but it's not playiing any sound

I tried this:

`await CrossMediaManager.Current.Play("raw/myAudio.mp3");`

and this:

`await CrossMediaManager.Current.PlayFromResources("raw/myAudio.mp3");`

Thanks,
[Jassim](https://www.zeera.online)

**Comment by adambarath** [comment]
I think you should use the Asset folder instead of Resources/raw

**Comment by jrahma** [comment]
> I think you should use the Asset folder instead of Resources/raw

The docs says:

> When playing from a Resource you should add your media file for example to the Assets or raw folder on Android, and the Resources folder on iOS.

so raw folder should be fine but still not working

**Comment by martijn00** [comment]
https://stackoverflow.com/a/22906128/4222823

I will close the next issue you open without properly filling out the template immediately!

**Comment by jrahma** [comment]
Hi,

The sound file is not getting played from Resource/raw folder

### Expected behavior

### Reproduction steps
Copy a sound file inside the raw folder and use the following to play it:

`await CrossMediaManager.Current.Play("raw/myAudio.mp3");
`
also tried:

`await CrossMediaManager.Current.PlayFromResources("raw/myAudio.mp3");
`

### Configuration

**Version:** 0.8.9

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms
