### ISSUE TITLE
When Video view Show controls set to true, Gestures are not firing/working.

### ISSUE THREAD

**Issue by SatyaRamprasad** [martijn00/XamarinMediaManager#600]
## 🐛 Bug Report

When Video view Show controls set to true, Tap Gesture is not firing/working.

### Expected behavior
When Video view Show controls is true, Tap Gesture should work.

### Reproduction steps
1.set show controls to true
2. Add a tap gesture
2.play a video and tap, it won't fire.

### Configuration

**Version:** 0.8.7

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android
- [x] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [x] :apple: MacOS
- [x] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
That is because the view will intercept the click. Either disable the controls, or add a view around the videoview and add the gesture on that.
