### ISSUE TITLE
Initialize init() method.

### ISSUE THREAD

**Issue by saurabh1993-05** [martijn00/XamarinMediaManager#601]
## 🐛 Bug Report

CrossMediaManager.Current.Init(this)

This will show me error whenever I put this keyword in Init method and without this it will not run 
please help.

**Comment by martijn00** [comment]
You need to do this in the mainactivity

**Comment by saurabh1993-05** [comment]
I am doing in MainAcitivity but I am getting error.

**Comment by saurabh1993-05** [comment]
![image](https://user-images.githubusercontent.com/50629920/64607899-0ff2fe80-d3e7-11e9-8da5-95dacb5296fc.png)


Hi if you see in image I am getting this type of error .
Please help how to resolve this issue.

**Comment by saurabh1993-05** [comment]
![image](https://user-images.githubusercontent.com/50629920/64608292-f1d9ce00-d3e7-11e9-8fc1-a803d9c4bc38.png)

And if I remove this keyword I will get Unhandled exception

System.NotImplementedException: This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

**Comment by martijn00** [comment]
That means you have not installed the nuget into every project.

**Comment by saurabh1993-05** [comment]
Nuget is installed in all projects but when I remove this keyword from Initialize method it shows this
error and when I add this it will show the above error(First Image) please look into this.
I need to use Media Manager in Application.

**Comment by martijn00** [comment]
Then you don't target Android 9

**Comment by saurabh1993-05** [comment]
still not working can you help make a video on youtube or something else it's very important.

**Comment by SveinEven** [comment]
I'm having this issue as well, and I set the target to Android 9, I get this message
`defining a default interface method requires --min-sdk-version >= 24 (currently 13)`
And that is with the minimum sdk version as 25.

I am using VS 2017, so I am unable to change the Dex-compiler.

@saurabh1993-05  Did you change the target framework here as seen in the image?
![image](https://user-images.githubusercontent.com/9107618/68372733-ba667400-0141-11ea-8083-3371469145cd.png)

**Comment by saurabh1993-05** [comment]
Hi SvienEven
I also changed the Target framework to android 9 pie but it is showing me the error something like
CompileToDalvik and yeah the min-sdk-version>=24 as well.
Let me know if you find any solution.

**Comment by martijn00** [comment]
The docs clearly say you need VS2019 and d8 compiler. If you still use VS2017 you are a fool and need to update now.

**Comment by SveinEven** [comment]
What a lovely reply from the owner "you are a fool".  You know, it would take you that many calories to write "If you still use VS2017, I suggest you update" instead of calling people fools. 
I dont have a lisence for at the moment, so I am unable to update. But thanks for your fantastic help @martijn00.

**Comment by martijn00** [comment]
It's great how people like you make open source toxic. I feel really appreciated for all the hard work I do, and give away for free to people like you... NOT. Let me ask another question. How much have you done in open source, or do you pay to open source projects at all? Seems like nothing. Thanks for your fantastic support @SveinEven

**Comment by SveinEven** [comment]
I'm sorry that you feel like I am toxic but you are the one that called me a fool.
I do not appreciate being called a fool for asking a question.

I have not done anything in open source, and I do not plan to either. But I do support every open source project I use or like. I had planned to support you if and when I got this plugin to work, and I probably still will once I get it to work. Even though you called me a fool.

But thanks for creating something that people use for free, but that does not give you the right to call people fools for nothing @martijn00

**Comment by saurabh1993-05** [comment]
Yes It works :) I got confused since it was working on android with the same configurations. Sorry My bad :) . Really fan of yours work. But Please don't use bad languages.
