### ISSUE TITLE
Tizen support for Xamarin Forms

### ISSUE THREAD

**Issue by johnjollystupid** [martijn00/XamarinMediaManager#602]
Is Tizen support for Xamarin Forms in the planned pipeline?

**Comment by martijn00** [comment]
Please fill out a proper issue template! Otherwise this will be closed.

**Comment by johnjollystupid** [comment]
Sorry I am new to this. Please can you explain what a proper issue template is. Many thanks in advance.

**Comment by martijn00** [comment]
When pressing new issue, you select a topic, and then fill out all the fields.

**Comment by martijn00** [comment]
Tizen support is already in.

**Comment by iptvstreamplayer** [comment]
System.NullReferenceException: Object reference not set to an instance of an object.
at MediaManager.Forms.Platforms.Tizen.VideoViewRenderer.OnElementChanged(ElementChangedEventArgs`1 args)

in xamarin forms v4.7 for tizen platform
