### ISSUE TITLE
QueueChangedEventArgs.cs IS NOT CODED in this version

### ISSUE THREAD

**Issue by nzrpi** [martijn00/XamarinMediaManager#603]
## 🔙 Regression

**QueueMediaChangedEventArgs.cs** used to be used to handle queue changes. The old code was:

using System;

namespace Plugin.MediaManager.Abstractions.EventArguments
{
    public class QueueMediaChangedEventArgs : EventArgs
    {
        public QueueMediaChangedEventArgs(IMediaFile file)
        {
            File = file;
        }

        public IMediaFile File { get; set; }
    }
}

The replacement in this version is **QueueChangedEventArgs.cs**, and it does not contain any code:

using System;

namespace MediaManager.Queue
{
    public class QueueChangedEventArgs : EventArgs
    {
    }
}

### Old (and correct) behavior
Allowed me to access e.File; the MediaFile.

### Current behavior

Cannot access e.File as it doesnt exist

### Reproduction steps
code it

### Configuration
??
**Version:** 1.1

**Platform:** 
- [ ] :iphone: iOS
- [checkmark] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Fixed in 0.8.9
