### ISSUE TITLE
Thumbnail missing in android notification

### ISSUE THREAD

**Issue by justcoding121** [martijn00/XamarinMediaManager#604]
## 🐛 Bug Report

Great work!

### Expected behavior
In android, the thumbnail (icon or album art) of the audio file played is not shown in the notification.
![Screenshot_20190904-202121](https://user-images.githubusercontent.com/2637679/64307332-f8cd9000-cf52-11e9-9411-ef8acf628e72.jpg)

### Reproduction steps
Sorry, I don't have the time to write a full demo project for this bug. I am providing the snippet below I am using. The API I am using[ is here](https://github.com/martijn00/XamarinMediaManager/blob/7ec7d505d3950c8cbabc60e7431b3e67a6943420/MediaManager/Media/MediaExtractorExtensions.cs#L30).
```
var mediaItems = (await nextTracks
                    .Select(x => new FileInfo(this.cacheService.GetCacheFilePath(x.Url)))
                    .CreateMediaItems())
                    .ToList();

await this.mediaManager.Play(mediaItems);
```

Looking into this repository, I see that the parsing for the thumbnail is not correct. In this line below each provider is parsed and then overwritten. So whichever is the last successful provider will be the metadata used. The sample audio file to test this [behavior is here](https://download-a.akamaihd.net/files/media_publication/51/nwt_18_Job_E_14.mp3).

https://github.com/martijn00/XamarinMediaManager/blob/7ec7d505d3950c8cbabc60e7431b3e67a6943420/MediaManager/Media/MediaExtractorBase.cs#L152-L161

Also on another note, an optional feature to dismiss the notification and audio playback with a swipe or at least a stop button for dismissal would be nice to have with the default behavior.

### Configuration

**Version:** 0.8.8

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Can you test 0.8.9? There are several fixes around this.

The feature to dismiss the notification and audio playback with a swipe or at least a stop button: this already exists. If it doesn't show you might have disabled it in the Notification manager, or your device software doesn't support it.

**Comment by justcoding121** [comment]
Thanks! It is fixed in the latest version.

The swipe feature works for other apps like outlook, so the device does support it. I couldn't find any specific setting that would prevent swipe to dismiss. I have a Galaxy S7 installed with Android 8.0 API 26.

I am closing this since the issue is resolved.

**Comment by justcoding121** [comment]
I see that we are setting PlayerNotificationManager.SetOngoing(true) in MediaBrowserService. My understanding is that SetOnGoing(true) will disable swipe to dismiss as answered in [SO here.](https://stackoverflow.com/questions/21795336/android-notification-swipe-delete-disabling)

https://github.com/martijn00/XamarinMediaManager/blob/develop/MediaManager/Platforms/Android/MediaSession/MediaBrowserService.cs#L135

**Comment by martijn00** [comment]
If you pause it is set to false: https://github.com/martijn00/XamarinMediaManager/blob/develop/MediaManager/Platforms/Android/MediaSession/MediaBrowserService.cs#L81

You have access to change it too: https://github.com/martijn00/XamarinMediaManager/blob/develop/MediaManager/Platforms/Android/Notifications/NotificationManager.cs#L16

**Comment by justcoding121** [comment]
Thanks! The second link is what I needed.
