### ISSUE TITLE
Android - Queue keeps building up, tracks repeating

### ISSUE THREAD

**Issue by jmartine2** [martijn00/XamarinMediaManager#61]
My app does not use queues.  I receive the MediaFinished event when a song ends, and in the handler, my app chooses the next song to play, and calls Play(IMediaFile mediaFile).

Since the interface change, I am having the following problem:

My app plays Song1.
When Song1 ends, it plays Song2.
When Song2 ends, my app requests to play Song3, but instead Song1 plays again.
Song1 keeps playing each time my app tries to play a new song.

I debugged this, and I found that for some reason, PlayNext() is being called.  I have included the call stack at the end of this email.

I put a breakpoint in PlayNext(), and in this part of the code:

```
        public async Task PlayNext()
        {
            if (MediaQueue.HasNext())
            {
                await CurrentPlaybackManager.Stop();
                MediaQueue.SetNextAsCurrent();
                await Task.WhenAll(
                    CurrentPlaybackManager.Play(_currentMediaFile),
                    GetMediaInformation(new[] {_currentMediaFile}));
            }

```

I found that MediaQueue has multiple songs in it (Song1, Song2, Song3, etc.), and the logic is making Song1 keep playing because it never leaves the queue. Even though the songs end, they don't get removed from the queue, so they keep building up.

When a song ends shouldn't it be automatically removed from the queue?

Am I doing something wrong, or is this a bug?

I'm wondering if perhaps my call to Play() is somehow interrupting the removal of the previous song from the queue?

Call stack:
>0x40 in Plugin.MediaManager.Abstractions.Implementations.MediaManagerBase.PlayNext at C:\Users\joemj\Source\Repos\XamarinMediaManager\MediaManager\Plugin.MediaManager.Abstractions\Implementations\MediaManagerBase.cs:58,17	C#
>  	[External Code]	
>  	0x5A in Plugin.MediaManager.Abstractions.Implementations.MediaManagerBase.OnMediaFinished at C:\Users\joemj\Source\Repos\XamarinMediaManager\MediaManager\Plugin.MediaManager.Abstractions\Implementations\MediaManagerBase.cs:249,13	C#
>  	0xF in Plugin.MediaManager.AudioPlayerBase<Plugin.MediaManager.MediaPlayerService>.<OnServiceConnected>b__57_3 at C:\Users\joemj\Source\Repos\XamarinMediaManager\MediaManager\Plugin.MediaManager.Android\Audio\AudioPlayerBase.cs:143,73	C#
>  	0xF in Plugin.MediaManager.MediaServiceBase.OnMediaFinished at C:\Users\joemj\Source\Repos\XamarinMediaManager\MediaManager\Plugin.MediaManager.Android\MediaPlayerService\MediaServiceBase.cs:303,13	C#
>  	0xD in Plugin.MediaManager.MediaPlayerService.OnCompletion at C:\Users\joemj\Source\Repos\XamarinMediaManager\MediaManager\Plugin.MediaManager.Android\MediaPlayerService\MediaPlayerService.cs:232,13	C#
>  	0x13 in Android.Media.MediaPlayer.IOnCompletionListenerInvoker.n_OnCompletion_Landroid_media_MediaPlayer_ at /Users/builder/data/lanes/3511/ce955cc0/source/monodroid/src/Mono.Android/platforms/android-24/src/generated/Android.Media.MediaPlayer.cs:233,5	C#
>

**Comment by jmartine2** [comment]
Note that I was able to counteract this issue in my own code by manually calling MediaQueue.Clear() right before Play() each time, but I'm not sure that I should have to do this.

**Comment by SimonSimCity** [comment]
The queue is thought as to be a list. This list doesn't kick items by itself, it just moves the index. If you request the player to play the first song of that queue, it will always be the same, right.

You're talking about queues here ... Why multiple?
Usually, there's just one, containing a list of tracks. The index defines on what position of the list the player currently is playing.

**Comment by martijn00** [comment]
The `MediaFinished` event you use calls `PlayNext()`
```
private async void OnMediaFinished(object sender, MediaFinishedEventArgs e)
        {
            if (sender != CurrentPlaybackManager) return;
                MediaFinished?.Invoke(sender, e);
            await PlayNext();
        }
```

How would you solve this in the library?

**Comment by jmartine2** [comment]
@SimonSimCity Sorry I should have said, "My app does not use the queue."

@martijn00 I think it's fine that it plays the next song in the queue if there are more songs in the queue. But I do think that since it's a queue, it should automatically remove each song when it is finished playing. The behavior that I described in my initial post seems very odd. When I specifically call Play(Song3), I don't think it should be playing Song1, which it already played.

**Comment by modplug** [comment]
@jmartine2: We changed the default behavior for the queue to Repeat = false, this should fix your issues.

**Comment by SimonSimCity** [comment]
@modplug please also take a look at the `ToggleRepeat` method ... it looks quite odd. In my opinion, we need a getter and setter for the property `Repeat`

**Comment by modplug** [comment]
@SimonSimCity: Yeah, I agree. The logic seems wrong as well

**Comment by martijn00** [comment]
Fixed in https://github.com/martijn00/XamarinMediaManager/commit/0f5904331c2fb9f3f0c43a793eed49476b89fccd
