### ISSUE TITLE
Play Media file from Resource

### ISSUE THREAD

**Issue by jrahma** [martijn00/XamarinMediaManager#614]
Hi,

The sound file is not getting played from Resource/raw folder

### Expected behavior

To run the sound file from raw folder

### Reproduction steps

Copy a sound file inside the raw folder and use the following to play it:

`await CrossMediaManager.Current.Play("raw/myAudio.mp3");
`

also tried:

`await CrossMediaManager.Current.PlayFromResources("raw/myAudio.mp3");
`

### Configuration

**Version:** 0.8.9

**Platform:** 
- [ X] :iphone: iOS
- [ X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by sparkist97** [comment]
you can put it in PCL and make sure that its build action is "EmbeddedResource" then use `await CrossMediaManager.Current.PlayFromAssembly("Assembly.Resource.raw.file.mp3");`

**Comment by martijn00** [comment]
To make it easier, in 0.8.10 you can do: `CrossMediaManager.Android.PlayFromResource(Resource.Raw.play.ToString());`

**Comment by supreettare** [comment]
I am sorry but both the above options are still not working for me. 
Putting it in PCL (standard2.0) project, same as above doesn't work. 
I also tried creating a Raw folder inside android resources & putting it there, doesn't work either. No exceptions. It just doesn't playback the file. 

Also, @martijn00 are you sure there is a CrossMediaPlayer.Android? I can't resolve that.

**Comment by supreettare** [comment]
@jrahma were you able to solve this?

**Comment by supreettare** [comment]
I was able to play it from the assembly file. I got confused on the folder structure, had to remove Resources.Raw from my string value & it worked as expected. 
Thanks
