### ISSUE TITLE
[iOS] Audio should resume after interruption like a phone call

### ISSUE THREAD

**Issue by BuddyLReno** [martijn00/XamarinMediaManager#615]
## 🚀 Feature Requests

The currently playing audio file should resume after interruption (like a phonecall)
### Contextualize the feature

Android currently resumes the audio after a phone call. iOS should also do the same.
### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by BuddyLReno** [comment]
It looks like iOS used to have this feature [back in 2017](https://github.com/martijn00/XamarinMediaManager/commit/4f20b31cce688fda3dce0850246a42a6f34e7627) but that looks like it was just an observer for the playback rate that updated status.

**Comment by BuddyLReno** [comment]
Alright so I figured out a different way to do this since it's a general observable. Microsoft has a callback for observing audio interruptions ([documentation here](https://docs.microsoft.com/en-us/dotnet/api/avfoundation.avaudiosession.interruptionnotification?view=xamarin-ios-sdk-12)). In the iOS project's `AppDelegate.cs` file:

```c#
    // tracking last played state
    private bool WasPlaying { get; set; }

    public override bool FinishedLaunching(UIApplication app, NSDictionary options)
    {
      // other xamarin startup stuff
      CrossMediaManager.Current.Init();
      AVAudioSession.Notifications.ObserveInterruption(AudioInterruption);
    
      return base.FinishedLaunching(app, options);
    }

    private void AudioInterruption(object sender, AVAudioSessionInterruptionEventArgs e)
    {
      switch (e.InterruptionType)
      {
        case AVAudioSessionInterruptionType.Began:
          // save the last playing state.
          WasPlaying = CrossMediaManager.Current.IsPlaying();
          break;
        case AVAudioSessionInterruptionType.Ended:
          // if the player was laying before the interruption, resume playback.
          if (WasPlaying) CrossMediaManager.Current.Play();
          break;
      }
    }
```

**Comment by BuddyLReno** [comment]
To get around this not being supported for now, I added a hook into the app delegate for the iOS project. Since the AV Player is an operating level singleton, it's accessible anywhere.  

```c#
using AVFoundation;

// other code

private void AudioInterruption(object sender, AVAudioSessionInterruptionEventArgs e)
{
  if (e.InterruptionType == AVAudioSessionInterruptionType.Ended)
  {
    CrossMediaManager.Current.Play();
  }
}
```

**Comment by martijn00** [comment]
@BuddyLReno would this work for you: https://github.com/martijn00/XamarinMediaManager/commit/0bbb22f1dcda74cf0606a38d3c10c8fcdbabe5cd

**Comment by BuddyLReno** [comment]
@martijn00 Looks like that should work!
