### ISSUE TITLE
Help Setting Up The Environment Properly to Contribute

### ISSUE THREAD

**Issue by BuddyLReno** [martijn00/XamarinMediaManager#618]
## 💬 Questions and Help

@martijn00 I'd like to help contribute as I've got a couple solutions to some things I see missing on the iOS side, but I'm unable to build this project successfully on Windows or Mac, making it kind of hard to test. Since all the platform code isn't in specific projects, I don't think I can just exclude platforms I can't build due to environment. What is the process to properly build and test on a mac or windows OS?

Chiefly, I'd like to take a stab at adding:
- Audio interruption resuming on iOS
- More granular hooks for turning off and on notification features
- iOS control center scrubber support

**Comment by martijn00** [comment]
Would be great to get some contributions! To start developing you need to install the very latest Visual studio versions, that were released only yesterday. Before that you had to run a preview version. On windows you need to have the UWP SDK installed, and on both you need the latest .net core 3.0. Also you need to have the Android SDK 9.0.

It is possible to switch to only building one target: https://github.com/martijn00/XamarinMediaManager/blob/develop/Directory.build.props#L61
But i don't think that helps much in your case. You just need the right software installed.

The things you mention sound like great areas to work on. If there is no issue open for them, please open one so we can track status per issue. If you have questions during development or about architecture, send me a DM.
