### ISSUE TITLE
[IOS] VideoView without quit button

### ISSUE THREAD

**Issue by FeduniakVitalii** [martijn00/XamarinMediaManager#619]
## 🐛 Bug Report

VideoView doesn't has close button. 
In IOS we can't go back from video page.

### Expected behavior
Close button needed near the fullScreen button.
### Reproduction steps
Creating page, and in content put:
 <StackLayout>
            <mm:VideoView x:Name ="VideoView"  VerticalOptions="FillAndExpand" 
              ShowControls="true" VideoAspect="AspectFit" BackgroundColor="Black"/>
        </StackLayout>

**Version:** 0.6.7

**Platform:** 
- [ ] :iphone: iOS

**Comment by martijn00** [comment]
You need to wrap it in a NavigationPage yourself, or add an overlay with close button. Also you are on a old version.

**Comment by FeduniakVitalii** [comment]
> You need to wrap it in a NavigationPage yourself, or add an overlay with close button. Also you are on a old version.

In new versions native controls have this button?
