### ISSUE TITLE
Current time with milliseconds precision

### ISSUE THREAD

**Issue by premingiet** [martijn00/XamarinMediaManager#635]
i am using a timer to get current time of media. And i am using like 10 milliseconds timer. But player is giving out current time too slow. I am not getting that milliseconds precision.

**Comment by martijn00** [comment]
Fill out a proper issue template! Any next issue will be closed if it is not filled out.

P.S. look at https://github.com/martijn00/XamarinMediaManager/blob/develop/MediaManager/MediaManagerBase.cs#L36
