### ISSUE TITLE
Unable to provide custom IMediaNotificationManager implementation (Android)

### ISSUE THREAD

**Issue by beko1997** [martijn00/XamarinMediaManager#72]
I'm seeking for a way to implement a custom notification. Specificly I want to be able to change some of the style elements like the background color and buttons. 

The **MediaManagerImplementation** provides a setter for the **MediaNotificationManager** but I'm unable to get the MediaSession Token. So the notification won't show. The default MediaNotificationManager will also be regenerated after adding a new item to the Queue.

Is there a way to get the MediaSession token? Or am I looking at the wrong approach here?

**Comment by bubavanhalen** [comment]
With the current implementation it is not possible without using some dirty Reflection to get a value form an internal property .

I just changed the visibility of the Session property and added it to the current Pull Request => https://github.com/martijn00/XamarinMediaManager/pull/70

Just check the last [commit](https://github.com/martijn00/XamarinMediaManager/pull/70/commits/8ef48d6d708889309b20975bb2e2ebce11c5e78b). If the pull Request gets merged you are able to get it with: 
`((MediaManagerImplementation)CrossMediaManager.Current).MediaSessionManager.CurrentSession.SessionToken;`

**Comment by bubavanhalen** [comment]
With the current implementation it is not possible without using some dirty Reflection.

I fixed the reinitialization of the `MeidaNotificationManager `and set the visibilty level from the CurrentSession to public and added the changes to the current Pull Request => https://github.com/martijn00/XamarinMediaManager/pull/70
As soon this gets merged you can get token by using this:
`((MediaManagerImplementation)CrossMediaManager.Current).MediaSessionManager.CurrentSession.SessionToken;`

**Comment by beko1997** [comment]
Allright, thanks for the update!
