### ISSUE TITLE
Xamarin Forms - How get raw/example.mp3

### ISSUE THREAD

**Issue by kikolopes90** [martijn00/XamarinMediaManager#73]
I use xamarin forms pcl, i can not fetch the file is in the raw folder. How do I do?

![screenshot_1](https://cloud.githubusercontent.com/assets/21179985/20629353/f9f22cc4-b322-11e6-887a-42d4b04e28ac.png)

```
var siren = CrossMediaManager.Current;

if (!resultA)
{
   SirenSource.Source = "noaudio.png";
   await siren.Play("siren.mp3", MediaFileType.AudioUrl);
   resultA = true;
}
else
{
   SirenSource.Source = "audio.png";
   await siren.Stop();
   resultA = false;
}
```

**Comment by martijn00** [comment]
This is not an issue, but a question for something like StackOverflow.
