### ISSUE TITLE
Android - Exception "No player is set"

### ISSUE THREAD

**Issue by jmartine2** [martijn00/XamarinMediaManager#76]
I am randomly encountering this error. It is coming from MediaManagerBase.CurrentPlaybackManager' getter:

```
            get
            {
                if (_currentPlaybackManager == null && _currentMediaFile != null) SetCurrentPlayer(_currentMediaFile.Type);

                if (_currentPlaybackManager == null) throw new Exception("No player is set");
                _currentPlaybackManager.RequestHeaders = RequestHeaders;
                return _currentPlaybackManager;
            }

```

The first line is calling SetCurrentPlayer(), which is as follows:

```
        private void SetCurrentPlayer(MediaFileType fileType)
        {
            if (_currentPlaybackManager != null)
            {
                RemoveEventHandlers();
            }
            switch (fileType)
            {
                case MediaFileType.AudioUrl:
                case MediaFileType.AudioFile:
                    _currentPlaybackManager = AudioPlayer;
                    break;
                case MediaFileType.VideoUrl:
                case MediaFileType.VideoFile:
                    _currentPlaybackManager = VideoPlayer;
                    break;
                case MediaFileType.Other:
                    break;
                default:
                    throw new ArgumentOutOfRangeException();
            }
            AddEventHandlers();
        }
```

The only code path that I can see that would permit _currentPlaybackManager to remain null (and thus cause the exception) is if the fileType passed in is MediaFileType.Other.

Any thoughts on how to fix this?

**Comment by jmartine2** [comment]
I did some more testing, and found that when this issue is occurring, when the getter is called, both _currentPlaybackManager and _currentMediaFile are both null. Therefore, SetCurrentPlayer() is never called. In this case, the getter will always throw an exception.

In looking at the stack traces from my crashes, in every case, this happens when MediaManagerBase.Pause() is called, which accesses CurrentPlaybackManager and the exception thus occurs.

I thought of two ways of fixing it:

1) Modify the Pause() method to check to see if _currentMediaFile is null or not:

```
        public async Task Pause()
        {
            if (_currentMediaFile != null)
                await CurrentPlaybackManager.Pause();
        }
```

2) The other idea is to modify the getter so that instead of throwing an exception if _currentPlaybackManager is null, have the getter return null in that case instead. Then, add a null reference check (of CurrentPlaybackManager) in Pause() (and possibly other places where it is accessed.

For now, I have made the change in Option 1 in my version of the source, and will continue testing. If anyone things that Option 2 is better, let me know.

**Comment by BergQuester** [comment]
I've gotten this exception on iOS too when calling `CrossMediaManager.Current.Stop()` when nothing has been played to begin with.

I find the behavior of throwing an exception rather than doing nothing very strange. Therefore, I wholeheartedly agree with @SimonSimCity. Return `null` and let the programmer deal with it. In my case, update the code that `Stop()` uses to do nothing if it is null.

**Comment by jmartine2** [comment]
I made the Option 2 changes. The getter will now return Null. I also added null reference checks wherever it is accessed. See Pull Request #86 .
