### ISSUE TITLE
Android - Java.Lang.RuntimeException: Invalid notification (no valid small icon)

### ISSUE THREAD

**Issue by jmartine2** [martijn00/XamarinMediaManager#77]
I am getting this exception randomly on certain devices. Looking at the stack trace on the crash, it appears to be coming from MediaNotificationManagerImplementation.StartNotification().

According to this StackOverflow question:
http://stackoverflow.com/questions/33642484/android-notificationmanager-giving-me-no-valid-small-icon-error

It appears that it is caused by not setting the small icon in the notification builder.  Here's the code in XMM that should be doing this:

```
var icon = (_appliactionContext.Resources?.GetIdentifier("xam_mediamanager_notify_ic", "drawable", _appliactionContext?.PackageName)).GetValueOrDefault(0);
           
...

_builder.SetSmallIcon(icon != 0 ? icon : _appliactionContext.ApplicationInfo.Icon);

```

So, it would seem that it can find neither the xam_mediamanager_notify_ic resource, or  _appliactionContext.ApplicationInfo.Icon.  To fix this, do I need to provide the xam_mediamanager_notify_ic resource in my own application package?

**Comment by bubavanhalen** [comment]
Yes exactly, but we should add this as a bug if the ApplicationInfo.Icon isn't working as Fallback in all cases.

**Comment by jmartine2** [comment]
Actually, I just checked, and in my Android Manifest tab in the Android project properties in Visual Studio, I didn't have the Application Icon set. I just set it, so hopefully that will fix the problem for me.
