### ISSUE TITLE
Calling MediaQueue.Clear() does not clear current

### ISSUE THREAD

**Issue by BergQuester** [martijn00/XamarinMediaManager#85]
After stopping playback, I am attempting to discard all items in the MediaQueue. However, calling `MediaQueue.Clear()` keeps the current item cached. Setting `CrossMediaManager.Current.MediaQueue = null;` causes the manager to crash when attempting to start a new item later.

**Comment by perfectsine** [comment]
@BergQuester Were you ever able to resolve this?  I am now experiencing something similar as well.
