### ISSUE TITLE
Android: "Handle must be valid" exception in MediaSessionManager.UpdatePlaybackState()

### ISSUE THREAD

**Issue by jmartine2** [martijn00/XamarinMediaManager#87]
I have been getting this exception in MediaSessionManager.UpdatePlaybackState(), in the call to MediaSessionCompat.SetPlaybackState().

According to [this report](https://bugzilla.xamarin.com/show_bug.cgi?id=47577), This appear to be a Xamarin garbage collection bug.

I have fixed this using the temporary solution listed in that report. Pull request to come soon.

**Comment by SimonSimCity** [comment]
@jmartine2 if you have some time at hand, I guess the team is still searching for a repo where this bug is present, since the issue is set to *INFONEEDED* :wink:
