### ISSUE TITLE
1.2.2 could crash on earlier Android devices when starting the foreground service.

### ISSUE THREAD

**Issue by BajakiGabesz** [martijn00/XamarinMediaManager#894]
1.2.2 could crash on earlier Android devices when starting foreground service because the foregroundServiceType parameter is not known by some of the earlier operating systems such as Android Pie on Huawei P10.

https://github.com/Baseflow/XamarinMediaManager/blob/7f72e5b723e0fba418700bfa195a02db17f2433a/MediaManager/Platforms/Android/MediaSession/MediaBrowserService.cs#L144

I tested it on Xamarin.Forms and it causes crashes immediately on Android Pie and maybe on another operating system too. Should change when we are lower system version than Android 12:
`StartForeground(notificationId, notification);`

**Comment by martijn00** [comment]
Can you make a PR to add this check?

**Comment by BajakiGabesz** [comment]
Sure, will do it soon.

**Comment by BajakiGabesz** [comment]
The PR has been created.
