### ISSUE TITLE
Android: Un-pausing media does not raise MediaManager.StatusChanged event

### ISSUE THREAD

**Issue by jmartine2** [martijn00/XamarinMediaManager#90]
If you have a song playing and pause it, the MediaManager.StatusChanged event is raised, but when you un-pause it, the event is not raised.

**Comment by hmfp20** [comment]
I have the some problem to. Still no solution?

**Comment by Vencode** [comment]
Also facing this issue on the pre-release version. Is there a workaround for it ?
