### ISSUE TITLE
UWP: Un-pausing media makes it start from the beginning

### ISSUE THREAD

**Issue by beko1997** [martijn00/XamarinMediaManager#93]
> If a song is paused, and you un-pause it by calling MediaManager.PlayPause(), the song starts over from the beginning instead of continuing where it left off.

Issue #89 also exists on UWP.

**Comment by TheMiao** [comment]
Still have the same issue happened using 
PlaybackController.SeekTo(StreamingPosition)
MediaManager.PlaybackController.Play()
